### ISSUE TITLE
Update to 2023.1 on macos not possible

### ISSUE THREAD

**Issue by tobias992** [mullvad/mullvadvpn-app#4404] opened 2023-03-01 15:40 UTC
## Issue report

Operating system: macOS 13.2.1
App version: 2022.5

### Issue description

Update ends with "installation failed, please contact the software developer".

**Comment by faern** [comment] 2023-03-02 06:53
Are there any logs or screenshots available we can see? Maybe the download is corrupt, try downloading the installer again maybe.

**Comment by faern** [comment] 2023-03-02 12:38
I recommend you look at this guide for that type of error: https://mullvad.net/en/help/install-and-use-mullvad-app-macos/#trouble-install

**Comment by faern** [comment] 2023-03-20 13:20
I'll close this as we are unable to reproduce, and reporter does not provide more information.

**Closed as not planned by faern** 2023-03-20 13:20 UTC
Labels: macOS
