### ISSUE TITLE
Auto-connect setting not working

### ISSUE THREAD

**Issue by axeleklof** [mullvad/mullvadvpn-app#610] opened 2018-11-23 15:35 UTC
The app runs at startup and connects to the VPN service automatically even though I have auto-connect turned off. I want the app to run when I login but remain disconnected until i manually connect. Am I just misinterpreting what this setting actually does?
I'm running Windows 10 and Mullvad 2018.5

**Comment by Masterys** [comment] 2018-11-26 14:11
I have this same issue and I was about to open a issue on this. Also, I have completely disabled Mullvad from starting at startup but it still runs in the background (with no tray icon showing) because the service is still running. I have temporarily disabled the service by going to Services > "Mullvad VPN Service" > Right Click, select Properties and set Startup type to either Disabled or Manual.

**Comment by Masterys** [comment] 2018-11-26 14:13
@faern Is there way to escalate the priority of this issue?

**Comment by faern** [comment] 2018-11-30 15:56
@axeleklof Yes, I agree these settings are confusing at the moment. It works like this: We have a system service always running in the background. It starts on computer boot no matter what you have set any setting to. It's a vital part of the product and needed for us to be able to provide a secure, reliable and safe experience. When you activate `auto-connect` that makes this system service connect the to the VPN directly on boot. So far none of this has anything to do with the GUI / tray bar icon app. So the `auto-launch`/`auto-start` option makes the GUI app start on user login. But starting the GUI force-triggers the system service to connect to the VPN. Thus if you have `auto-connect` disabled but `auto-launch` enabled the system service will *not* connect directly when the computer boots. But when you log in to your user account the GUI will start and *that will* connect the VPN for you.

We are currently working on adding support for starting the GUI without connecting the VPN, but this is not yet done. Expect this to be available in a version or two. Sorry for the inconvenience.

**Comment by faern** [comment] 2018-11-30 16:01
@Masterys The tray icon is part of the frontend GUI app, not the system service. The system service is intended to always run. The system service does absolutely nothing unless you have `auto-connect` enabled or you interact with it using the GUI or CLI frontends so it should really not hurt to have it running. If you really want it to not run you will have to manually disable this system service or uninstall the app. It's always running by design and an integral part of how we can ensure reliable security and network leak protection.

Having the system service shut down as you exit the GUI would have multiple downsides. It would require you to escalate to administrator and accept the annoying administrator privilege dialogs every time you start the app for example. This would be terrible UX for most people.

A lot of programs/apps/products out there start their own system service and it's nothing strange about that really. Especially products who are related to networking and/or system security. Take firewalls and anti-virus for example.

**Comment by faern** [comment] 2018-11-30 16:02
I'm going to close this as it's not really a bug. Just a slight missing feature and bad explanation of current functionality that you can't start the GUI without triggering a VPN connection. And allowing that feature is already part of our internal roadmap.

**Closed by faern** 2018-11-30 16:02 UTC

**Comment by a-gunderin** [comment] 2024-09-22 01:06
@faern
I use Mullvad VPN occasionally (Windows 10), so I don’t need the Mullvad VPN service running automatically and consuming resources.
I’d like it to only run when I start the Mullvad VPN app.
However, if I set the service to manual, the app doesn’t work, and I have to manually start it in Windows Services, which isn’t ideal.
Is there a way to prevent it from running automatically but have it start only when I open the Mullvad VPN app?
