### ISSUE TITLE
Windows App 2023.1: Service Error Code 1

### ISSUE THREAD

**Issue by HJLBX** [mullvad/mullvadvpn-app#4377] opened 2023-02-21 01:42 UTC
Mullvad Windows app 2023.1 service will not start during the installation sequence, and subsequently the App hangs as it is attempting to connect to the service.

If attempt to start it manually, it throws an Error Code 1.

Windows 11 22H2

**Comment by faern** [comment] 2023-02-21 08:35
Could you please send a problem report? The problem reports in the UI should be accessible even though it can't reach the system service. Please refer to this issue in the problem report description. Thanks.

**Comment by citrixscu** [comment] 2023-02-21 15:46
This looks related to #4376. Here is a log file from a Windows VM.

Host: Windows 11 22H2, VMware Workstation Pro 17
Guest: Windows 11 Dev 23500.1000

```
System information:
mullvad-product-version: 2023.1
os: Windows 11 Build 25300

====================
Log: \\?\C:\ProgramData\Mullvad VPN\daemon.log
====================
[2023-02-21 07:36:18.079][mullvad_daemon::version][INFO] Starting mullvad-daemon - 2023.1 2023-02-20
[2023-02-21 07:36:18.079][mullvad_daemon][INFO] Logging to C:\ProgramData\Mullvad VPN
[2023-02-21 07:36:18.081][mullvad_daemon::system_service][INFO] Service started.
[2023-02-21 07:36:18.081][mullvad_daemon::system_service][DEBUG] Update service status: StartPending, checkpoint: 1, wait_hint: 1s
[2023-02-21 07:36:18.093][mullvad_paths::settings][ERROR] Failed to obtain system app data path: Process ID for C:\WINDOWS\system32\lsass.exe not found
[2023-02-21 07:36:18.093][mullvad_daemon::system_service][ERROR] Error: Unable to get settings dir
Caused by: Not able to find requested directory
[2023-02-21 07:36:18.093][mullvad_daemon::system_service][DEBUG] Update service status: Stopped, checkpoint: 0, wait_hint: 0ns
[2023-02-21 07:36:18.094][mullvad_daemon][DEBUG] Process exiting with code 0
```

**Comment by HJLBX** [comment] 2023-02-21 16:23
> Could you please send a problem report? The problem reports in the UI should be accessible even though it can't reach the system service. Please refer to this issue in the problem report description. Thanks.

Unfortunately I cannot as I am not using a VM; I am using a real system and when installing 2023.1 it completely blocks networking because of this issue. So I had to uninstall it and revert to 2022.5. Also I only have 3 license\connection seats which are fully used. I would need an additional seat for VM testing.

**Comment by dlon** [comment] 2023-02-21 18:17
Closing as it's a duplicate of #4376.

**Closed by dlon** 2023-02-21 18:17 UTC
Labels: bug, Windows
