### ISSUE TITLE
JS Error in journalctl when trying to connect

### ISSUE THREAD

**Issue by danielsouzat** [mullvad/mullvadvpn-app#1775] opened 2020-05-21 01:33 UTC
I'm constantly getting this error on systemd journal. It happens every time I click in connect.

```
mai 20 22:02:18 hostname appindicatorsupport@rgcjonas.gmail.com[1907]: Mullvad VPN1, Impossible to lookup icon for 'Mullvad VPN1_2-panel'
mai 20 22:02:18 hostname gnome-shell[1907]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                              _createIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:406:26
                                              _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:368:14
                                              _updateIconByType@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:574:18
                                              _updateIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:601:14
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                              _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:220:22
                                              _onPropertiesChanged@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:15
                                              refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:51:19
mai 20 22:02:18 hostname gnome-shell[1907]: Removing a network device that was not added
mai 20 22:02:18 hostname appindicatorsupport@rgcjonas.gmail.com[1907]: Mullvad VPN1, Impossible to lookup icon for 'Mullvad VPN1_3-panel'
mai 20 22:02:18 hostname gnome-shell[1907]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                              _createIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:406:26
                                              _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:368:14
                                              _updateIconByType@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:574:18
                                              _updateIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:601:14
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                              _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:220:22
                                              _onPropertiesChanged@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:15
                                              refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:51:19
mai 20 22:02:18 hostname appindicatorsupport@rgcjonas.gmail.com[1907]: Mullvad VPN1, Impossible to lookup icon for 'Mullvad VPN1_4-panel'
mai 20 22:02:18 hostname gnome-shell[1907]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                              _createIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:406:26
                                              _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:368:14
                                              _updateIconByType@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:574:18
                                              _updateIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:601:14
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                              _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:220:22
                                              _onPropertiesChanged@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:15
                                              refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:51:19
mai 20 22:02:18 hostname appindicatorsupport@rgcjonas.gmail.com[1907]: Mullvad VPN1, Impossible to lookup icon for 'Mullvad VPN1_5-panel'
mai 20 22:02:18 hostname gnome-shell[1907]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                              _createIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:406:26
                                              _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:368:14
                                              _updateIconByType@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:574:18
                                              _updateIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:601:14
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
                                              _onPropertiesChanged/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:220:22
                                              _onPropertiesChanged@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:214:15
                                              refreshPropertyOnProxy/<@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/util.js:51:19
mai 20 22:02:18 hostname appindicatorsupport@rgcjonas.gmail.com[1907]: Mullvad VPN1, Impossible to lookup icon for 'Mullvad VPN1_6-panel'
mai 20 22:02:18 hostname gnome-shell[1907]: JS ERROR: Exception in callback for signal: icon: Error: Argument 'filename' (type filename) may not be null
                                              _createIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:406:26
                                              _cacheOrCreateIconByName@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:368:14
                                              _updateIconByType@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:574:18
                                              _updateIcon@/usr/share/gnome-shell/extensions/appindicatorsupport@rgcjonas.gmail.com/appIndicator.js:601:14
                                              _emit@resource:///org/gnome/gjs/modules/core/_signals.js:133:47
```
I'm using Manjaro..

**Comment by faern** [comment] 2020-05-25 14:41
Seems to be a problem with Electron, gnome-shell or appindicator.. Not sure. But I assume the app works as intended?

**Comment by danielsouzat** [comment] 2020-05-25 17:31
Actually it is stuck at *Creating secure connection* but IDK if it is related.

It is working on my phone and on the PC it doesn't even after disabling *ufw* firewall. Anyway I'm not blocking outgoing connections.

I have reported the problem through the app but basically this is the error at frontend.log:

```
[2020-05-25 14:27:22.666][warn] Failed to fetch account data. Retrying in 8000 ms
[2020-05-25 14:27:22.666][warn] Got reply to REDACTED but no one was waiting for it
[2020-05-25 14:27:40.670][warn] Request REDACTED  timed out:  {
```

**Comment by faern** [comment] 2020-06-01 07:56
We did a quick test in Manjaro and we can't reproduce this issue. We don't officially support Manjaro so we won't put more effort into this right away. Hopefully it will be resolved by an Electron upgrade or other GUI improvement soon.

**Comment by faern** [comment] 2020-06-01 07:58
> I have reported the problem through the app but basically this is the error at frontend.log:

That error is common to see when there are network timeouts. I don't think it has anything to do with the issues you are seeing in journalctl.

Please send a problem report to support, inside the app. They can then help you from there.

**Closed by faern** 2020-06-01 07:58 UTC
