### ISSUE TITLE
multi-subnet local network sharing

### ISSUE THREAD

**Issue by altaic** [mullvad/mullvadvpn-app#2674] opened 2021-04-15 22:55 UTC
## Issue report

Operating system: macOS 11.2.3

App version: 2021.2

### Issue description

Local network sharing only works for a single subnet, but many local networks have multiple subnets, e.g. 192.168.0.5 needs to communicate with 192.168.23.2. Please add a setting for the local network netmask, or at least default to `/16`.

**Comment by faern** [comment] 2021-04-16 14:37
If you enable local network sharing you can already send traffic to any private IP range. So this is already possible. You just need to set up your routing table correctly.

The VPN tunnel sucks up any traffic that is destined for the otherwise default route. So if you are on the network `192.168.0.0/24` and want to communicate with `192.168.1.0/24` but you don't have a dedicated routing table entry for it then it will not work. Because your LAN is not properly set up. In that case you rely on the traffic being sent to your router and from there correctly routed to your other local subnet.

If your router that bridges your two subnets is at `192.168.0.1` and you want to allow talking to all of `192.168.1.0/24` then run this in a terminal:
```
sudo route -n add -net 192.168.1.0/24 192.168.0.1
```

**Comment by faern** [comment] 2021-04-28 11:40
I'm closing this as it's not a missing feature. Or at least should not be. It should work correctly if you set routes correctly. Please re-open if there is something preventing this from working as intended.

**Closed by faern** 2021-04-28 11:40 UTC

**Comment by mickdekkers** [comment] 2021-07-17 09:15
Here's the command for Windows in case anyone else needs it:
```ps1
route -p ADD 192.168.1.0 MASK 255.255.255.0 192.168.0.1
```

Adjust the subnet, the mask and router IP respectively as you need them 🙂

**Comment by faern** [comment] 2022-07-31 12:24
Make your router advertise it? If your router provides access to multiple networks, and you use DHCP in your network, you probably want to make your router advertise all those networks

**Comment by faern** [comment] 2022-09-09 13:48
No, BGP is something different. You don't want to use BGP on your LAN :)

I'm not that familiar with OpenWrt, but this looks like what you want: https://www.reddit.com/r/openwrt/comments/pywj4d/question_how_to_push_route_table_routes_down_to/

**Comment by SimonBrazell** [comment] 2023-06-11 05:11
FYI -

I got it working via OpenWRT settings, add the following to the `/etc/config/dhcp` file for the interface you want the routes pushed from (e.g. `lan`):

```
config dhcp 'lan'
	option interface 'lan'
        ...
	list dhcp_option '249,192.168.3.0/24,192.168.1.1'
	list dhcp_option '121,192.168.3.0/24,192.168.1.1'
```
The above would be similar to running this on the client device - `sudo route -n add -net 192.168.3.0/24 192.168.1.1`.

These can be added via Luci too at `Interfaces » lan » DHCP Server » Advanced Settings » DHCP-Options`
