### ISSUE TITLE
No connection on Wake from Sleep on MacOS

### ISSUE THREAD

**Issue by adunanya** [mullvad/mullvadvpn-app#3922] opened 2022-09-12 01:51 UTC
I've had this issue twice now this week after waking up my MacBook from sleep state (opening the lid and logging in with touchID). When I open up my MacBook Air, my WiFi connects but has an explanation point over the wifi symbol after a few seconds in the tray area that says "no internet" on hover... and Mullvad says in the client: "connection blocked". I tried disabling the 'always on firewall' feature and tried switching protocols to openVPN, but it does not fix the issue. I also disabled wifi and turned it back on and it still doesn't connect or sense any internet connection. I checked the IP and it says it can't communicate with the router ("no ip") in Network settings. The only thing that I can do at that point is to restart my laptop and then everything's back to normal. It happened on Friday for me and also today this morning. Again, this is after I've closed the lid and just let the computer sleep before I go to bed and upon 'waking it up' in the morning, that's what happens.

As I understand, iVPN uses the same code structure to keep the firewall "always on" (which I totally LOVE by the way), but they've never had this issue and I used them for years before switching to you guys. I assume it's your built in always-on firewall... (please don't remove that!).. but I can't imagine what this could be from. It's just really annoying have to do a full restart twice a week. Please make this a top priority to fix guys! Really ruins the wireguard experience too </3 Thank you Mullvad team. System info below:

MacBook Air 11" 2020
MacOS: 11.5.2 Big Sur
Mullvad Client Version 2022.3

**Comment by pinkisemils** [comment] 2022-09-13 14:53
Would you mind sending a problem report from the app? The always-on-firewall should not interfere with macOS's connectivity check when coming out of sleep. Could you please also post the output of `nslookup captive.apple.com` when this happens?

**Comment by pinkisemils** [comment] 2022-09-13 14:55
Seemingly a duplicate of #3895.

**Closed by pinkisemils** 2022-09-13 14:55 UTC
