### ISSUE TITLE
2020.4 Debian 10 LXQT wrong tray icon

### ISSUE THREAD

**Issue by mastercoldcoder** [mullvad/mullvadvpn-app#1744] opened 2020-05-12 15:23 UTC
## Issue report

Operating system: Debian 10 Buster LXQT

App version: 2020.4

### Issue description

I would like to inform you that I can no longer launch the mullvad application, I'm blocked on this screen
<a href="https://zupimages.net/viewer.php?id=20/20/91ls.png"><img src="https://zupimages.net/up/20/20/91ls.png" alt="" /></a>

Nothing works. I can't enter my account number.
In addition, the icon at the bottom of the LXQT desktop is displayed incorrectly.
<a href="https://zupimages.net/viewer.php?id=20/20/t1jj.png"><img src="https://zupimages.net/up/20/20/t1jj.png" alt="" /></a>

I hope I made myself clear, thank you for unblocking the situation and thank you again for your services. :+1:

**Comment by faern** [comment] 2020-05-12 16:15
Hi. Thanks for the report. Sadly it's very hard for us to do anything without any logs to indicate what might have gone wrong. Please take this issue with our support instead, they will be able to help you much better. You can send a problem report from within the app directly, that way they will automatically get the logs they will need to diagnose the problem. Just go to settings and "Report a problem".

**Comment by mastercoldcoder** [comment] 2020-05-12 18:43
Ok The problem was solved by installing : libappindicator3-1 before installing MullvadVPN-2020.4_amd64.deb .
The application launches without any problem and asks for my account number.
Connection ok, trayicon ok
Thanks to mulvad support for your help

**Comment by raksooo** [comment] 2020-05-13 10:19
I've been able to reproduce the tray icon issue and it seems to be LXQt specific. The tray icon shows up fine at first but when the app tries to change it into another icon, when connecting/disconnecting, it's turned into a cogwheel instead of the icon that the app provides. Hopefully this is solved without any action when we upgrade the app to Electron 8 which uses another tray icon API. If it isn't we'll look into it at some point after that.

**Comment by mateusbirnbaum** [comment] 2020-05-14 20:14
Same problem here with OpenSUSE Tumbleweed 20200508, under KDE 5.69.0,
Qt 5.14.1. The tray icon is just a gray/white little circle, no matter what is the status.
No issue however with OpenSUSE Tumbleweed 20200107, KDE 5.65.0, Qt 5.13.1.

**Comment by mateusbirnbaum** [comment] 2020-05-21 19:57
The tray icon issue is solved for me on (OpenSUSE Tumbleweed 20200508) by installing libappindicator3 and the dependency libindicator3.
Interestingly the icon's behavior also changed, clicking on the icon does *not* open the GUI but a little menu where one has to click on the entry 'Mullvad VPN' to open the GUI.

**Comment by faern** [comment] 2020-05-25 09:09
This issue will be automatically fixed the next time we upgrade Electron. However, other tray icon issues upstream stops us from currently adopting a newer Electron version. We hope that can be resolved rather soon.

**Comment by raksooo** [comment] 2020-10-21 11:37
This issue was first fixed by upgrading to Electron 8 which included a new tray icon implementation but was then reverted due to bugs in the new implementation (https://github.com/electron/electron/pull/23674).

There is an issue in Electron about this which has unfortunately been closed, https://github.com/electron/electron/issues/15124. That thread contains a workaround as well which work for me, but could have some unknown effects as well.

**Comment by raksooo** [comment] 2020-10-21 12:23
The simplest way to add the workaround would be to edit `/usr/share/applications/mullvad-vpn.desktop` by changing the `Exec=` line to 
```
Exec=env XDG_CURRENT_DESKTOP=KDE "/opt/Mullvad VPN/mullvad-gui" %U
```
This seem to take effect after logging out and in again.

This will be overwritten when the app is updated though so it needs to be done after each update. And as I said in the previous comment, I don't know if this could cause any other issues within the app.

**Comment by raksooo** [comment] 2020-10-21 12:24
Since there's nothing that can be done on our end I'll close this.

**Closed by raksooo** 2020-10-21 12:24 UTC
Labels: Desktop frontend, Linux, bug
