### ISSUE TITLE
Connecting to mullvad system service

### ISSUE THREAD

**Issue by anatolykopyl** [mullvad/mullvadvpn-app#2678] opened 2021-04-16 22:26 UTC
## Issue report

Operating system: macOS Big Sur 11.2.3

App version: 2021.3-beta1, 2021.2, 2020.7, 2020.6

### Issue description

First screen stuck on "Connecting to mullvad system service...".

The in-app error report system fails. This is the error log:
```
System information:
id: cceb197d-890d-4f32-b93a-0d09f9a9b871
mullvad-product-version: 2021.3-beta1
os: macOS 11.2.3

====================
Log: /private/var/log/mullvad-vpn/preinstall.log
====================
Running preinstall at Sat Apr 17 01:16:34 MSK 2021
Failed to send 'prepare-restart' command to old mullvad-daemon

====================
Log: /private/var/log/mullvad-vpn/postinstall.log
====================
Running postinstall at Sat Apr 17 01:16:34 MSK 2021
Failed to copy old daemon log
Unable to kill GUI, not running?

====================
Log: ~/Library/Logs/Mullvad VPN/frontend-main.log
====================
[2021-04-17 01:17:49.168][debug] Chromium sandbox disabled: false
[2021-04-17 01:17:49.171][info] Running version 2021.3-beta1
[2021-04-17 01:17:49.238][info] Detected locale: en-US
[2021-04-17 01:17:59.241][error] Failed to connect to daemon: Failed to connect before the deadline
[2021-04-17 01:18:00.598][debug] Problem report was written to /var/folders/z6/7fpsbjbx3753bz99d59j6vxh0000gn/T/6604d9e7-7b85-481e-946e-dfef44bb1465.log
[2021-04-17 01:18:12.253][error] Failed to connect to daemon: Failed to connect before the deadline
[2021-04-17 01:18:12.254][error] Failed to reconnect - Error: Failed to connect before the deadline
[2021-04-17 01:18:25.259][error] Failed to connect to daemon: Failed to connect before the deadline
[2021-04-17 01:18:25.260][error] Failed to reconnect - Error: Failed to connect before the deadline
[2021-04-17 01:18:38.266][error] Failed to connect to daemon: Failed to connect before the deadline
[2021-04-17 01:18:38.267][error] Failed to reconnect - Error: Failed to connect before the deadline

====================
Log: ~/Library/Logs/Mullvad VPN/frontend-main.old.log
====================
[2021-04-17 01:16:46.072][debug] Chromium sandbox disabled: false
[2021-04-17 01:16:46.078][info] Running version 2021.3-beta1
[2021-04-17 01:16:46.156][info] Detected locale: en-US
[2021-04-17 01:16:56.158][error] Failed to connect to daemon: Failed to connect before the deadline
[2021-04-17 01:17:09.170][error] Failed to connect to daemon: Failed to connect before the deadline
[2021-04-17 01:17:09.170][error] Failed to reconnect - Error: Failed to connect before the deadline
[2021-04-17 01:17:22.181][error] Failed to connect to daemon: Failed to connect before the deadline
[2021-04-17 01:17:22.182][error] Failed to reconnect - Error: Failed to connect before the deadline
[2021-04-17 01:17:29.967][debug] Problem report was written to /var/folders/z6/7fpsbjbx3753bz99d59j6vxh0000gn/T/e7b89b13-cc15-46e5-a467-fb93e619df22.log
[2021-04-17 01:17:29.982][error] Failed to send a problem report.
              Stdout: 
              Stderr: Error: Unable to create REST client
Caused by: Failed to load address cache
Caused by: Failed to open the address cache file
Caused by: No such file or directory (os error 2)

[2021-04-17 01:17:35.004][error] Failed to send a problem report.
              Stdout: 
              Stderr: Error: Unable to create REST client
Caused by: Failed to load address cache
Caused by: Failed to open the address cache file
Caused by: No such file or directory (os error 2)

[2021-04-17 01:17:35.193][error] Failed to connect to daemon: Failed to connect before the deadline
[2021-04-17 01:17:35.194][error] Failed to reconnect - Error: Failed to connect before the deadline
[2021-04-17 01:17:46.621][info] Cannot close the tunnel because there is no active connection to daemon.

====================
Log: ~/Library/Logs/Mullvad VPN/frontend-renderer.log
====================
[2021-04-17 01:17:49.845][debug] Tunnel state: disconnected

====================
Log: ~/Library/Logs/Mullvad VPN/frontend-renderer.old.log
====================
[2021-04-17 01:16:46.900][debug] Tunnel state: disconnected
```

**Comment by faern** [comment] 2021-04-19 13:04
Thanks for reporting this! We'll look into it

**Comment by pinkisemils** [comment] 2021-04-19 13:51
Does `/Library/LaunchDaemons/net.mullvad.daemon.plist` exist? If it does, can you start the daemon via 
```bash
launchctl load -w /Library/LaunchDaemons/net.mullvad.daemon.plist
``` ? 
Can you execute the daemon at all in a shell?
```bash
/Applications/Mullvad \VPN.app/Contents/Resources/mullvad-daemon --version
```

**Comment by anatolykopyl** [comment] 2021-04-19 17:11
@pinkisemils 
First command returns `Load failed: 5: Input/output error`. If ran with `sudo` returns:
```
/Library/LaunchDaemons/net.mullvad.daemon.plist: Path had bad ownership/permissions
Load failed: 122: Path had bad ownership/permissions
```
But the following seems to work and prints the version. 
```
/Applications/Mullvad\ VPN.app/Contents/Resources/mullvad-daemon --version
```

**Comment by pinkisemils** [comment] 2021-04-20 09:12
GIven that `launchctl` is complaining about permissions, I'd like to see what are the permissions of our `plist` - could you post the output of `ls -alh /Library/LaunchDaemons/net.mullvad.daemon.plist`.  And just to double-check, how do you install our app? I assume you just double click on the `pkg` file, and then use the installer with it's UI. 

The reason I'm asking is that from the logs you've supplied, I can clearly see that our [`postinstall`](https://github.com/mullvad/mullvadvpn-app/blob/master/dist-assets/pkg-scripts/postinstall) script gets executed, and it should create the launch file for our daemon.

**Comment by anatolykopyl** [comment] 2021-04-20 09:37
The output is:
```
-rw-rw-r--  1 root  wheel   1.0K Apr 17 01:16 /Library/LaunchDaemons/net.mullvad.daemon.plist
```
Yes, I did use the UI installer.

Don't know if this is useful info, but running `/Applications/Mullvad\ VPN.app/Contents/Resources/mullvad-daemon` without sudo errors out with:
```
Error: Unable to get log directory
Caused by: Failed to set directory permissions on /var/log/mullvad-vpn
Caused by: Operation not permitted (os error 1)
```
But with sudo works and the app seems to work alright while the daemon is running. Not sure if it is supposed to be ran with privileges though.

**Comment by pinkisemils** [comment] 2021-04-20 10:22
I believe running it with `sudo` won't break anything any further, but really, it should be launchable as a service via `launchctl`. 
I think you can _fix_ it via `sudo chmod 644  /Library/LaunchDaemons/net.mullvad.daemon.plist`. I still don't know the root cause of why the installer behaves differently on your machine to seemingly every other machine we've ever seen. But I think setting the permissions in the script should fix this for you.

**Comment by anatolykopyl** [comment] 2021-04-20 10:29
Thank you!

**Comment by pinkisemils** [comment] 2021-04-20 10:30
I'll keep the issue open until I've merged a fix for the installer script.

**Closed** 2021-04-20 13:33 UTC
