### ISSUE TITLE
[Feature Request] - Filter by RAM / DISK based server

### ISSUE THREAD

**Issue by DPTJKKVH** [mullvad/mullvadvpn-app#3912] opened 2022-09-08 12:33 UTC
## Issue report

Operating system: Ubuntu 22.04 (But feature request is not OS specific.)

App version: 2022.4

### Issue description

The transition to a diskless infrastructure will take some time before completed. In the meantime a server filter category should be added, allowing the user to choose if they want to only connect to diskless servers, disk based servers or both. The filters should work identical to the provider filters and the "rented / owned" filters.

**Comment by faern** [comment] 2022-09-08 13:32
We are working on this. It will likely exist in the next version, or the one after that.

**Comment by DPTJKKVH** [comment] 2022-09-08 14:13
Glad to hear! Should I close this issue then or will you close it after the feature has been merged?

And btw @faern : You do a fantastic job managing/moderating the issue section. I'm involved in more projects than my account lets you know and I must say, the way you handle things is very welcoming and efficient at the same time. I don't want this to come off as butt kissing so I'll leave it at that but wanted to give you my feedback anyway.

**Comment by rblaine95** [comment] 2022-09-28 13:27
@git70 
On the right hand side of the issue is a button that will say "Subscribe" or "Unsubscribe"
You can click it to "Subscribe" to receive notifications of updates to an issue without having to leave a comment or participate in the issue itself.
<img width="399" alt="image" src="https://user-images.githubusercontent.com/4052340/192790634-939f413f-34be-4082-afec-3337ed50acf8.png">

**Comment by DPTJKKVH** [comment] 2022-12-12 20:41
@faern Is is slated for next release? :pray:

**Comment by faern** [comment] 2022-12-13 14:20
It is being developed. I can't promise it will make it to the next release, but it might!

**Comment by MarkusPettersson98** [comment] 2024-12-10 13:02
Closing this because all of our VPN infrastructure already run from RAM: https://mullvad.net/en/blog/we-have-successfully-completed-our-migration-to-ram-only-vpn-infrastructure :tada:

**Closed by MarkusPettersson98** 2024-12-10 13:02 UTC
Labels: feature request
