### ISSUE TITLE
Credit Expiry + Kill Switch = Broken Internet

### ISSUE THREAD

**Issue by mboudreau** [mullvad/mullvadvpn-app#4069] opened 2022-10-20 01:24 UTC
## Issue report

Operating system:  Windows 10

App version: 2022.5

### Issue description

I tried out Mullvad on my Windows PC for a month to see if it was adequate for my usage.  Everything seems to work great.  I think the Kill Switch is a neat idea, but I can see several problems with it which I discovered first hand: I was connected to Mullvad when my credit expired.  It automatically disconnected me, but the kill switch also activated it because of this and I couldn't use my internet anymore without paying for more credit, which I couldn't do on my PC since I had no internet.

If you're going to have a feature like Kill Switch, you better test _all possible scenarios like your life depends on it_.  It's just bad development that this was my first experience with Mullvad.

**Comment by faern** [comment] 2022-10-20 05:34
Can you explain how you expected it to work? Because what you say is the intended functionality, it has been tested carefully.

Please consider a scenario where *your life depends on the VPN*. You browse around and use the internet and it's critical that no traffic leaks outside the tunnel. If your account expires, because you did not keep track of the time, or a payment failed for some reason. This user do not want traffic to flow freely outside the VPN suddenly and unknowingly if the account expires. They want internet cut. Then they can make a conscious decision on how to proceed and pay. Either they decide that they can unlock the internet and visit mullvad.net for a payment after they have closed all other programs. Or they want to call a friend, and have them top up their account via VPN or whatnot.

By design, our app never allows traffic to flow outside the tunnel automatically. The user always has to explicitly approve the disconnect action.

**Comment by kkarpieszuk** [comment] 2024-01-26 13:37
I have the same problem and I consider it as an issue, especially I cannot turn it off now. 

I just turned on some old laptop where I was using Mullvad but license is of course expired now. 

Now every time I start my laptop, it is not connected to the internet because _kill switch_ is blocking it. **I think this is correct until this point**

The problem is: I can't turn off this functionality without paying for the license again, am I correct? I don't see any option: just I can provide license key (so pay) or go to settings where there is no option other than closing mullvad app. Plus there is button to turn off kill switch, but I want to turn it off forever. Still, I need to every day open mullvad, click button to stop kill switch functionality, then close Mullvad app. 

Question is: can I disable kill switch without paying for license? If I uninstall mullvad, will thso solve the problem? (I did not try this as I am affraid if this will not dead lock me in a state where I cannot connect to internet anymore)

**Comment by raksooo** [comment] 2024-01-29 07:10
There should be a red "Disconnect"-button (or a red "Unblock"-button if logged out) that disengages the killswitch. Can you find these? Otherwise we have a bug related to their visibility.
<img width="432" alt="image" src="https://github.com/mullvad/mullvadvpn-app/assets/3668602/f099794b-3aae-494f-8100-b31a8755ad25">
<img width="432" alt="image" src="https://github.com/mullvad/mullvadvpn-app/assets/3668602/2380ed15-5270-4582-9d76-f85f80b2b064">

**Comment by kkarpieszuk** [comment] 2024-01-29 08:25
we have a misunderstanding here: I do see this button and it works. 

The problem I am having is: I don't want to click this button anymore. How to turn off it? 

I remember I enabled this button when I was paying for Mullvad. It was somewhere in the settings of the app, am I remembering this correctly?

Now, when license expired I don't have access to the app settings so I can't disable it. But the app is still blocking my internet untill I click do disable every time. 

The bug here is the fact I would like to have my internet working normally but I cannot unless I spend 5 USD only to go to the settings.

**Comment by MrChocolatine** [comment] 2024-01-29 09:36
Why not uninstalling Mullvad VPN if it is, clearly, of no use?

**Comment by raksooo** [comment] 2024-01-29 09:54
@kkarpieszuk The Mullvad VPN app has always had a kill switch that blocks your internet when running out of time. This kill switch has always been part of the app and has never been possible to disable.

A while ago we made that more clear by adding the toggle into the app. No functionality changed but we now show information about the kill switch in VPN Settings.

**Closed** 2024-01-29 10:01 UTC

**Comment by kkarpieszuk** [comment] 2024-01-29 10:16
If I uninstall the app, will my internet be working correctly? 

If yes, then really we are spending time on non existing problem :)

I asked  this question above but didn't get answer and I just don't want to uninstall and find I am in a trap (no app to disable  killswitch but killswitch still blocking my internet)

**Comment by raksooo** [comment] 2024-01-29 10:46
If you uninstall the app it will remove the kill switch and everything should be back to normal. The same goes for clicking the "Disconnect" button, unless you have enabled "Auto-connect", "Launch on startup" or "Lockdown mode" which will change the behavior of the app and enter the blocked state again later (or immediately if "Lockdown mode" is enabled).

**Comment by kkarpieszuk** [comment] 2024-01-29 13:18
thank you, this info satisfies me!
