### ISSUE TITLE
[Feature Request] new features for iOS

### ISSUE THREAD

**Issue by mikesk8** [mullvad/mullvadvpn-app#1655] opened 2020-04-11 18:18 UTC
Thanks for iOS app; great news:) 

Would it be possible to add:

1) kill switch
2) visible notification when there is no secure connect

Thanks,
Michael

**Comment by pronebird** [comment] 2020-04-14 21:44
Hi,

We’re currently testing the on-demand VPN and should be able to roll out an update very soon if everything goes as planned. 

We will look into notifications on iOS, if they make sense and if it’s possible to use them in the context of the VPN tunnel extensions on iOS.

Cheers,
Andrej

**Comment by pronebird** [comment] 2020-04-20 12:43
@mikesk8 Please update to Mullvad VPN 2020.2 via AppStore. On-demand VPN is automatically enabled for all new VPN configurations, and existing configuration when connecting VPN inside the app.

You can verify that on-demand VPN is enabled by going to iPhone Settings > VPN, locate WireGuard (Mullvad VPN) configuration and tap ℹ️. "Connect On Demand" toggle should be visible and enabled.

**Comment by faern** [comment] 2020-04-20 12:57
> kill switch

Almost a duplicate of #1649. At least the On-demand VPN is supposed to solve the similar problem.

> visible notification when there is no secure connect

The OS should automatically remove the VPN logo from your notification bar when you are not connected over a VPN. So that should be an already existing visual indication.

Closing this issue since both items seems solved. It's also not optimal to have multiple unrelated issues in the same issue report. Please open more specific issues if anything remains.

**Closed by faern** 2020-04-20 12:57 UTC
Labels: iOS
