### ISSUE TITLE
WinDbg  shows that Mullvad VPN failed with BlueScreen of death on my Microsoft Surface Laptop 5 on the latest Windows 11 24H2

### ISSUE THREAD

**Issue by leonid1812** [mullvad/mullvadvpn-app#7294] opened 2024-12-06 10:25 UTC
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

1. BlueScreen of death on my computer with Windows 11 24H2
2. OS rebooted periodically
3. Errors in the Windows log file

### Expected Behavior

Works without system rebooting

### Steps to Reproduce

1. Install Windows 24H2 on Microsoft Surface Laptop 5. Install all necessary updates.
2. Install the latest version of Mullavad

### Failure Logs

```shell
Hello,

I got the BlueScreen of death on my computer with Windows 11 24H2. I have installed the WinDbg utility and it shows that mullvad-wireguard.sys leads to this trouble.
This is example of dump;

BLACKBOXWINLOGON: 1

CUSTOMER_CRASH_COUNT:  1

PROCESS_NAME:  System

STACK_TEXT:  
ffffa101`3c9fab48 fffff805`c5d75129     : 00000000`00000133 00000000`00000000 00000000`00000500 00000000`00000500 : nt!KeBugCheckEx
ffffa101`3c9fab50 fffff805`c5d67b61     : fffff805`c69c33a0 00000000`00000002 00000000`00000000 00000000`00592ec2 : nt!KeAccumulateTicks+0x589
ffffa101`3c9fabc0 fffff805`c5d67725     : 00000000`00352831 00000000`00000000 000000d4`a0c7258b 00000000`0000000d : nt!KiUpdateRunTime+0xc9
ffffa101`3c9fac40 fffff805`c5c6e8fe     : 00000000`00000000 00000000`00000000 ffffa101`3c9e77c0 fffff805`c6920560 : nt!KiUpdateTime+0x2b5
ffffa101`3c9fadd0 fffff805`c5c702ad     : ffff8081`6e731ea0 00000000`00000000 ffff8081`6e731f50 fffff805`c698de28 : nt!KeClockInterruptNotify+0x66e
ffffa101`3c9faf50 fffff805`c607bc4e     : 00000000`02cd0b02 ffff8081`6e731ea0 ffffe90f`c2c6f3d0 000000d4`a0ca342f : nt!KiCallInterruptServiceRoutine+0x2ed
ffffa101`3c9fafb0 fffff805`c607c45c     : ffffa101`3c9de180 ffffe90f`c2c6f450 00000000`00000000 00000000`00000000 : nt!KiInterruptSubDispatchNoLockNoEtw+0x4e
ffffe90f`c2c6f3d0 fffff805`c5c7deb5     : ffff8081`860d4634 fffff805`65225172 ffffe90f`00000000 fffff805`00000000 : nt!KiInterruptDispatchNoLockNoEtw+0x3c
ffffe90f`c2c6f560 fffff805`c5c56656     : 00000000`0001003d 00000000`00000002 ffff8081`915b9650 ffff8081`915b9010 : nt!ExpAcquireSpinLockExclusive+0x45
ffffe90f`c2c6f590 fffff805`6522edaa     : ffff8081`915b9650 fffff805`65230c70 00000000`00000001 ffffe90f`c2c6f5f0 : nt!ExAcquireSpinLockExclusive+0x36
ffffe90f`c2c6f5c0 ffff8081`915b9650     : fffff805`65230c70 00000000`00000001 ffffe90f`c2c6f5f0 00000000`00000005 : mullvad_wireguard+0x1edaa
ffffe90f`c2c6f5c8 fffff805`65230c70     : 00000000`00000001 ffffe90f`c2c6f5f0 00000000`00000005 fffff805`00000003 : 0xffff8081`915b9650
ffffe90f`c2c6f5d0 00000000`00000001     : ffffe90f`c2c6f5f0 00000000`00000005 fffff805`00000003 2e393032`2e353831 : mullvad_wireguard+0x20c70
ffffe90f`c2c6f5d8 ffffe90f`c2c6f5f0     : 00000000`00000005 fffff805`00000003 2e393032`2e353831 323a3537`2e363931 : 0x1
ffffe90f`c2c6f5e0 00000000`00000005     : fffff805`00000003 2e393032`2e353831 323a3537`2e363931 ffff8000`39393232 : 0xffffe90f`c2c6f5f0
ffffe90f`c2c6f5e8 fffff805`00000003     : 2e393032`2e353831 323a3537`2e363931 ffff8000`39393232 00000000`00000000 : 0x5
ffffe90f`c2c6f5f0 2e393032`2e353831     : 323a3537`2e363931 ffff8000`39393232 00000000`00000000 00000000`00000000 : 0xfffff805`00000003
ffffe90f`c2c6f5f8 323a3537`2e363931     : ffff8000`39393232 00000000`00000000 00000000`00000000 00000000`00000000 : 0x2e393032`2e353831
ffffe90f`c2c6f600 ffff8000`39393232     : 00000000`00000000 00000000`00000000 00000000`00000000 ffff8081`7c39b158 : 0x323a3537`2e363931
ffffe90f`c2c6f608 00000000`00000000     : 00000000`00000000 00000000`00000000 ffff8081`7c39b158 00000000`00000002 : 0xffff8000`39393232


SYMBOL_NAME:  mullvad_wireguard+1edaa

MODULE_NAME: mullvad_wireguard

IMAGE_NAME:  mullvad-wireguard.sys

STACK_COMMAND:  .process /r /p 0xfffff805c69cdf80; .thread 0xffff80816e6ca280 ; kb

BUCKET_ID_FUNC_OFFSET:  1edaa

FAILURE_BUCKET_ID:  0x133_DPC_mullvad_wireguard!unknown_function

OSPLATFORM_TYPE:  x64

OSNAME:  Windows 10

FAILURE_ID_HASH:  {018bf450-1319-9872-5c54-fdc15d5feec4}
 
Followup: MachineOwner
```

**Comment by dlon** [comment] 2024-12-20 16:18
Hey, thanks for reporting this! Just noting that we'll be working on this soon.

I'm closing this as a duplicate of some similar issues:

https://github.com/mullvad/mullvadvpn-app/issues/7266
https://github.com/mullvad/mullvadvpn-app/issues/5857

**Closed by dlon** 2024-12-20 16:18 UTC
Labels: bug, Windows
