### ISSUE TITLE
[Feature Request]: Only connect to VPN on WiFi

### ISSUE THREAD

**Issue by neverabsolute** [mullvad/mullvadvpn-app#4892] opened 2023-07-12 00:28 UTC
Hello! I've been using Mullvad for a long while now and one of the biggest issues I have with the iOS app is that on mobile data, connectivity is really unstable. I assume this is because when you're on the move you constantly have to renegotiate the connection from one cell tower to another, and that also means you have to re-establish the VPN connection as well.

What I'd propose is the ability to make it so possible for the user to enable a setting such that Mullvad does not attempt to connect, or even disconnects from an active connection, when it detects the phone is on mobile data. It might also make sense to include the inverse setting, making it so that you can have Mullvad *only* attempt to connect while on mobile data, and disconnect when it detects that you have connected to WiFi.

I'd assume there would have to be some UX changes and non-intrusive defaults set, but I do think this would be a nice QoL feature. Let me know if I can add any clarification.

**Comment by faern** [comment] 2023-07-12 11:03
This is a duplicate of #4086. This also sounds like a workaround IMO. The real solution is probably to make the connection more stable on cellular. I think the app should handle hopping between towers. I don't think you get a new IP or anything when that happens. On the other hand, if the app does not detect a working tunnel for a while, it will try to reconnect. And that's what happens on unstable connections. We should probably make those reconnect timers more relaxed on mobile.

For this feature in general (not connect on certain types of network) we have other issues. #1884 So I'm going to close this as a duplicate of the two linked issues. Feel free to open an issue specifically on the unstable tunnels if you want to.

**Closed by faern** 2023-07-12 11:03 UTC
