### ISSUE TITLE
Dependency resolution failure during installation on OpenSUSE (no `dbus-libs`).

### ISSUE THREAD

**Issue by rokejulianlockhart** [mullvad/mullvadvpn-app#4919] opened 2023-07-22 20:37 UTC
## Issue report

Operating system:

```sh
uname -a
```
```log
Linux RQN6C6 6.4.3-1-default #1 SMP PREEMPT_DYNAMIC Tue Jul 11 06:23:11 UTC 2023 (5ab030f) x86_64 x86_64 x86_64 GNU/Linux
```

App version:

```pwsh
file $HOME/Downloads/MullvadVPN-2023.5-beta1_x86_64.rpm
```
```log
/home/rokejulianlockhart/Downloads/MullvadVPN-2023.5-beta1_x86_64.rpm: RPM v3.0 bin i386/x86_64
```

### Issue description

```sh
sudo zypper install https://mullvad.net/media/app/MullvadVPN-2023.5-beta1_x86_64.rpm
```
```log
Loading repository data...
Reading installed packages...
Resolving package dependencies...

Problem: nothing provides 'dbus-libs' needed by the to be installed mullvad-vpn-2023.5_beta1-1.x86_64
 Solution 1: do not install mullvad-vpn-2023.5_beta1-1.x86_64
 Solution 2: break mullvad-vpn-2023.5_beta1-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 1
Resolving dependencies...
Resolving package dependencies...
Nothing to do.
```

```pwsh
plasma-discover --local-filename $HOME/Downloads/MullvadVPN-2023.5-beta1_x86_64.rpm
```
> ![Dependency resolution failed](https://github.com/mullvad/mullvadvpn-app/assets/42837531/c5a2ddcc-676b-43aa-ad6c-c4702e1dab8d)

**Comment by faern** [comment] 2023-07-31 08:14
This is basically a duplicate of #2242. Yes, OpenSUSE uses different package names from Fedora, which the RPMs were designed for. You can find more information in the linked to issue. We do not officially support OpenSUSE and do not currently test the app on OpenSUSE ourselves.

**Closed by faern** 2023-07-31 08:14 UTC
