### ISSUE TITLE
Mullvad VPN DNS fails in Parallels VM

### ISSUE THREAD

**Issue by ihateprogramming88** [mullvad/mullvadvpn-app#7126] opened 2024-11-05 06:44 UTC
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

After the latest update 2024.7, when I open parallels VM, my windows 11 VM the internet disconnects within the first minute, DNS does not get resolved. It use to work fine before this update. I am not sure if this is exactly Mullvad related but I thought I would report it. After I change VPN server it works for a little bit then disconnects again. Mac os sequoia 

### Expected Behavior

Boot vm start browsing and then it will. Disconnect 

### Steps to Reproduce

1. ... Open parallels VM make sure set to shared network in network settings 
2. ... Start browsing
3. It will disconnect

**Comment by mdl054** [comment] 2024-11-06 16:27
Same behavior here, reverting to 2024.5 allows it to function

**Comment by humblecoder** [comment] 2024-11-24 01:35
Well, here's an interesting (¿edge?) case.

`MacOS Host (Mullvad 2024.7) -> Parallels (Debian 12) -> NO INTERNET`

`MacOS Host (Mullvad 2024.7) -> Parallels (Debian 12) (guest also running Mullvad) -> SUCCESSFUL INTERNET`

Both are set to "Shared Network" for the guests.

😳

**Comment by Tarry91** [comment] 2024-12-03 15:03
Can confirm, same issue in VirtualBox

**Comment by Mike-571** [comment] 2024-12-08 10:15
So far so good with Sequoia 15.1, Parallels 20.1.2 and Mullvad 2024-9 beta1

**Comment by Tarry91** [comment] 2024-12-08 14:07
Can confirm, resolved with Mullvad 2024-9 beta1 :)

**Comment by Serock3** [comment] 2024-12-09 09:27
Great to hear! 🎉  This was likely caused by a DNS issue that we have resolved in the latest beta version. Note that the fix does NOT apply to macOS versions from 14.6 to (and including) 15.0. If you have a version in this range, you will need to update to 15.1.

Since the problem seems to be resolved, I will close this issue. Please re-open it if you find that the bug remains for macOS versions 🙂

**Closed by Serock3** 2024-12-09 09:27 UTC
Labels: bug, macOS, Daemon
