### ISSUE TITLE
Mullvad 2020.06 System Service Fails to Start on Linux (Ubuntu/Mint)

### ISSUE THREAD

**Issue by davidjmeier** [mullvad/mullvadvpn-app#2198] opened 2020-10-21 00:23 UTC
## Issue report

Operating system: Linux Mint 19.3 Tricia x86_64 / Ubuntu 18.04 x86_64 (Kernel: 5.4.0-52-generic)

App version: Mullvad 2020.06

### Issue description

Mullvad system service will not start.  However using 2020.05 the system works as expected.  The initial attempt to install was over 2020.05 as an upgrade.  When that didn't work I ran an `sudo apt purge mullvad-vpn/now` and attempted the installation clean with the same results.

If there's a way I can enable debug or collect additional logs please let me know.  Thank you!

**Comment by faern** [comment] 2020-10-21 08:25
Please send a problem report from within the app. Settings -> Report a problem. That will go directly to our support and they will handle any issues in using the app.

**Comment by davidjmeier** [comment] 2020-11-10 20:01
I just sent in a report.

With the current DNS bug now impacting 2020.05 and 2020.06 I decided to test 2020.07-beta1 and also get the same error from 2020.06 wherein the UI just hangs.  Right now there are no usable versions that work on Linux Mint.

Screenshot:
![mullvad-mint](https://user-images.githubusercontent.com/828435/98727202-33079e00-235d-11eb-91f4-c29311b5281c.png)

**Comment by zagatta** [comment] 2020-11-11 09:42
I have the same problem on elementary os hera (Ubuntu 18.04) and Pop os 20.04 (Ubuntu 20.04).

**Comment by pinkisemils** [comment] 2020-11-11 10:01
Could you elaborate on how you configure your networking? Are you letting NetworkManager do it's thing, rely on a plain DHCP client or do you set your IPs and routes up manually or via a script?

The issue might be because your routing table might only contain a single default route like `default via 192.168.122.1 dev enp1s0`. The daemon will try and add the same route to a different routing table and fail because the above route depends on a route to your local network existing. The route would look like `192.168.122.0/24 dev enp1s0`.

**Comment by zagatta** [comment] 2020-11-11 10:34
I do not actively do any network configuration.
I have a pretty extensive /etc/hosts list, but I guess that not a problem.
Apart from that I was only using the mullvad linux client and no other changes to any network environment that I am aware of.

**Comment by pinkisemils** [comment] 2020-11-11 12:07
Interesting. We have only been able to reproduce what seemingly is this issue when the routes are setup as described above. Would you mind sending in a problem report too?

**Comment by faern** [comment] 2020-11-11 15:04
We have applied a fix that we hope will help for the issues you are having @zagatta and @davidjmeier. If you feel comfortable doing so, could you try out this development version and tell us if it behaves better or not? https://build.mullvad.net/2020.7-beta1-dev-43b452/

**Comment by pinkisemils** [comment] 2020-11-12 21:18
We are however still struggling to reproduce the issue on a stock install of the aforementioned distributions. To ensure that we are even fixing the issue that you are experiencing, it'd be interesting to see what your routing table looks like, so the output `ip route` and `ip rotue -6` would be much appreciated, as long as you are OK with sharing it. I can only presume that you are using the default GUI tools to setup networking, which would imply that you are using NetworkManager, but I've struggled to reproduce this issue via just NetworkManager.

**Comment by davidjmeier** [comment] 2020-11-13 14:06
Just to clarify, on both systems NetworkManager is in use along with DHCP.  The route table looks as follows:

```
➜  /tmp ip -6 route
::1 dev lo proto kernel metric 256 pref medium
fd56:aaa:bbbb:cccc:eeee:ffff::/88 dev ztraaabbbc proto kernel metric 256 pref medium
fe80::/64 dev eno1 proto kernel metric 100 pref medium
fe80::/64 dev ztraaabbbc proto kernel metric 256 pref medium
fe80::/64 dev docker0 proto kernel metric 256 linkdown pref medium
➜  /tmp ip -4 route
default via 10.X.X.5 dev eno1 proto dhcp metric 100 
10.X.Y.0/24 dev ztraaabbbc proto kernel scope link src 10.X.Y.140 
10.X.X.0/24 dev eno1 proto kernel scope link src 10.X.X.222 metric 100 
10.X.Z.0/24 via 10.X.Y.141 dev ztr2qu6anx 
169.254.0.0/16 dev eno1 scope link metric 1000 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
```
On these systems I have installed Docker (as is noted) as well as ZeroTier (as indicated by the ztr routes).

I will try and test the build you've posted and report back.  Thank you!

**Comment by zagatta** [comment] 2020-11-14 18:03
@faern 

yes it works now.

**Comment by dazWiLLiE** [comment] 2020-11-15 18:02
Not working here, tried the linked beta (`Arch Linux`), still get the following (`/var/log/mullvad-vpn/daemon.log`):

```
[2020-11-15 18:55:42.312][mullvad_daemon::version][INFO] Starting mullvad-daemon - 2020.7-beta1-dev-43b452 2020-11-11
[2020-11-15 18:55:42.312][mullvad_daemon][INFO] Logging to /var/log/mullvad-vpn
[2020-11-15 18:55:42.315][mullvad_daemon::rpc_uniqueness_check][DEBUG] Failed to locate/connect to another daemon instance, assuming there isn't one
[2020-11-15 18:55:42.315][mullvad_daemon][INFO] Management interface listening on /var/run/mullvad-vpn
[2020-11-15 18:55:42.315][mullvad_daemon::relays][DEBUG] Reading relays from /var/cache/mullvad-vpn/relays.json
[2020-11-15 18:55:42.315][mullvad_daemon::relays][DEBUG] Reading relays from /opt/Mullvad VPN/resources/relays.json
[2020-11-15 18:55:42.369][mullvad_daemon::relays][INFO] Initialized with 776 cached relays from 2020-11-15 12:52:25.000
[2020-11-15 18:55:42.369][mullvad_daemon::settings][INFO] Loading settings from /etc/mullvad-vpn/settings.json
[2020-11-15 18:55:42.369][mullvad_daemon::version_check][DEBUG] Loading version check cache from /var/cache/mullvad-vpn/version-info.json
[2020-11-15 18:55:42.369][mullvad_daemon::version_check][WARN] Error: Unable to load cached version info
Caused by: Clearing version check cache due to a version mismatch
[2020-11-15 18:55:42.370][mullvad_daemon::account_history][INFO] Opening account history file in /etc/mullvad-vpn/account-history.json
[2020-11-15 18:55:42.370][mullvad_daemon::version_check][WARN] Not checking for updates because this is a development build
[2020-11-15 18:55:42.374][mullvad_daemon][DEBUG] No cached target state to load
[2020-11-15 18:55:42.374][mullvad_daemon][INFO] Automatically connecting since auto-connect is turned on
[2020-11-15 18:55:42.376][talpid_core::routing::imp::imp][ERROR] Error: Failed to flush exclusions routes
Caused by: Route without a valid node
[2020-11-15 18:55:42.376][mullvad_daemon][ERROR] Error: Unable to initialize daemon
Caused by: Tunnel state machine error
Caused by: Failed to initialize the route manager
Caused by: Internal route manager error
Caused by: Route without a valid node
[2020-11-15 18:55:42.376][mullvad_daemon][DEBUG] Process exiting with code 1
[2020-11-15 18:55:42.376][mullvad_daemon::relays][ERROR] Relay list updater shutting down
```

**Comment by stefan-mullvad** [comment] 2020-11-16 12:24
@dazWiLLiE What kernel version are you running? Try to update it to at least 4.19.

**Comment by dazWiLLiE** [comment] 2020-11-16 22:36
Kernel version: 5.9.8-1-MANJARO

**Comment by blissd** [comment] 2020-11-18 06:08
I have the same problem. Instead of NetworkManager I use systemd-networkd and systemd-resolved for managing my network. This setup has worked for a long time.

For me, the Mullvad linux app broke after I replaced my router which has caused default route IP to change from **192.168.1.1** to **192.168.198.1**. The Mullvad daemon has failed to start since that change.

I've tried the 2020.7 beta, but it does not fix the problem.

**Comment by henrythelonewolf** [comment] 2020-11-19 05:12
I'm having the same problem as @dazWiLLiE and output of my daemon.log is the exact same. I'm currently running on kernel 5.9.8-2-MANJARO.

**Comment by dazWiLLiE** [comment] 2020-11-19 14:29
@henrythelonewolf Great! I'll install "mullvad-vpn" from AUR, reboot and see how it goes.

**Comment by dazWiLLiE** [comment] 2020-11-28 15:57
Interesting, now Mullvad has problems again:

```
[2020-11-28 16:52:46.490][mullvad_daemon][ERROR] Error: Unable to start management interface server
Caused by: Unable to start management interface server
Caused by: Failed to start IPC pipe/socket
Caused by: Address already in use (os error 98)
[2020-11-28 16:52:46.490][mullvad_daemon][DEBUG] Process exiting with code 1
```

Which address is in use?

**Comment by dazWiLLiE** [comment] 2020-12-04 15:41
Rebooted again, and now have the same error..

**Comment by davidjmeier** [comment] 2020-12-20 17:14
Thanks again for the beta fix, curious if this has been pushed to a GA release or is it still an outstanding issue for some?

**Comment by HoboDev** [comment] 2021-02-13 10:13
Same issue here [Address already in use (os error 98)]. Happened after a system crash. So far unfixable. Everything was working fine before.

**Comment by MarkusPettersson98** [comment] 2024-09-19 08:04
Hello everyone!

Since this issue last saw an update almost 3 years ago, I just want to check in and see if anyone still experiences this issue. If so, please provide updated logs and which distro, kernel and systemd version you are usigin so that we can investigate it properly.

If we don't see any replies we'll close this issue. Feel free to open new ones as needed. Thanks :yellow_heart:

**Closed** 2024-09-20 10:48 UTC
