### ISSUE TITLE
404 Error on Stable Fedora Repo

### ISSUE THREAD

**Issue by gruberaaron** [mullvad/mullvadvpn-app#6922] opened 2024-10-04 03:19 UTC
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Followed instructions on https://mullvad.net/en/help/install-mullvad-app-linux#fedora

```
Errors during downloading metadata for repository 'mullvad-stable':
  - Status code: 404 for https://repository.mullvad.net/rpm/stable/x86_64/repodata/c6cf93b0c09f7f6f5ea14ff35e7ca61ab80db8aa5fac9546e57406703de30649-primary.xml.gz (IP: 45.149.104.1)
Error: Failed to download metadata for repo 'mullvad-stable': Yum repo downloading error: Downloading error(s): repodata/c6cf93b0c09f7f6f5ea14ff35e7ca61ab80db8aa5fac9546e57406703de30649-primary.xml.gz - Cannot download, all mirrors were already tried without success
Ignoring repositories: mullvad-stable
Dependencies resolved.
Nothing to do.
Complete!
```

Beta repo seems to work correctly.

Here is my mullvad.repo config:

```
[mullvad-stable]
name=Mullvad VPN
baseurl=https://repository.mullvad.net/rpm/stable/$basearch
type=rpm
enabled=1
gpgcheck=1
gpgkey=https://repository.mullvad.net/rpm/mullvad-keyring.asc

[mullvad-beta]
name=Mullvad VPN (beta)
baseurl=https://repository.mullvad.net/rpm/beta/$basearch
type=rpm
enabled=0
gpgcheck=1
gpgkey=https://repository.mullvad.net/rpm/mullvad-keyring.asc

```

### Expected Behavior

Successful download of package(s).

### Steps to Reproduce

1. sudo dnf config-manager --add-repo https://repository.mullvad.net/rpm/stable/mullvad.repo
2. sudo dnf check-update

### Operating system version

Fedora Workstation 40 (KDE)

**Comment by faern** [comment] 2024-10-04 04:07
Not able to reproduce. I checked our repositories and they seem correct. I followed your steps to reproduce in a Fedora 40 container and it works. This looks like a (temporary?) network issue on your end to me.

> Here is my mullvad.repo config:

You are not supposed to have *both* the stable and the beta repo. You are supposed to add one or the other. Given your other info I suspect you want to use the stable repos. Please remove the beta repos and see if that helps.

**Comment by faern** [comment] 2024-10-04 07:28
More people are reporting this, but for the deb repositories. So we might have a hosting issue. We are looking into it. Thanks for reporting.

**Comment by faern** [comment] 2024-10-04 08:27
@gruberaaron Are you still seeing this? Can you reliably reproduce it? It looks from what you write that you can at least install the beta app. Have you tried installing it and running it and tried updating the stable repository via a VPN tunnel? I suspect this is a hosting issue, so trying to reach the repository servers from somewhere else might help.

**Comment by faern** [comment] 2024-10-04 09:49
This was a CDN caching issue on our end. This should have been resolved now. I'm closing this as completed. Please report if you still encounter this problem, now or later.

**Closed by faern** 2024-10-04 09:49 UTC
Labels: bug, Linux

**Comment by AshtakaOOf** [comment] 2024-11-03 21:20
I also have this issue on dnf5
```
sudo dnf5 config-manager addrepo --set=baseurl=https://repository.mullvad.net/rpm/stable/mullvad.repo
```
Then when trying to install `mullvad-vpn` I get
```
Status code: 404 for https://repository.mullvad.net/rpm/stable/mullvad.repo/repodata/repomd.xml (IP: 45.149.104.1)
```
`https://repository.mullvad.net/rpm/stable/mullvad.repo` does exist but `/repodata/repomd.xml` does not

**Comment by faern** [comment] 2024-11-04 12:20
@AshtakaOOf I suspect you have an error in your command there. Please look at our installation guide. It has updated docs for Fedora 41 now: https://mullvad.net/sv/help/install-mullvad-app-linux#fedora

**Comment by AshtakaOOf** [comment] 2024-11-04 21:39
Thanks it works :grinning:
