### ISSUE TITLE
[iOS] Support for iOS 11 and 12

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#1855] opened 2020-06-18 00:30 UTC
Hello, please add support for iOS 11 and 12

There are still users who owns as far as iPhone 6 :(

For your consideration. Thank you.

**Comment by faern** [comment] 2020-06-18 11:55
Duplicate of #1748. Sorry but this has already been requested and an explanation as to why is in that issue.

**Closed by faern** 2020-06-18 11:55 UTC
Labels: iOS, not-in-scope

**Comment by faern** [comment] 2020-09-11 09:19
We went ahead and fixed iOS 12 support anyway. And it just went live! The latest version on App Store now supports iOS 12 and newer. https://mullvad.net/en/blog/2020/9/11/mullvad-vpn-also-available-ios-12/

**Comment by 8227846265** [comment] 2020-09-11 09:54
Wow, nice to hear this!
