### ISSUE TITLE
Add cli option to start mullvad-vpn client minimized [linux]

### ISSUE THREAD

**Issue by rhoeden** [mullvad/mullvadvpn-app#398] opened 2018-09-01 15:39 UTC
Let power users enjoy the indicator icon in systray without having to close the mullvad-vpn window every time system starts up.

**Comment by faern** [comment] 2018-09-01 22:04
The app should start minimized, except for the first time it's started and you have to enter an account number. This seems to be a bug. So we should rather fix that than adding a flag to toggle it. We'll look into it.

**Comment by rhoeden** [comment] 2018-09-12 12:10
Fair enough. I've switched to openvpn for a cleaner solution for the time being.

**Comment by baimafeima** [comment] 2018-09-14 08:06
What desktop environments would the indicator icon in the systray work? Do you have any particular setup for testing? It would be great to have support for KDE Plasma, Budgie and Xfce.

**Comment by faern** [comment] 2018-09-14 09:18
@baimafeima I'm going to turn the question around. Where does it currently not work? We know it works in at least Xfce and Ubuntu's own patched Gnome 3. Many modern window managers have deprecated and removed support for tray icons now. For example vanilla Gnome 3 have no tray icons.

But that is off topic for this issue. If you see a window manager that are supposed to have tray icon support but our app does not have one. Then please file a separate issue on that our app does not work as intended under that window manager/desktop environment.

**Comment by baimafeima** [comment] 2018-09-14 10:13
> Then please file a separate issue on that our app does not work as intended under that window manager/desktop environment.

Thanks, will do some testing.

**Comment by faern** [comment] 2019-01-25 12:35
The new beta release, [2019.1-beta1](https://github.com/mullvad/mullvadvpn-app/releases/tag/2019.1-beta1), supports configuring the GUI app to start minimized on Linux. Just open the app, go to "Preferences" and enable "Start minimized". This will soon be in a stable release. Closing this issue as it's now fixed.

**Closed by faern** 2019-01-25 12:35 UTC

**Comment by dreirund** [comment] 2024-11-25 22:27
> *The new beta release, [2019.1-beta1](https://github.com/mullvad/mullvadvpn-app/releases/tag/2019.1-beta1), supports configuring the GUI app to start minimized on Linux.*

I still wish for a command line option for that.

Usecase:

* When launched manually, present the user with a window.
* Another option to launch it from a script to just place the tray icon.

And have both uses be possible without the user having to change settings in the GUI.
