### ISSUE TITLE
Make Split Tunneling page on Linux more like the app on Android (be able to always split a specific app)

### ISSUE THREAD

**Issue by calhix** [mullvad/mullvadvpn-app#5293] opened 2023-10-15 19:23 UTC
## Issue report

Operating system: Fedora 39 SIlverblue

App version: 2023.5

### Issue description

I really like how the split tunneling page on the android app works, you can set apps to always be excluded. Is something like that possible on desktop? I just want to make Tor be excluded from the VPN at all times. Works great on my phone.

**Comment by faern** [comment] 2023-10-17 07:57
Closing this as a duplicate of #3044, #5065 and #3397. Sadly, this is not in the pipeline and we have no good known solution right now.

**Closed by faern** 2023-10-17 07:57 UTC
