### ISSUE TITLE
The "mullvad-exclude" split-tunnel launcher does not work on IPv6 connections, only IPv4

### ISSUE THREAD

**Issue by ovesoe** [mullvad/mullvadvpn-app#2370] opened 2020-12-23 08:36 UTC
## Issue report

Operating system: Linux (Debian Testing)

App version: 2020.7

### Issue description

Launching a program (Firefox) with "mullvad-exclude" I note that only its IPv4 traffic bypasses the tunnel. The IPv6 traffic is still routed through the VPN. This might also be a privacy issue because peers can now infer that my real IPv4 address belongs to a Mullvad user and which endpoint it is currently behind.

**Comment by pinkisemils** [comment] 2020-12-23 11:21
This is a duplicate of #2307.

**Closed by pinkisemils** 2020-12-23 11:21 UTC
