### ISSUE TITLE
[Feature request] Utilize the kernel module on Android

### ISSUE THREAD

**Issue by Atrate** [mullvad/mullvadvpn-app#1534] opened 2020-02-23 12:07 UTC
Since Android devices use a very old kernel (usually older than 4.0), getting the WireGuard kernel module from the upcoming mainline is... hardly possible.

Some users with root access choose to install the kernel module by patching the existing kernel, so IMHO it woupd be nice if the Mullvad app for Android utilized the module if it were installed.

**Comment by chandradeepdey** [comment] 2020-02-23 16:08
Duplicate of #1134

**Closed** 2020-02-23 16:15 UTC
