### ISSUE TITLE
Compatibility with firewall and other issue ever since App uses wintun instead of wintap

### ISSUE THREAD

**Issue by Gitt238746238** [mullvad/mullvadvpn-app#2728] opened 2021-05-08 07:31 UTC
Operating system: Windows 7
App version: 2021.3

Hello.

Ever since the change in mullvad client from openvpn to wireguard (wintun.sys), the firewall used (comodo firewall) does not see any connections. When openvpn is used (openvpn in app now also uses the wintun.sys wireguard).
Internet works fine but the firewall lets everything through, any program, because the comodo firewall (COMODO Internet Security Firewall Driver) does not attach itself to the Mullvad Tunnel (that uses wintun.sys).
Roughly a year ago I remember everything still worked fine. Back then it still used the standard wintap adapter and not wintun (only wireguard used that). I am not sure why comodo firewall does not recognize the wintun Adapter(s) Tunnel (that are newly created when establishing a connection in the app).

Does it have anything to do with the fact that upon creating a new connection, a new adapter tunnel is created?
For example Mullvad 19. Next one would be Mullvad 20, then Mullvad 21 and so on. Not sure if it's supposed to be that way.
![mulv(1)](https://user-images.githubusercontent.com/83859199/117530881-23e17000-afcf-11eb-84c6-60aef770fdd4.png)

The old standard tap adapter where everything worked fine was always (permanently) listed under Network Connections Panel (windows 7) and static,  if I remember correctly even after disconnecting and being offline and not connected. I'm sure about the fact that it did not have it's name of the adapter changed with an increased number.
I am not sure what the reason is why the firewall does not see the wintun adapter tunnel. Either A because the adapter is not static and permanently always active anymore (like it used to be when the old tap was used). Or B because comodo firewall generally does not support the wintun. Or C because the issue with the increasing number.

**Comment by faern** [comment] 2021-05-11 08:42
It is correct that when we got rid of the ancient non-maintained OpenVPN TAP adapter and adopted Wintun we started creating a new adapter on each connection. This is how Wintun is designed and intended to be used.

It's unfortunate that Comodo can't see these new adapters. I suggest you contact Comodo and ask them to look into this. Wintun is gaining in popularity and is not going away. Not at Mullvad and probably not with other VPNs either.

**Comment by faern** [comment] 2021-06-11 08:34
I'm closing this as the issue is mainly between Wintun and Comodo. The Wintun developers are not overly excited about improving compatibility with the long EOLd Windows 7 and we are going to drop support for it within a year as well. I suggest you either talk to your AV provider or upgrade your OS.

**Closed by faern** 2021-06-11 08:34 UTC
