### ISSUE TITLE
Killswitch

### ISSUE THREAD

**Issue by DutchPete** [mullvad/mullvadvpn-app#5140] opened 2023-09-09 12:37 UTC
## Issue report

Operating system: macOS 13 Ventura

App version: 2023.4

### Issue description

When the internet connection is cut, the killswitch blocks access to internet. While that is great from a privacy point of view, I am not sure I like it. Is there a way to disable the killswitch?

**Comment by MrChocolatine** [comment] 2023-09-09 14:52
- https://mullvad.net/en/help/tag/privacy/#67
- https://github.com/mullvad/mullvadvpn-app/blob/main/docs/security.md#kill-switch

**Comment by DutchPete** [comment] 2023-09-09 16:41
@MrChocolatine thanks for your reply, I was afraid that would be the answer. 

From the 1<sup>st</sup> link:
> The app has a built in kill switch that is enabled by default and cannot be disabled. This is to prevent your traffic from leaking outside of the VPN tunnel i**f your network suddenly stops working** or **if the tunnel fails for any reason**. Mullvad automatically protects your data until your connection is reestablished.

Details for that 2<sup>nd</sup> point, from the 2<sup>nd</sup> link:
> **If the tunnel were to come down and your operating system tries to route packets** out via the normal network rather than through the VPN, **these rules would block them from leaving**. So rather than failing open, meaning if the tunnel fails your traffic leaves in other ways, we fail closed, meaning if the packets don't leave encrypted in the way the app intends, **then they can't leave at all**.

That is precisely what worries me: **I lose control over my computer**.

I find that rather condescending: we, Mullvad, decide what is good for you. Why not let the user pick their own choice? As far as I am concerned, Mullvad's only responsibility regarding this issue is to explain to the user what the kill switch does, but then provide a toggle for the user to choose the appropriate setting, perhaps with the default setting as ‘enabled’.

**Comment by MrChocolatine** [comment] 2023-09-09 18:59
> explain to the user what the kill switch does, but then provide a toggle for the user to choose the appropriate setting, perhaps with the default setting as ‘enabled’.

This is exactly what is implemented, with the toggle disabled.

**Comment by MrChocolatine** [comment] 2023-09-09 19:02
See the threads
- https://github.com/mullvad/mullvadvpn-app/issues/3430
- https://github.com/mullvad/mullvadvpn-app/issues/4141

**Comment by DutchPete** [comment] 2023-09-10 06:37
@MrChocolatine 
> This is exactly what is implemented, but with the toggle disabled.

Yes, I know, my comment was just a confirmation that that is what I'd expect, but I want the toggle enabled. I posted a request for that in issue #3430.

Thanks a lot for jumping in and providing the 2 links. Obviously, the kill switch and toggle are an issue for others too, albeit from a different angle.

**Comment by faern** [comment] 2023-09-12 11:51
I'm going to close this issue as it's a duplicate of #3430. Any discussion about implementing support for disabling the kill-switch can be had there.

**Closed by faern** 2023-09-12 11:51 UTC
