### ISSUE TITLE
[Feature Request] Rotating connections/IPs

### ISSUE THREAD

**Issue by seanfrasure** [mullvad/mullvadvpn-app#3236] opened 2022-01-05 14:15 UTC
The vast majority of trackers rely on IP addresses as a facet of fingerprinting. Even if the VPN is "detectable", it would be very helpful to be able to rotate the connection to change in intervals. I suggest the configuration be able to select a certain region/location to stay within and that the connection can be rotated every X minutes.

I know that there are other ways to accomplish this on desktop via CLI (similar to https://archern9.github.io/posts/randomize-mullvad-interface-with-cron/) but I feel it would be a useful feature to have built-in across all platforms.

**Comment by faern** [comment] 2022-01-05 16:57
Thanks for the suggestions. But we already have an issue for this feature open. So I'm going to close this as a duplicate of #2623

**Closed by faern** 2022-01-05 16:57 UTC
