### ISSUE TITLE
Switching user on Ubuntu doesn't disconnect from VPN client

### ISSUE THREAD

**Issue by markcellus** [mullvad/mullvadvpn-app#3286] opened 2022-01-22 14:08 UTC
## Issue report

Operating system: Ubuntu 21.10

App version: 2021.6

### Issue description

While having MullvadVPN client on, logging out and logging in to another user does not disconnect the VPN client.

**Repro steps:**

1. Log in with first user (User 1)
2. Turn on Mullvad VPN client and make sure its connected
3. Log out of User 1
4. Log into second user (User 2)
5. Open Mullvad VPN client

**Expected Behavior**
Mullvad VPN client is disconnected.

**Actual Behavior**
Mullvad VPN client is still connected.

Note: "Launch app on start-up" and "Auto-connect" are both disabled the entire time.

**Comment by faern** [comment] 2022-01-24 11:10
I suppose Ubuntu does not kill all User 1 processes on "logout" then? I guess it's more of a user switch rather than user logout?

If that is true, then it's not very much we can do I'm afraid. If our app is running we should not randomly disconnect. And I don't think we should add code to detect a Ubuntu specific "logout" and disconnect then. Both because that could be technically ugly AND because we know for sure there are users who expect the opposite behavior. We have users running distributions where logging out DOES exit our app and thus disconnect the tunnel. They expect the VPN to NOT disconnect just because they switch users.

**Comment by markcellus** [comment] 2022-01-24 23:48
That is not correct. As indicated in the steps I listed, I am actually logging out of user 1.

**Comment by raksooo** [comment] 2022-01-25 14:20
@markcellus It looks like our app is killed without receiving the quit-events that we would expect to receive. We've added this to our backlog.

**Comment by raksooo** [comment] 2022-04-11 15:35
Our app isn't always notified before it's closed down on log out and when it is, it's not often given enough time to disconnect. I've reported this to Electron: https://github.com/electron/electron/issues/33651.

**Comment by raksooo** [comment] 2022-10-19 12:36
We decided a while back that the app shouldn't disconnect on system log out for two reasons:
1. It's not possible to get it working well on all platforms
2. We need to disconnect on any `SIGTERM` signal as it could be for other reasons than logging out, e.g. killed by OS to save resources.

This has been implemented and now the only ways to disconnect in the app is to press "Disconnect" or "Quit app". I'll close this since this is now intended behaviour.

**Closed by raksooo** 2022-10-19 12:36 UTC
Labels: bug, Desktop frontend
