### ISSUE TITLE
android connection issues with restrictive networks

### ISSUE THREAD

**Issue by lordcyb3r** [mullvad/mullvadvpn-app#2942] opened 2021-09-02 20:10 UTC
Operating system: android 10 (OOS oneplus 6t)

I am unable to connect to mullvad when on my University's wifi due to the lack of bridge mode or other bypass methods. Tried openvpn with shadowsocks (followed the guide), and this fails even on my home network. I get that bridge mode on android is not in the pipeline, but there should be a way to get around these restrictive firewalls using the official app.

**Comment by faern** [comment] 2021-09-03 08:36
We are working on bringing various obfuscation protocols to WireGuard and to the mobile platforms.

However, I'm going to close this as a duplicate of #1210 and #1049

**Closed by faern** 2021-09-03 08:36 UTC
