### ISSUE TITLE
Windows 10 Wireguard Mullvad locked out on boot, when Android phone Mullvad already up

### ISSUE THREAD

**Issue by narration-sd** [mullvad/mullvadvpn-app#1734] opened 2020-05-11 16:51 UTC
## Issue report

Operating system: may be combination:  Windows 10 latest, and Android 7.1.1

App version: observed on Win10 2020.3, Android 2020.4beta3 

### Issue description

It's simple. When the phone is on and running Mullvad, very often the laptop on Win10 will not connect Mullvad on its boot, if locked to Wireguard.  OpenVPN is ok, but not desired. Mullvad is locked, shows the red-in-green icon. Happens/ed about 80% of the time, very consistently. Requires powering off the phone -- then Mullvad on PC auto-connects fine at a reboot.

Latest change: I updated to your Windows 10 Beta 2020.4 Beta 4.  Now, I think the auto-connect Wireguard-only on boot works. In fact I can see it pause with look like the fail, then in seconds try again and connect apparently reliably.

Analysis. I went through a number of possibilities with Sanny, your support person. S/he felt 'of course' this couldn't happen, as the phone has nothing to do with the pc in terms of Mullvad. This view is understandable, but I think incorrect actually.

What I found, that led me to try the beta (nearly unreachable, by the way, had to go here on Github to get it rather than circuitous web page which was supposed to offer it), was that I ran out of Mullvad Wireguard keys. Yes.  I had done nothing to use up keys; there should be only two, one for the Win10 install, one for the Android. 

What I think causes the original failure is that the phone and the laptop end up trying to use the same Mullvad Wireguard key. Whatever causes that is perhaps linked to how so many keys  were autogenerated -- I never manually generated a key, yet the full 5 keys were used up.

I cleared all the keys, after upgrading the PC to latest Beta, then created a key each for the two installs.  No extra keys have been generated since, over two days or so, the weekend. 

That I see the seeming moment of blocked still on the laptop may say that you have put in a check to switch keys if there is a collision, but that the collision is still occurring. And perhaps, you've also prevented the generation of extra keys.  I'm just guessing, from earlier issues where you seem to feel you were working on such a problem.

As you can probably understand, I've been pretty deep in protocols and many other software matters before -- long time (and European 20 years) consultant. So ask if you want to know anything more, thanks.  Mullvad is great, much enjoy its performance and reliability even at this stage. I'd like to see you get the big success, including with the Mozilla partnership. Thus reporting not only this, but some more minor matters -- and one of them not minor, but probably fixed in your network overall. Takk.

**Comment by faern** [comment] 2020-05-12 09:35
> What I think causes the original failure is that the phone and the laptop end up trying to use the same Mullvad Wireguard key

Apps on different devices never try to use the same key as another device. There is no way they could even if they wanted to. The way it works is when the app starts it checks if it has a key stored locally on the device, in the settings of the app. If it does not it generates a new private/public keypair for WireGuard and upload it to our infrastructure. The app never queries the infrastructure for existing keys or download them. And the infrastructure does not have the private keys of the other devices, so it would not be possible for your PC and Android to have the same private key (unless you actually manually transferred the private key between the devices and injected it in the other's settings in some way, but that's not likely).

Why you had so many keys is likely because earlier versions of the app was pretty bad at key management so it could easily forget it's own key and just try to upload a new one. The result is that the account was filled with keys after a while. And we still kind of have this problem if you uninstall and reinstall the app. Then it will have lost the key during the uninstall and after you start it again it will upload a new one. If you upgrade the app instead of uninstalling it this should not happen.

We just today released a new stable app for PC: `2020.4`. It does not have many key related fixes, but many other fixes. Please upgrade to that version on your PC and run `2020.4-beta4` on the Android phone.

> I cleared all the keys, after upgrading the PC to latest Beta, then created a key each for the two installs. No extra keys have been generated since, over two days or so, the weekend.

I hope you did not create keys manually? Or what did you mean? The app creates and uploads keys automatically in the background. Unless your account somehow becomes full of keys you should never have to worry about this.

**Comment by narration-sd** [comment] 2020-05-12 16:39
>I hope you did not create keys manually? Or what did you mean? The app creates and uploads keys automatically in the background. Unless your account somehow becomes full of keys you should never have to worry about this.

I wonder in turn what you mean, Linus?  Your app created an overload of keys, and refused to connect. I deleted them. The PC app regenerated and connected, as I recall (not certain), and the Android app did not. So I created a key for it, and then it worked.  

You react as if we should not manage or create keys, yet you provide the interface to do so, and in fact it invites to do so.

The Android app updated last night, apparently to 2020.4-beta4.  This morning there are _three_ keys.  What do you propose I do about them, re: what you say about fixed?

I'm just now updating the PC app to the 2020.4 release. Your release notes seem to say it's identical to the beta-4 I have running presently.

Linus, as one would say, an extremely experienced hand, I am trying to help here. It may help you to know I have a considerably Scandinavian cultural background, besides living in Europe 20 years. I am trying to help here, so no reason to be sharp -- just mentioning this early :)

**Comment by narration-sd** [comment] 2020-05-12 17:06
@faern  Linus, here's an image of your keys manager at present. 

- Given I have two devices in use with Mullvad (you have no client for my older iPad), it's not clear why there are four ports  assigned to the first key, but I'm sure you will tell me.
- The second key may look normal, for a second device, whichever of the two it is?
- The third key looks  unused - shouild I delete it? Note it appears two days after the others. Maybe that is the one I created since the phone app appeared not to know one after fresh beta update

One more possible issue is where you keep the keys on Android. It's needful to clear the caches of the phone regularly, as they eat memory to the limit. If you are keeping keys there, rather than in a stable repository/file, they will get lost this way, from manual, Google-suggested, or automatic cache clears. In case this situation may have to do with your observations or problem.

![wireguard-ports-12-may](https://user-images.githubusercontent.com/247945/81723733-26e76600-9438-11ea-9f9d-93de7a7ba206.png)

**Comment by faern** [comment] 2020-05-13 08:19
> One more possible issue is where you keep the keys on Android. It's needful to clear the caches of the phone regularly, as they eat memory to the limit.

Aaah. Here we probably have the issue. If you clear the cache the Android app will indeed lose the current keys and generate new ones, slowly filling up the account! This is an error on our end and we have very recently switched it over to storing the keys in more persistent settings storage. Most people never clear their cache and this has not come up as an issue before, so it was not brought to our attention. But apparently some users clear their cache frequently. I suspect it has to do with device age and amount of free storage. For a device close to its storage limits it makes sense to clear the cache now and then.

All you have to do then is to wait for `2020.5-beta1` to come out and the keys will be safe between cache wipes!

> You react as if we should not manage or create keys, yet you provide the interface to do so, and in fact it invites to do so.

I was not fully clear what you meant by "create keys". As the website allows you to add keys to your account as well. And in the app you should not manually have to create keys most of the time. It should be automatic. But yeah. If the issue is a cleared cache the app will likely get confused about the keys and you might have had to generate one manually in the app.

> ... it's not clear why there are four ports assigned to the first key, but I'm sure you will tell me.

The only way to get ports assigned to a key is to manually assign them in the UI you sent the screenshot of. I double checked this with some of the developers working on that. So the only explanation I have is that you have assigned them. If not, then I have no idea.

> The third key looks unused - shouild I delete it?

What makes you believe it's unused? :thinking: There is no way for the key management tool to know which keys are being used or not. All three keys are active on our WireGuard server and all servers accept traffic from them. They don't report back to the main API servers which keys are being used. So this key management tool has no idea which ones go unused. But we do have a UX problem in communicating to users which keys they have on which devices, so we know this UI can be problematic.

You seem to be well aware of the WireGuard key view in the app as well. You can open that view on your phone and PC and you will see the public key. Then you can compare with the website and you can see which two keys you actually are using.

**Comment by narration-sd** [comment] 2020-05-13 15:22
Glad we are getting somewhere on this one :)

back to front, Mullvad blocked once more on boot autoconnect this morning. I was able to get it going by changing Location (to Denver).  I pretty strongly remember this would not work some days and versions ago, so I think things are better. And I'm now considering that maybe the blocking by now has only to do with all the shifting still going on with your Los Angeles portal. 

There are 'dead' portal labels each day, and if I were on one of those actively the day before -- or if your autoconnect just tries on the list and quits if there are too many fails (almost all the bad ports listed are at the numeric beginning of the list, that  would be an explanation.

>> The third key looks unused - shouild I delete it?
>What makes you believe it's unused? 🤔 

It hasn't any ports assigned to it. I confess to being a little hazy about what port assignment means in Mullvad, especially why I might want to assign any?  As I haven't, so the four ports on the first key (ref the picture, which is still valid) came from 'somewhere'.  

Enlightenment on this subject would be useful, thanks. And again, given extra ports don't seem a good idea, since it has no ports, and it's pretty clearly the key I created manually, should I not delete it?

>> iPad2 etc. side point
Would be really nice if there was a client out there that would enable the System 9.3.x older apple kit, as none seem to do. I know, I know. But for many things they are very useful. On to your other points...(!)

**Comment by faern** [comment] 2020-05-13 15:32
The ports you see are for **port forwarding**. See this guide: https://mullvad.net/en/help/port-forwarding-and-mullvad/

That means that the ports you add to the key there will be forwarded from the **exit IP** on the server you connect to in the tunnel to you. This is so that you can host things on your computer and reach it from the internet though one of our exit IPs and via the tunnel.

For normal VPN usage you should not / need not forward any ports. That's just for opening up a port **back to your device** from the public internet.

**Comment by narration-sd** [comment] 2020-05-13 15:53
Ok, that's what I gathered, and I don't do that, port forwarding, on my router or in Mullvad.   So something along the line that generated the five-and-no-more keys, must have liked to exercise ports as well.

By what you say, _no_ ports should be assigned on any of my keys.

As things are working from the time I get exit-connections, no rush on any of this, and I'm glad to wait for the beta5 to see things get even better.

Should Ieave all the keys and ports alone  until then? Might be a good check-out of the beta advances?

**Comment by faern** [comment] 2020-05-14 07:37
If you do not need ports forwarded back to your device from the internet. Then please remove all ports from all keys. If you don't know whether or not you need ports, then you don't need ports.

**Comment by narration-sd** [comment] 2020-05-14 12:55
@faern  Linus, thanks; that makes sense. No, I am quite clear i don't need ports for anything I'm intentionally doing, and will remove them.

And then we'll have a clean slate when the next beta comes out, other than the three keys.

I've just made a clear report on the routing failure to Richard, and will paste that into the closed item for you to see in case you're not watching, as suspect you can help connect it to  where it will do the most good. Thanks.

**Comment by faern** [comment] 2020-05-18 13:22
Android version `2020.5-beta1` is now live on our website and Google Play. It stores the keys in the settings rather than the cache. Please upgrade and hopefully this issue should be resolved.

I'm closing this issue since the main problem here seems to be a wiped cache and as a result lost keys.

**Closed by faern** 2020-05-18 13:22 UTC

**Comment by narration-sd** [comment] 2020-05-18 19:28
@faern  Hello Linus, about the third try to get this written, but you should like the result.

I've tried the beta, and it looks solid. There is the problem that it keeps trying get you to reload the previous beta4, saying it's out of date, until the phone is rebooted. Screens if you want to see  them.

The beta5 itself looks to have a number of good things -- i got notified by Github earlier.

And as far as the keys and so forth, all looks very solid. After clearing the unasked ports, and the extra key, over the weekend, all remains in that state, working fine, with this upgrade, and with the things I tried on the laptop to see if possibly one of my development arrangements (vms, other vps, etc.) had been responsible for the creation of ports.  It seems not, and all is well, so we can likely put that behind us.

The problem of the UX with long placenames continues, and the addition of the 'please up(down)grade makes it worse; maybe both of those can be fixed together.

I imagine you know that Richard and i had some very good conversation late in the week, and settled the apparent overseas-Los Angeles trace.  Indeed, I'd misread a numeral, which is then what you tried to tell me about a German exit point -- just that there weren't facts in what you said, and as well, I'd been looking at the actual exit port reporting its location as Romania for a week, which was rather suggestive. 

I agree with Richard's idea on that, and I think that with Los Angeles being more stable and properly configured now, this is another point we can leave unless it shows  again. So, Mullvad looking ever better, and I enjoy to have it, thanks.

**Comment by narration-sd** [comment] 2020-05-18 20:44
p.s. meant to say that I had reached the point to clear Cache on the Android phone, so this was a good moment to test, and the keys survived fine this time - mission accomplished.

I think it's well to know this isn't an issue mainly with 'old phones', but with the misbehavior of some  apps, giving memory leaks - I seem to observe the combination of using Google News and Pocket, a very natural combination, to be particularly problematic.
