### ISSUE TITLE
missing field `version`

### ISSUE THREAD

**Issue by 2ir** [mullvad/mullvadvpn-app#6044] opened 2024-03-31 11:36 UTC
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

It's not installing

### Expected Behavior

.

### Steps to Reproduce

```
git clone https://aur.archlinux.org/mullvad-vpn.git
cd mullvad-vpn/
makepkg -si
```

### Failure Logs

```shell
[caio@archlinux ~/Downloads/mullvad-vpn]$ makepkg -si
==> Making package: mullvad-vpn 2024.1-1 (Sun 31 Mar 2024 01:26:28 PM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning mullvadvpn-app git repo...
Cloning into bare repository '/home/caio/Downloads/mullvad-vpn/mullvadvpn-app'...
remote: Enumerating objects: 339278, done.
remote: Counting objects: 100% (8622/8622), done.
remote: Compressing objects: 100% (3492/3492), done.
remote: Total 339278 (delta 5839), reused 6770 (delta 4716), pack-reused 330656
Receiving objects: 100% (339278/339278), 168.19 MiB | 7.54 MiB/s, done.
Resolving deltas: 100% (219820/219820), done.
  -> Cloning mullvadvpn-app-binaries git repo...
Cloning into bare repository '/home/caio/Downloads/mullvad-vpn/mullvadvpn-app-binaries'...
remote: Enumerating objects: 2188, done.
remote: Counting objects: 100% (740/740), done.
remote: Compressing objects: 100% (381/381), done.
remote: Total 2188 (delta 393), reused 606 (delta 343), pack-reused 1448
Receiving objects: 100% (2188/2188), 212.11 MiB | 11.81 MiB/s, done.
Resolving deltas: 100% (1284/1284), done.
  -> Found no-rpm.diff
  -> Found mullvad-vpn.sh
==> Validating source files with sha256sums...
    mullvadvpn-app ... Skipped
    mullvadvpn-app-binaries ... Skipped
    no-rpm.diff ... Passed
    mullvad-vpn.sh ... Passed
==> Verifying source file signatures with gpg...
    mullvadvpn-app-binaries git repo ... Passed
==> Extracting sources...
  -> Creating working copy of mullvadvpn-app git repo...
Cloning into 'mullvadvpn-app'...
done.
Switched to a new branch 'makepkg'
  -> Creating working copy of mullvadvpn-app-binaries git repo...
Cloning into 'mullvadvpn-app-binaries'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
Submodule 'dist-assets/binaries' (https://github.com/mullvad/mullvadvpn-app-binaries) registered for path 'dist-assets/binaries'
Submodule 'windows/libwfp' (https://github.com/mullvad/libwfp) registered for path 'windows/libwfp'
Submodule 'windows/windows-libraries' (https://github.com/mullvad/windows-libraries) registered for path 'windows/windows-libraries'
Cloning into '/home/caio/Downloads/mullvad-vpn/src/mullvadvpn-app/dist-assets/binaries'...
done.
Cloning into '/home/caio/Downloads/mullvad-vpn/src/mullvadvpn-app/windows/libwfp'...
Cloning into '/home/caio/Downloads/mullvad-vpn/src/mullvadvpn-app/windows/windows-libraries'...
Submodule path 'dist-assets/binaries': checked out 'd5772339cee9c1a0d7671968746f02499b78e245'
Submodule path 'windows/libwfp': checked out '3ea5ca1163a005dd9dbe51167e9a1176574cc348'
Submodule path 'windows/windows-libraries': checked out 'f5114c49bd9845533f193b57d55f27a5fbb47ef0'
patching file gui/tasks/distribution.js
Hunk #1 succeeded at 161 (offset -1 lines).
error: failed to load manifest for workspace member `/home/caio/Downloads/mullvad-vpn/src/mullvadvpn-app/android/translations-converter`

Caused by:
  failed to parse manifest at `/home/caio/Downloads/mullvad-vpn/src/mullvadvpn-app/android/translations-converter/Cargo.toml`

Caused by:
  TOML parse error at line 1, column 1
    |
  1 | [package]
    | ^^^^^^^^^
  missing field `version`
==> ERROR: A failure occurred in prepare().
    Aborting...
```

### Operating system version

Linux archlinux 6.8.2-arch2-1

### Mullvad VPN app version

2024.1-1

**Comment by Sacquer** [comment] 2024-04-13 23:05
I got a similar error output when I had a different rust version installed locally (w. asdf), after removing it, I was able to install - I used yay though.

**Comment by eisukeesaki** [comment] 2024-05-10 05:47
Having the same issue.

`
[ace@sozoxp mullvad-vpn]$ makepkg -si
==> Making package: mullvad-vpn 2024.2-1 (Thu 09 May 2024 10:41:50 PM PDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning mullvadvpn-app git repo...
Cloning into bare repository '/home/ace/tmp/mullvad-vpn/mullvadvpn-app'...
remote: Enumerating objects: 353189, done.
remote: Counting objects: 100% (5181/5181), done.
remote: Compressing objects: 100% (2103/2103), done.
remote: Total 353189 (delta 3674), reused 3661 (delta 2923), pack-reused 348008
Receiving objects: 100% (353189/353189), 175.30 MiB | 17.58 MiB/s, done.
Resolving deltas: 100% (228730/228730), done.
  -> Cloning mullvadvpn-app-binaries git repo...
Cloning into bare repository '/home/ace/tmp/mullvad-vpn/mullvadvpn-app-binaries'...
remote: Enumerating objects: 2237, done.
remote: Counting objects: 100% (789/789), done.
remote: Compressing objects: 100% (413/413), done.
remote: Total 2237 (delta 419), reused 644 (delta 360), pack-reused 1448
Receiving objects: 100% (2237/2237), 219.89 MiB | 19.25 MiB/s, done.
Resolving deltas: 100% (1310/1310), done.
  -> Found no-rpm.diff
  -> Found mullvad-vpn.sh
==> Validating source files with sha256sums...
    mullvadvpn-app ... Passed
    mullvadvpn-app-binaries ... Passed
    no-rpm.diff ... Passed
    mullvad-vpn.sh ... Passed
==> Verifying source file signatures with gpg...
    mullvadvpn-app-binaries git repo ... Passed
==> Extracting sources...
  -> Creating working copy of mullvadvpn-app git repo...
Cloning into 'mullvadvpn-app'...
done.
Switched to a new branch 'makepkg'
  -> Creating working copy of mullvadvpn-app-binaries git repo...
Cloning into 'mullvadvpn-app-binaries'...
done.
Switched to a new branch 'makepkg'
==> Starting prepare()...
Submodule 'dist-assets/binaries' (https://github.com/mullvad/mullvadvpn-app-binaries) registered for path 'dist-assets/binaries'
Submodule 'windows/libwfp' (https://github.com/mullvad/libwfp) registered for path 'windows/libwfp'
Submodule 'windows/windows-libraries' (https://github.com/mullvad/windows-libraries) registered for path 'windows/windows-libraries'
Cloning into '/home/ace/tmp/mullvad-vpn/src/mullvadvpn-app/dist-assets/binaries'...
done.
Cloning into '/home/ace/tmp/mullvad-vpn/src/mullvadvpn-app/windows/libwfp'...
Cloning into '/home/ace/tmp/mullvad-vpn/src/mullvadvpn-app/windows/windows-libraries'...
Submodule path 'dist-assets/binaries': checked out 'd5772339cee9c1a0d7671968746f02499b78e245'
Submodule path 'windows/libwfp': checked out '3ea5ca1163a005dd9dbe51167e9a1176574cc348'
Submodule path 'windows/windows-libraries': checked out 'f5114c49bd9845533f193b57d55f27a5fbb47ef0'
patching file gui/tasks/distribution.js
Hunk #1 succeeded at 161 (offset -1 lines).
error: failed to load manifest for workspace member `/home/ace/tmp/mullvad-vpn/src/mullvadvpn-app/android/translations-converter`

Caused by:
  failed to parse manifest at `/home/ace/tmp/mullvad-vpn/src/mullvadvpn-app/android/translations-converter/Cargo.toml`

Caused by:
  TOML parse error at line 1, column 1
    |
  1 | [package]
    | ^^^^^^^^^
  missing field `version`
==> ERROR: A failure occurred in prepare().
    Aborting...
`

Kernel: 6.8.9-arch1-2

**Comment by eisukeesaki** [comment] 2024-05-10 06:09
```
commit d377630dc966e8fb595f1ff9b08e24cd65335918 (HEAD)
Author: Mark Wagie <mark.wagie@proton.me>
Date:   Wed Dec 6 10:53:23 2023 -0700

    2023.6
```

and

```
commit fa01b1aec8ca08f548bf92699d129329ff686be9
Author: Mark Wagie <mark.wagie@proton.me>
Date:   Tue Oct 10 11:00:10 2023 -0600

    2023.5
```

raised the  ` missing field `version` issue.

I was able to install the following version.

```
commit 1fb29e8144a852e246ec45bdf424b9eef490b113
Author: Mark Wagie <mark.wagie@proton.me>
Date:   Wed Jun 28 08:52:52 2023 -0600

    2023.4
```

**Comment by eisukeesaki** [comment] 2024-05-10 06:12
```
commit 6bd52d109fc2a04e0897496414f51db886d7e9ad (HEAD -> master, origin/master, origin/HEAD)
Author: Mark Wagie <mark.wagie@proton.me>
Date:   Mon Apr 29 09:34:26 2024 -0600

    2024.2
```

and

```
commit bb4787400ab213043d2dc0c2fbe7332efa6f0beb
Author: Mark Wagie <mark.wagie@proton.me>
Date:   Thu Mar 21 16:38:09 2024 -0600

    2024.1
```

raised the  `missing field `version`` issue.

I was able to install the following version:

```
commit d377630dc966e8fb595f1ff9b08e24cd65335918
Author: Mark Wagie <mark.wagie@proton.me>
Date:   Wed Dec 6 10:53:23 2023 -0700

    2023.6
```

**Comment by eisukeesaki** [comment] 2024-05-24 03:15
Still having the same issue with 2024.3-2.

```
==> Starting prepare()...
Submodule 'dist-assets/binaries' (https://github.com/mullvad/mullvadvpn-app-binaries) registered for path 'dist-assets/binaries'
Submodule 'windows/libwfp' (https://github.com/mullvad/libwfp) registered for path 'windows/libwfp'
Submodule 'windows/windows-libraries' (https://github.com/mullvad/windows-libraries) registered for path 'windows/windows-libraries'
Cloning into '/home/ace/.cache/yay/mullvad-vpn/src/mullvadvpn-app/dist-assets/binaries'...
done.
Cloning into '/home/ace/.cache/yay/mullvad-vpn/src/mullvadvpn-app/windows/libwfp'...
Cloning into '/home/ace/.cache/yay/mullvad-vpn/src/mullvadvpn-app/windows/windows-libraries'...
Submodule path 'dist-assets/binaries': checked out '7db2c76522e29b4acd8f461fc87f794954c6df95'
Submodule path 'windows/libwfp': checked out '3ea5ca1163a005dd9dbe51167e9a1176574cc348'
Submodule path 'windows/windows-libraries': checked out 'f5114c49bd9845533f193b57d55f27a5fbb47ef0'
patching file gui/tasks/distribution.js
Hunk #1 succeeded at 160 (offset -2 lines).
patching file gui/tasks/distribution.js
error: failed to load manifest for workspace member `/home/ace/.cache/yay/mullvad-vpn/src/mullvadvpn-app/android/translations-converter`

Caused by:
  failed to parse manifest at `/home/ace/.cache/yay/mullvad-vpn/src/mullvadvpn-app/android/translations-converter/Cargo.toml`

Caused by:
  TOML parse error at line 1, column 1
    |
  1 | [package]
    | ^^^^^^^^^
  missing field `version`
==> ERROR: A failure occurred in prepare().
    Aborting...
 -> error making: mullvad-vpn-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
mullvad-vpn - exit status 4

```

**Comment by yochananmarqos** [comment] 2024-06-06 22:08
AUR package maintainer here. Creating issues upstream about the AUR package is pointless, they do not support it. Please read the [pinned comment](https://aur.archlinux.org/packages/mullvad-vpn#comment-719725) on the AUR page.

@2ir Please close this issue. In the future, please comment on the AUR page if you have issues after attempting a clean build.

**Comment by Spunkie** [comment] 2024-06-06 23:06
Ya, what do you think? A security related app/company would actually care about how their app is being consumed on platforms and the issues they're facing because they are too lazy to package it themselves? 

You should have contacted some random guy instead... obviously.

/s?

**Closed as completed** 2024-06-09 09:33 UTC
Labels: bug
