### ISSUE TITLE
"Split Tunnel" ignores Windows Firewall blocking rules

### ISSUE THREAD

**Issue by MarenFayre** [mullvad/mullvadvpn-app#3152] opened 2021-11-26 13:04 UTC
## Issue report

Operating system: Windows 10

App version: 2021.6

#### Issue encountered (transitive case)

1. Block Edge: "Windows Defender Firewall" > Advanced > Outbound Rules > New > Block "%ProgramFiles% (x86)\Microsoft\Edge\Application\msedge.exe"

2. Open some url in Edge, get "Hmmm… your Internet access is blocked" (desired behavior).

3. With Edge closed, click link inside random app (has been replicated with notepad++ "Search on internet" right-click on a link feature). Link opens the system default browser (Edge) but loading fails again as expected.

4. Now enable VPN and add said app to the split tunnel. With Edge still closed, click a link in this app. A new Edge instance opens and successfully loads the page (bypassing the firewall rule) from my home IP (outside the VPN). All further interactions with this new Edge instance are similarly unbounded.

~~The opposite happens if an instance of Edge is already open outside of the tunnel. When I open the link from inside the tunnel,  it will create a new tab that will be correctly blocked. This instance will also keep using the VPN IP instead of my home IP (tested without the firewall rule).~~
I retested it since and actually, if an Edge instance is already opened, clicking a link from inside a tunneled app opens a new tab AND somehow gives it full access + new tabs and current tabs if you reload them.

#### Simple case

Adding Edge itself to the split tunnel in this scenario gives it unrestricted internet access even when blocked in the firewall.

**Comment by faern** [comment] 2021-11-29 10:48
Thanks for reporting this. We'll look into it!

**Comment by mvd-ows** [comment] 2021-11-29 15:00
We've now reproduced the issue on our end.

The reason why this is happening is because the split tunneling driver applies special treatment for any traffic that has been redirected outside the tunnel. It's essentially marking the traffic as being allowed and cancels any further evaluation in the firewall.

I made a quick test wherein the driver applies a regular permit verdict to said traffic. This allows subsequent, lower-weighted, filters to be evaluated and for them to effectively block traffic.

This is probably the correct fix, but it has to be evaluated and tested some more before it can be included in the app.

Are you able to expand a bit on the actual use-case that surfaced this bug?

**Comment by MarenFayre** [comment] 2021-11-30 11:53
So I use Simplewall by Henry++ which can be thought of as a configuration tool for Windows Firewall. Anytime an apps tries to access the internet I get a prompt asking me to choose whether to let this process access the internet, that automatically creates the appropriate rules in the system firewall.

Typically, I can see every Unity game and such pinging off my firewall and I would obviously deny those.

Of course, even if you block an app from accessing the Internet, those can still open webpages in the system default browser sometimes. This is why I keep Edge as my default and block it even though I use Firefox, to prevent such cases. If an app tries to open a webpage it will open but fail to load and I will catch that.

I encountered this issue while playing an MMORPG that uses Cloudflare aggressively. If I try to open their website in Firefox right now with the VPN enabled, I get and "Error 1020: Access denied".  
Therefore what I would typically do is keep a separate, tunneled copy of Firefox to access any website from my home IP when needed (say this game or Netflix). The game executable is similarly tunneled so that I may be able to login to play it.

The issue arose because their game has a built-in feature to access a character's "public character sheet" hosted on their website. Clicking on this would open the default system browser (Edge) and load some url with the character ID in it.  
It was pretty convenient at first so it took me a while to realize what was happening and that this webpage should not be able to load at all since Edge is both blocked on my system, and the fact it loaded meant it wasn’t using the VPN since it got through Cloudflare on their side.

At first, I thought that this might be a bug with Simplewall, so I disabled it and set the firewall rule manually. After checking that wasn’t the case I tried tunneling Notepad++ which does not even use the internet and merely opens the system default browser, and I verified that this new instance no longer used the VPN and bypassed the block. I only go the idea to tunnel Edge itself afterwards.

Anyway, it’s good a sign that you’re able to make sense of what’s happening regarding the firewall issue, since I have no idea how any of this works.

I would also like to point out that I re-tested calling the system default browser from an app inside the tunnel. I can thankfully no longer replicate the "pulling and already opened instance of Edge or Firefox inside the tunnel and under the firewall" that happened while re-testing last time as I edited in my comment (hopefully I just did something really weird that time).  
You would know better than me if your code has the potential to pull existing processes in the tunnel.
However new instances of the browser still open in the tunnel and may trick the user into feeling "safe" when the browser they are using is in fact completely exposed for the rest of the session.

**Comment by mvd-ows** [comment] 2021-11-30 13:15
Thank you, that's very informative.

When the Mullvad App is configured to apply split tunneling on a specific app, that app can be said to be split or excluded.

Be aware that the splitting property is inherited by child processes. This is done so that e.g. splitting Steam will allow all games that are launched from there to be automatically excluded from the tunnel.

In the specific case of web browsers, this can sometimes result in confusing behavior. In the scenario you were working with, Notepad++ and Edge, there will be different results depending on whether Edge is already running.

Scenario #1 - Edge is the default browser, Edge is not running, Notepad++ opens a link: The browser will launch as a child process of Notepad++ and inherit the splitting flag from its parent.

Scenario #2 - Edge is the default browser, Edge is already running, Notepad++ opens a link: A new Edge process is launched to service the new tab being opened. The new process is created as a child of an Edge master process that owns and manages all tabs. Whether the new tab/process is being split depends on whether the Edge master process or any process higher up the process tree are configured to be split.

Hope this helps.

**Comment by MarenFayre** [comment] 2021-11-30 14:55
Ok, I see how that child-rule may be helpful for Steam, but that does not sound so great in other cases privacy-wise, consider this test I just did:
Within a split Notepad++, I clicked a link that opened an Edge instance in the clear. I then downloaded a ".torrent" file from https://webtorrent.io/free-torrents which opened qBittorrent _also_ in the clear (I checked the external IP in the logs and it used my home IP when doing this). With a directly split Firefox instead, "open with app" after downloading a ".torrent" file did not leak, but "opening a magnet link" did somehow (may I remind you that your official website recommends splitting Firefox in order to watch Netflix?).

Anyway, that is still reassuring for my use case. I at least trust myself to work around the pitfalls now once your firewall fix gets approved.

**Comment by mvd-ows** [comment] 2021-11-30 22:58
Right, you have a workflow that starts in an excluded application. Why, and at which point, do you expect the workflow to switch over to using regular tunneled mode?

When performing the torrent/magnet tests, it's possible there was an existing minimized qBittorrent instance still running from before. In this case, a new process is launched momentarily only to queue work into the already existing process, and then swiftly exit. This is an example of when the inheritance of the splitting flag breaks.

How is Netflix related to any of this?

**Comment by MarenFayre** [comment] 2021-12-01 10:28
I meant no offense, I'm sorry I came across that way. I was just sharing a test that I was inspired to do with my new understanding of the feature, this does not realistically impact my workflow in any way.

Regarding Netflix though, the tutorial at https://mullvad.net/en/help/watching-netflix-with-split-tunneling/ simply says that "None of the traffic in the excluded application will go through the VPN". It would be nice if users could discover a stronger warning somewhere, teaching them about the non-obvious pitfalls of tunneling such as opening files directly from a tunneled app like this.

**Comment by mvd-ows** [comment] 2021-12-01 11:09
Thank you. We'll consider your suggestion.

**Comment by mvd-ows** [comment] 2021-12-06 13:10
A fix has been implemented, tested and merged. The merge commit can be seen here: https://github.com/mullvad/win-split-tunnel/commit/b9a1a6d58356f6dd652abc8ded6aba1c42ce6a0b

These changes will be included in the next app release.

**Closed by mvd-ows** 2021-12-06 13:10 UTC
Labels: bug, Windows
