### ISSUE TITLE
[Feature Request] Android: Bridge support

### ISSUE THREAD

**Issue by Pizzacus** [mullvad/mullvadvpn-app#1210] opened 2019-10-20 13:12 UTC
Couldn't find any other issue about this feature. Is bridge/shadowsocks support planned on Android?

Alternatively, do you have an idea on how to make the app work with the Shadowsocks Android app previously used back when we didn't have a Mullvad app?

**Comment by kah0922** [comment] 2019-10-20 16:35
Before either of those things are supported, OpenVPN/TCP support needs to be supported in the Mullvad Android App.

**Comment by Pizzacus** [comment] 2019-10-20 16:38
Wireguard doesn't work through bridges? Hmm, that makes sense then.

**Comment by kah0922** [comment] 2020-07-17 00:32
Any updates on this?

**Comment by faern** [comment] 2020-07-20 09:24
We want to support obfuscation (via for example shadowsocks) on mobile eventually. But this is currently blocked on a few things. Most notably that WireGuard is UDP only and most obfuscation protocols can't really handle that.

We are not going to go backwards in time and add OpenVPN support to mobile. Instead we will find a way to obfuscate WireGuard. But there is no exact timeline for this.

**Comment by faern** [comment] 2021-06-11 09:20
I'm closing this as duplicate of #1049

**Closed by faern** 2021-06-11 09:20 UTC
Labels: feature request
