### ISSUE TITLE
"No internet access" in taskbar and that broke split tunneling apps when switching server

### ISSUE THREAD

**Issue by yur1xpp** [mullvad/mullvadvpn-app#3713] opened 2022-07-01 03:25 UTC
## Issue report

Operating system: Windows 10 21H2

App version: 2022.2

### Issue description

"No internet access" in taskbar status when VPN connected or switching servers. In reality, VPN is connected and has internet access and I can surf the web just fine. But this bothers me because there are apps that are in split tunneling, and they "thought" that they have no internet connection and it won't work (Spotify). Mullvad configured to use Wireguard protocol. However I notice that sometimes if you disable and re-enable the network adapter then reboot computer, it revert to the expected state (shows has internet connection), but once you starts changing the server again, it come back.
![image](https://user-images.githubusercontent.com/34767893/176816840-02319477-26a5-4e39-a73f-3a0fb126767e.png)

**Comment by faern** [comment] 2022-07-01 12:45
Thanks for reporting this. We are semi-aware of this issue. It pops up from time to time. We have tried mitigations earlier to explain to Windows that the tunnel has internet etc. We'll look at it.

**Comment by yur1xpp** [comment] 2022-07-02 09:47
Do you guys have any temporary fix for this at the this moment that doesn't requires a reboot? Perhaps a cli command or such? I'm switching servers a lot so I'll take any workaround that works.

**Comment by LinuxOnTheDesktop** [comment] 2022-07-03 00:34
Cf. #2877?

**Comment by yur1xpp** [comment] 2022-07-03 11:21
Reconnection doesn't works for me sigh

**Comment by xerta555** [comment] 2022-07-05 07:00
I get this issue this morning, i just had to wait some seconds (arround 5-10 seconds) and my network icon become normal.

It's not impossible that this "issue" come from Windows component(s) interface(s) or from a KB..

My logfile: [11e23d2e-e93b-4492-9143-3e9fde53d034.log](https://github.com/mullvad/mullvadvpn-app/files/9043993/11e23d2e-e93b-4492-9143-3e9fde53d034.log)

**Comment by dlon** [comment] 2022-07-08 09:05
@yur1xpp It might be the case that some probe is failing while the tunnel is being set up. But it should retry after a while even if that's the case. Are NLA/NCSI probes are enabled on your machine?

**Comment by LinuxOnTheDesktop** [comment] 2022-07-09 19:50
I find that an ad hoc fix for this problem - or only for _something like_ this problem? I lose track - is to use services.msc to restart the MullvadVPN service.

**Comment by yur1xpp** [comment] 2022-07-12 11:51
Restarting the Mullvad service did indeed temporary fixed it. But I'm not sure if that will causes an IP leak? Kill switch is on, but I'm not very clear on the technicality. Would love if someone can explain that bit.

**Comment by dlon** [comment] 2022-07-12 15:55
In general, you cannot assume that restarting the service won't leak anything unless "always require VPN" is enabled. The leak might be what causes Windows to detect connectivity on your actual network interface. So simply disconnecting and connecting again (rather than "reconnecting") would probably have the same effect.

**Comment by LinuxOnTheDesktop** [comment] 2022-07-28 23:56
Neither workaround - the restarting of the service, and the 'NetRoute' one - worked for me, at least not when automated via Powershell and Task Scheduler. (Each did work when run manually.) However, the latest beta (2022.3-beta3) seems to have fixed the problem (such that on awaking the PC needs no workaround).

**Comment by dlon** [comment] 2022-08-10 10:24
If this issue persists, here is a test build that hopefully should work around the broken connectivity check: https://releases.mullvad.net/builds/2022.3-beta3-dev-8752a8+test-early-dns-build/MullvadVPN-2022.3-beta3-dev-8752a8+test-early-dns-build.exe

In order for it to work, you may have to disable all of the DNS-based blocking features (adblocking, tracker blocking, etc.) as well as custom DNS.

I can't reproduce the problem exactly, but the test build does fix the issue of *temporarily*  ending up with "no internet access".

**Comment by yur1xpp** [comment] 2022-08-17 13:07
I'm still experiencing this even on 2022.3 release build.

**Comment by dlon** [comment] 2022-08-18 09:01
@yur1xpp: Good to know. Have you tried the test build or the delete/add route workaround mentioned above?

**Comment by yur1xpp** [comment] 2022-08-26 07:28
Update: 2022.4 still have the same issue

@dlon yeah I did tried the method, it doesn't works for me.

**Comment by yur1xpp** [comment] 2022-08-30 04:18
Having tried 2022.4 for few days, this is the worst version where the issue occur every few minutes, occurs without even the change of server.

**Comment by LinuxOnTheDesktop** [comment] 2022-09-10 13:48
Would someone tell me the identity of the file(s) that contain(s) the code that handles split-tunnelling, on Windows and (if there is separate code for this) on Wireguard? I've reached the level of frustration where I'm willing to try to debug the code myself, even though I don't (presently) know the Rust programming language.

**Comment by yur1xpp** [comment] 2022-09-28 11:03
I have no idea but I'm happy that someone actually trying to debug this, it's been 3 months since reported and it's still persisting, to say that I'm freaking annoyed is understatement.

**Comment by LinuxOnTheDesktop** [comment] 2022-09-29 08:59
@yur1xpp: don't get your hopes up. For: I am merely a user, and not much of a programmer; and no-one has given me the information for which I asked.

**Comment by Nalci** [comment] 2022-10-05 17:10
Hello!

I'm new to mullvad and I have the same problem. I have the latest version installed.

I tried to restart the connection, restart the app, change the location, changing from 5 GHz frequency to 2.4 GHz but nothing helped. Sometimes it works but that's pretty much luck. 

It's really annoying since Spotify for example stops working after some time and I have to use the website for music streaming.

**Comment by dlon** [comment] 2024-11-28 14:16
Is this still an issue?

**Comment by dlon** [comment] 2024-12-09 15:50
Please reopen the issue if this is still a problem.

**Closed by dlon** 2024-12-09 15:50 UTC
Labels: bug, Windows
