### ISSUE TITLE
[Android] Using DAITA together with shadowsocks does not work over WIFI

### ISSUE THREAD

**Issue by gsture** [mullvad/mullvadvpn-app#6864] opened 2024-09-25 08:45 UTC
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

After testing i came to the conclusion that using DAITA together with shadowsocks on android does not work over wifi at the moment. The VPN says it is connected but no data seems to be going through.

- It does work over 5g.
- When the vpn is connected over 5g and i turn on wifi it still works.
- When i reconnect the vpn over wifi it stops working again.
- Tried it on 2 separate wifi networks.

### Expected Behavior

If the VPN says it is connected it should work.

### Steps to Reproduce

1. Enable DAITA
2. Enable shadowsocks.
3. VPN connects but no data is going through.

### Android versions

GrapheneOS 14 (AP2A.240905.003) and Android 12

### Device models

2 x Pixel 8 and Samsung s10

### Mullvad VPN app version

2024.5 beta 2

**Comment by albin-mullvad** [comment] 2024-09-25 08:55
Thanks for the report @gsture! This combination should work and we've tested it on a set of devices, including a Pixel 5 running Graphene. So either it could be related to other app/device settings or perhaps related to the network you're connecting over. Can you shared some more details? Did you try connecting over both mobile data and wifi networks? Thanks!

**Comment by gsture** [comment] 2024-09-25 09:01
> Thanks for the report @gsture! This combination should work and we've tested it on a set of devices, including a Pixel 5 running Graphene. So either it could be related to other app/device settings or perhaps related to the network you're connecting over. Can you shared some more details? Did you try connecting over both mobile data and wifi networks? Thanks!

Ok did some more testing. 
- It does indeed work over 5g. 
- When the vpn is connected over 5g and i turn on wifi it still works. 
- When i reconnect the vpn over wifi it stops working again.

**Comment by gsture** [comment] 2024-09-25 09:09
I also tried this on my samsung s10 and another pixel 8. All 3 phones have the same issue.

**Comment by homer907** [comment] 2024-09-25 16:10
I'm not seeing the DAITA option on my android app. I'm on version 2024.4, enrolled in beta version, Android 13. Is this feature only working with shadowsocks and coming later as a toggle like the Windows app?

**Comment by gsture** [comment] 2024-09-25 16:22
> I'm not seeing the DAITA option on my android app. I'm on version 2024.4, enrolled in beta version, Android 13. Is this feature only working with shadowsocks and coming later as a toggle like the Windows app?

You can use DAITA separate. You need version 2024.5 for both DAITA and shadowsocks. The beta is available on github. I don't know if this version is released to playstore. If so it takes a while before an app is available on playstore after a developer releases it.

**Comment by gsture** [comment] 2024-09-27 05:56
> Thanks for the additional information! We've also tested this combination on both mobile data and wifi networks, so it's probably related to how certain networks are configured. It would really help if you could share some logs so that we can investigate further, would that be possible? You can send those directly from the app to our support team. Please reference this issue and ask for it to be forwarded to the android team.



> Thanks for the additional information! We've also tested this combination on both mobile data and wifi networks, so it's probably related to how certain networks are configured. It would really help if you could share some logs so that we can investigate further, would that be possible? You can send those directly from the app to our support team. Please reference this issue and ask for it to be forwarded to the android team.

[mullvad_log-#6864-1.txt](https://github.com/user-attachments/files/17159627/mullvad_log-.6864-1.txt)

It happens on 2 seperate wifi networks but also when i use another phone as a hotspot.

Let me know if you need any more information.

**Comment by gsture** [comment] 2024-10-02 11:42
I did some more testing with shadowsocks. The connection also stops working without daita, Shadowsocks does connect and work when you first set it but when you roam from 1 access point to another or the phone switches from wifi to cellular the vpn stops working with shadowsocks enabled.

**Comment by Pururun** [comment] 2024-10-17 13:26
There is an issue with Shadowsocks and UDP-over-TCP obfuscation in 2024.5 and 2024.6.

This is probably the culprit for this issue as well.

A fix for this will be in the next release, so please confirm this when that version is available.

**Comment by Rawa** [comment] 2024-10-18 13:20
Release: https://github.com/mullvad/mullvadvpn-app/releases/tag/android%2F2024.7

**Comment by Rawa** [comment] 2024-10-18 17:52
Thanks for the quick reply. I'll spend time on Monday looking closer into this and try to reproduce it. I have a Pixel 8, running Android 15, we also have some other devices I can try and reproduce this in.

Do you know if you can reproduce this issue across multiple different WiFi's?

**Comment by Rawa** [comment] 2024-10-21 14:50
Spent some more time today to reproduce your issue. I believe have been able to, however it is a bit flaky. Do you get this time everytime you roam from mobile to WiFi?

**Comment by Rawa** [comment] 2024-10-22 13:04
Thanks for your report, I believe we have identified the issue and are working on merging fixes. I'll update here with a test build soon where you can try out if it resolves your issue.

**Comment by Rawa** [comment] 2024-10-22 13:26
@gsture Please test the following build:
https://releases.mullvad.net/android/builds/2024.8-beta1-dev-7a0b67%2Bandroid-no-connect-ss-fix/?C=M&O=D

**Comment by Rawa** [comment] 2024-10-22 14:53
Thanks for the quick testing, is still the exact behavior the exact same one?

>- When connected to wifi: If daita and shadow socks are enabled together the vpn does never work. Mullvad app says connected but no data is going through.
>- When connected to mobile network: VPN works fine with the same settings.
>- When i switch from mobile to wifi it will stop working again after a few minutes.
>- Post quantum on or off does not matter.
>- Shadowsocks alone works fine now on 2024.7

That DAITA and Shadowsocks never works when on WiFi? According to the logs PQ and Shadowsocks seems to be enabled. Can you try settings the MTU to 1420 to see if that changes anything?

From my testing DAITA and shadowssocks works fine, with the latest fix. The issue patched above fixes that roaming from Mobile data to Wifi would keep sending data towards mobile network until it goes down and then start dropping packages, until it discovered the tunnel was broken and then it would reconnect and setup the tunnel again.

**Comment by Rawa** [comment] 2024-10-22 15:05
> > That DAITA and Shadowsocks never works when on WiFi? According to the logs PQ and Shadowsocks seems to be enabled. Can you try settings the MTU to 1420 to see if that changes anything?
> > 
> > From my testing DAITA and shadowssocks works fine, with the latest fix. The issue patched above fixes that roaming from Mobile data to Wifi would keep sending data towards mobile network until it goes down and then start dropping packages, until it discovered the tunnel was broken and then it would reconnect and setup the tunnel again.
> 
> Yes exact same behavior. It never works. Setting mtu to 1420 did not fix this. I will test this on another network this evening i am not near another network at the moment. I will report back with my findings.

Maybe obvious, but I assume you are also connected to one of the daita supported servers when testing daita (Netherlands/USA/UK)?

Best regards

**Comment by Rawa** [comment] 2024-10-22 15:11
> > > > That DAITA and Shadowsocks never works when on WiFi? According to the logs PQ and Shadowsocks seems to be enabled. Can you try settings the MTU to 1420 to see if that changes anything?
> > > > From my testing DAITA and shadowssocks works fine, with the latest fix. The issue patched above fixes that roaming from Mobile data to Wifi would keep sending data towards mobile network until it goes down and then start dropping packages, until it discovered the tunnel was broken and then it would reconnect and setup the tunnel again.
> > > 
> > > 
> > > Yes exact same behavior. It never works. Setting mtu to 1420 did not fix this. I will test this on another network this evening i am not near another network at the moment. I will report back with my findings.
> > 
> > Maybe obvious, but I assume you are also connected to one of the daita supported servers when testing daita (Netherlands/USA/UK)?
> 
> xD How low do you think of me 😂 Yes it is connected to a daita server, i am sure. I don't think is even possible to connect to anything else if you active daita in recent versions of the app.

😂 Just trying to eliminate possible faults, since we are unable to reproduce your issue on our end. Please, get back with your tests on the other network. I'll continue the investigation tomorrow as well. 👍

**Comment by Rawa** [comment] 2024-10-23 13:12
I don't see anything out of the ordinary from the logs. How did your testing on other WiFi go? I also got word that there possibly is a problem with IPv6 and MTU size, could you check if you are using IPv6 on your WiFi?

I've also had another colleague test GrapheneOS 15 on his phone, both roaming and just WiFi. For us DAITA + Shadowsocks on WiFi works fine (IPv4).

**Comment by Rawa** [comment] 2024-10-23 13:58
Glad to hear you got that working with hotspot, I'm looking forward to the update to see your findings on your local network. 🙏

**Comment by Rawa** [comment] 2024-10-23 16:27
The latest tests you performed, was it with the new version that includes the MTU fix? I'd just like to confirm that it doesn't have anything to do with it.

**Comment by Rawa** [comment] 2024-10-28 12:30
Closing as agreed upon, let me know if you make any more finding the future. Thanks for you help! 🙏

**Closed by Rawa** 2024-10-28 12:30 UTC
Labels: bug, Android
