### ISSUE TITLE
Internet doesn't work after network switching

### ISSUE THREAD

**Issue by devalps** [mullvad/mullvadvpn-app#1847] opened 2020-06-15 07:29 UTC
## Issue report

Operating system: iOS 13.5.1

App version: 2020.3

### Issue description

I have problem with using mullvad app on iOS. When i'm changing network from LTE to WIFI. Internet doesn't work. This is very often and only solution is reboot phone. That's pain in ass. With this behaviour had a lot of problems cloudflare 1.1.1.1 wireguard vpn too. But after months that was solved. But on mullvad side now. That's not possible to use app. 
**Sometimes it doesn't work even after a restart. when I turn on mullvad, the internet just doesn't work.**

**Comment by faern** [comment] 2020-06-15 08:48
Thanks for reporting this. We will look into it.

**Comment by garrettoreilly** [comment] 2020-10-25 01:20
I’m still seeing this issue, even switching between access points on the same network.

iOS 14.1  
Mullvad 2020.4

**Comment by dallasbrittany** [comment] 2021-01-07 16:05
I'm still seeing it too (iOS 14.3). Switching VPN locations seems to help, but I'm not sure if it always does. I usually just give up using Mullvad for a few days, and it starts working again at some point. I'll try rebooting my phone next time it happens if switching locations doesn't work.

**Comment by pinkisemils** [comment] 2023-03-13 15:06
Closing this as this as this is a duplicate of #1785.

**Closed by pinkisemils** 2023-03-13 15:06 UTC
Labels: bug, iOS
