### ISSUE TITLE
[Feature Request] Add randomize server and time options

### ISSUE THREAD

**Issue by manakill** [mullvad/mullvadvpn-app#4831] opened 2023-06-26 17:23 UTC
It would be awesome if there were options the user could set to randomize servers in a Location

For example:
Location: Chicago, IL USA
Randomize connection every: 7 minutes

This would make the app pick a random server in the Chicago, IL Location - every 7 minutes.
Also have larger Geographic Locations for that setting also, such as USA.
Also have a time range or wildcard(100% random) time of when to change connections

**Comment by faern** [comment] 2023-06-26 18:33
You can already do basically all of this. If you select IL, USA it will choose a random server in that location every time the app connects/reconnects. Same if you just select the country USA, then it will pick a random server from all servers in the country.

Since you did not say on what platform you are, I'm going to assume you are on one of the three desktop platforms. On desktop you can script automatic reconnects with the CLI. If you open a terminal and run `mullvad reconnect` it will trigger a reconnect. Now you can just set up some kind of automation that runs this command every x minutes if you wish.

If you are on mobile you have to manually go in and reconnect in the app for now.

**Comment by faern** [comment] 2023-06-26 18:35
I'm going to close this as a duplicate of #2623

**Closed by faern** 2023-06-26 18:35 UTC

**Comment by manakill** [comment] 2023-06-27 06:47
No, you misunderstood the explicit details lol. Please reread

**Comment by faern** [comment] 2023-06-27 09:26
You have to explain the detail I'm missing then. What I do understand:

* Have the app pick a random server within a location constraint on every reconnect - This is how the app worked since the initial release in 2017. Select a location and every connection attempt will pick a random server in that location
* Have the app reconnect automatically at a fixed interval - Yes, that's what the linked feature request is about also. We will consider this and put it in the backlog.
* Have said automatic reconnect introduce some jitter/randomness to further improve anonymity by not always reconnecting after the exact same time - We might consider this when writing the spec for the above, but it's probably going to be worse for the UX than it delivers on anonymity.

**Comment by dukethorion** [comment] 2023-10-07 16:26
+1 for auto-reconnect.  Especially on mobile/Android.

Every 24 hours would be phenomenal.  (I'd suggest 6, 12, 24 hr, and maybe weekly as intervals).

Could have a choice between "Rotate between random servers" or "Rotate servers at location: X"
