### ISSUE TITLE
Cannot connect to HostedNetwork (WiFi Hotspot) from other devices!

### ISSUE THREAD

**Issue by pundoo** [mullvad/mullvadvpn-app#777] opened 2019-03-29 08:54 UTC
When Mullvad is open and active, it's for some reason blocking other devices from connecting to the hosted-network (WiFi status gets stuck at the 'Obtaining IP address...' state). Works fine when inactivated.

For what it's worth, I have ''Local network sharing' enabled and using on Windows 10 (v1809)

**Comment by faern** [comment] 2019-03-29 09:57
Thanks for the report. I assume you use the latest version of the app? `2019.2`.

Do you mean you host a wifi network on the computer running the Mullvad VPN app, and other devices fail to connect to that computer? Or your computer running Mullvad fails to connect to another wifi?

**Comment by pundoo** [comment] 2019-03-29 10:05
Yes, I'm using `2019.2` (however same issue persisted in `2019.1`)

> Do you mean you host a wifi network on the computer running the Mullvad VPN app, and other devices fail to connect to that computer?

Yes! When Mullvad is connected.

**Comment by faern** [comment] 2020-02-14 14:08
Is this still an issue. Closing due to inactivity. Please re-open if it's still a problem with the latest app version and with a fully updated Windows install.

**Comment by ChrisInacio** [comment] 2022-04-21 12:27
This is still an issue!

**Comment by faern** [comment] 2022-04-22 08:29
Okay! Sad to hear that. Could you please provide a good description of your setup and how to reproduce the issue?

**Comment by ChrisInacio** [comment] 2022-04-22 22:15
I have also tried _Static IP_ in the android settings.

For this I went into CMD and got the mullvad adapter settings using _ipconfig /all_.

The IPV4 address was 10.5.0.1 (if I am not mistaken). So I went into the Static IP settings on android, and set the following:

- IP: 10.5.0.13 (i choose this randomly)
- Router IP: 10.5.0.1
- Prefix: 16 (because subnet mask is 255.255.0.0
- DNS: 100.64.0.3 (if I am not mistaken)

Using this method I was able to connect to the WiFi network, however it does not have an active internet connection.
So, it is either a setting that is wrong... Or this method does not work.

I think that is all I know...
Sorry for the long text.

**Comment by ChrisInacio** [comment] 2022-04-24 17:46
> Okay! Sad to hear that. Could you please provide a good description of your setup and how to reproduce the issue?

So, so far i have managed to locate the issue. The Microsoft Adapter that is responsible for the WiFi hotspot does not have the DHCP server enabled.
I have used the following settings on the Android and managed to get it working:
- IP: 192.168.137.110 (I used a pool from .110 to .200)
- Router: 192.168.137.1
- Prefix: 24
- DNS 1: 192.168.137.1
- DNS 2: 8.8.8.8

It appears that the IP I needed to use was the one from the Microsoft Adapter (not the mullvad adapter).

The only issue I need to fix right now is the DHCP server. I have Windows 10 Home and I have not yet found a software that could create the hotspot and have a DHCP server built-in.

I don't know if there is a simpler way of doing it, but I would appreciate if you could teach me.

**Comment by faern** [comment] 2022-04-25 07:59
So there was no issue with our app blocking the wifi clients then? Going to close this issue again then.

Regarding DHCP server on Windows 10 Home: I don't know. I have never operated a DHCP server on Windows. So I'm sorry, but I don't think I can help you there.

**Closed by faern** 2022-04-25 07:59 UTC
