### ISSUE TITLE
Mac randomization at mullvad start/system boot

### ISSUE THREAD

**Issue by 666Danger-sudo** [mullvad/mullvadvpn-app#5488] opened 2023-11-22 18:23 UTC
## Issue report

Operating system: Debian 11 and 12

App version: 2023.5

### Issue description

So the issue started when I wanted to create a script that randomizes the mac address of my main interface at system boot. I created my script and placed it in /etc/NetworkManager/dispatcher.d/. It uses macchanger to change the mac. The problem is when I turn on the VPN, the mac address is switched back to the original.
It would be cool that there is an option that if turned on, the mac is randomized at system start no matter if the vpn is on or not.

**Comment by faern** [comment] 2023-11-23 09:59
I have created an internal tracking ticket for this: https://linear.app/mullvad/issue/DES-479/mac-address-of-physical-interface-being-reset-when-mullvad-connects

**Comment by raksooo** [comment] 2023-12-12 09:55
@666Danger-sudo We're not able to reproduce this. We've tried it on Debian 12 with the 2023.6 app and the randomized mac-address isn't reset.

**Comment by raksooo** [comment] 2023-12-12 14:41
I'll close this since we can't reproduce it.

**Closed by raksooo** 2023-12-12 14:41 UTC
Labels: bug, feature request
