### ISSUE TITLE
Failed to download the list of relays - 6-bit remainder error

### ISSUE THREAD

**Issue by emacsomancer** [mullvad/mullvadvpn-app#1723] opened 2020-05-08 06:08 UTC
## Issue report

Operating system: Linux 5.6.11

App version: both 2020.03 and 2020.04-beta4

### Issue description

the daemon is unable to start properly, reporting:
````
.....
[2020-05-08 00:04:20.962][mullvad_daemon::relays][ERROR] Error: Failed to download the list of relays
Caused by: Serialization error
Caused by: Encoded text cannot have a 6-bit remainder. at line 1 column 118246
````

I've tried both on the stable 2020.03 and 2020.04-beta4. I've been running without issue on 2020.03 for a while, and only tonight did this issue appear.

**Comment by faern** [comment] 2020-05-08 08:57
Thanks for reporting this. This was due to a temporary error in the data we sent out from the API. This is now fixed. It's not a bug in the app per se.

**Closed by faern** 2020-05-08 08:57 UTC
