### ISSUE TITLE
WireGuard over TCP & multiplehopping

### ISSUE THREAD

**Issue by acrostich** [mullvad/mullvadvpn-app#3071] opened 2021-11-01 16:01 UTC
## Issue report

Operating system: macOS 11.6.1

App version: 2021.5

### Issue description

I use wg multihopping. I just read the blog post https://mullvad.net/en/blog/2021/11/1/introducing-wireguard-over-tcp-and-ipv6/ and failed to figure out how to combine the instructions about how to set up wg over TCP and how to set it up for wg multihopping.

It would helpful to document how to do this at https://mullvad.net/en/help/cli-command-wg/ or if not supported, mention this.

**Comment by dlon** [comment] 2021-11-01 17:56
The UI is clunky at the moment. What you'll want to do is pick one (or a subset) of the TCP servers as your entry relay at the same time as you set the protocol to TCP. For example:
```
mullvad relay set tunnel wireguard --entry-location se sto se6-wireguard --protocol tcp
```
The `entry-location` option follows the same syntax as `mullvad relay set location`.

**Comment by acrostich** [comment] 2021-11-02 01:52
Thank you very much. With a command based on your example I do get connectivity with a status of the form:
`Tunnel status: Connected to WireGuard x.y.z.w:p over UDP via a.b.c.d:q over TCP`

Is that what should be expected, i.e., UDP encapsulated over a TCP tunnel  as the TCP tunnel will go through problematic networks and the encapsulated protocol doesn't matter for the potentially blocking network the VPN is on? (I'm not close to a problematic network at the moment so can't test it.)

Should it affect performance negatively? Ping times in a few tests were slower when over TCP, but that's just one performance indicator.

**Comment by dlon** [comment] 2022-05-03 11:36
Your description is essentially correct regarding the transport protocol used for the exit node. It is expected behavior. As for performance, it will indeed be reduced to some extent. One reason is that [udp-over-tcp](https://github.com/mullvad/udp-over-tcp) has not been heavily optimized (yet), but there's always going to be some overhead anyway.

I'm closing this issue since everything is working as intended.

**Closed by dlon** 2022-05-03 11:36 UTC
