### ISSUE TITLE
whitelisting explorer leaks in browser

### ISSUE THREAD

**Issue by EntranceJew** [mullvad/mullvadvpn-app#4242] opened 2022-12-22 00:24 UTC
## Issue report

Operating system: Win10 Home / 19045.2364 22H2

App version: 2022.5

### Issue description

If you split-tunnel whitelist explorer.exe so that you can browse LAN SMB connections, for example, it will leak according to the tester on the website.

Incidentally the app puts some invisible spacer between my system clock and my volume mixer and if I ever lose focus with it, then i have to run it again from the start menu because whatever "taskbar snapping" feature it has does not work.

**Comment by pinkisemils** [comment] 2022-12-22 10:59
Is it possible to reach the SMB connections with LAN traffic enabled? If you cannot reach them still, have you verified you've added the routes to LAN?

Does the invisible spacer thing happen even when explorer isn't being split?

**Comment by dlon** [comment] 2022-12-22 11:23
Any program launched from the taskbar/desktop is a subprocess of `explorer.exe`, so the leak you're seeing is probably expected behavior. We'll most likely add a warning about this.

**Comment by EntranceJew** [comment] 2022-12-23 14:22
> Does the invisible spacer thing happen even when explorer isn't being split?
yes

> Is it possible to reach the SMB connections with LAN traffic enabled? If you cannot reach them still, have you verified you've added the routes to LAN?
I can with VLC and other programs.

**Comment by faern** [comment] 2022-12-27 08:30
It is not recommended to exclude `explorer.exe` from the VPN tunnel. If you want to browse the LAN you should enable "Local network sharing". I'm closing this as it works as intended.

**Closed by faern** 2022-12-27 08:30 UTC
Labels: bug, Windows
