### ISSUE TITLE
Mullvad-vpn Segfaults when opening GUI

### ISSUE THREAD

**Issue by TheDenast** [mullvad/mullvadvpn-app#5075] opened 2023-08-30 20:18 UTC
Operating system: Arch Linux (Wayland, Hyprland)

App version: 2023.4
Side note: Installed from AUR, package `mullvad-vpn-bin`

VPN connects just fine through CLI commands. GUI app also launches just fine minimized. Once maximized, segfaults and crashes when given focus.

```
denast@denastPC ~> mullvad-vpn
[2023-08-30 16:12:37.294][verbose] Chromium sandbox is enabled
[2023-08-30 16:12:37.295][info] Running version 2023.4
[2023-08-30 16:12:37.365][info] Detected locale: en-US
[2023-08-30 16:12:37.401][info] Connected to the daemon
[43192:0830/161237.453177:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is egl, ANGLE is 
[2023-08-30 16:12:37.476][info] Autoconnect the tunnel
[43192:0830/161237.479049:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglCreateImageKHR: createImageFromDmaBufs failed
[43192:0830/161237.479121:ERROR:gl_image_egl.cc(38)] Error creating EGLImage: EGL_BAD_ALLOC
[43192:0830/161237.479171:ERROR:native_pixmap_egl_binding.cc(28)] Unable to initialize GL image from pixmap
[43146:0830/161238.006526:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=133
[2023-08-30 16:12:38.007][error] Child process of type GPU exited with exit code 133 due to crashed
[43257:0830/161238.127915:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is egl, ANGLE is 
[43257:0830/161238.146673:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglCreateImageKHR: createImageFromDmaBufs failed
[43257:0830/161238.146762:ERROR:gl_image_egl.cc(38)] Error creating EGLImage: EGL_BAD_ALLOC
[43257:0830/161238.146812:ERROR:native_pixmap_egl_binding.cc(28)] Unable to initialize GL image from pixmap
[2023-08-30 16:12:38.314][error] Failed to check autostart file: ENOENT: no such file or directory, access '/home/denast/.config/autostart/mullvad-vpn.desktop'
[43146:0830/161238.727284:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=133
[2023-08-30 16:12:38.727][error] Child process of type GPU exited with exit code 133 due to crashed
[43304:0830/161238.816563:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is egl, ANGLE is 
[43304:0830/161238.835388:ERROR:gl_display.cc(504)] EGL Driver message (Critical) eglCreateImageKHR: createImageFromDmaBufs failed
[43304:0830/161238.835465:ERROR:gl_image_egl.cc(38)] Error creating EGLImage: EGL_BAD_ALLOC
[43304:0830/161238.835507:ERROR:native_pixmap_egl_binding.cc(28)] Unable to initialize GL image from pixmap
[43234:0830/161239.479470:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[43146:0830/161239.481828:ERROR:gpu_process_host.cc(953)] GPU process exited unexpectedly: exit_code=133
[2023-08-30 16:12:39.481][error] Child process of type GPU exited with exit code 133 due to crashed
[43234:0830/161239.552455:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
/usr/bin/mullvad-vpn: line 2: 43146 Segmentation fault      (core dumped) "/opt/Mullvad VPN/mullvad-vpn" %U
```

**Comment by raksooo** [comment] 2023-08-31 06:37
Thanks for reporting! Could you try the 2023.5-beta1 release to see if that solves the issue?

**Comment by Hydroxycarbamide** [comment] 2023-10-11 19:34
2023.5 release does not fix the issue.

**Comment by pinkisemils** [comment] 2023-10-11 21:49
Works fine on Gnome 45 with the latest packages on Arch and _Tray Icons: Reloaded_ plugin. What DE are you using?

**Comment by Hydroxycarbamide** [comment] 2023-10-11 21:51
Sorry I forgot to mention it. Like @TheDenast, I am using Hyprland.

**Comment by pinkisemils** [comment] 2023-10-11 22:12
What status bar are you using? Or would you mind sharing your Hyprland config file? Unfortunately, I do not have the patience to configure it far enough to have a working terminal and a status with that can display status icons.

**Comment by Hydroxycarbamide** [comment] 2023-10-11 22:30
Sure I don't mind, here is my [hyprland.conf](https://gist.github.com/Hydroxycarbamide/dda15c11b183441c63eb892bd016d48d). I am using Hyprland 0.30.0 with Waybar 0.9.22.

**Comment by mur1chan** [comment] 2023-10-13 12:53
yeah i'm facing the same issue. i also use waybar and hyprland

**Comment by Hamza-Rafi** [comment] 2023-10-15 14:46
also coming across this issue using waybar and hyrland too

**Comment by Puumpkin** [comment] 2023-10-16 19:48
im using hyprland and waybar and have the issue aswell

**Comment by NorNub** [comment] 2023-10-19 15:27
same issue, arch, hyprland, waybar

**Comment by NorNub** [comment] 2023-10-19 15:30
Same issue, arch,hyprland,waybar only crashes when hovering cursor over got it

**Comment by Hamza-Rafi** [comment] 2023-10-19 15:57
This is also causing the mullvad cli to not work. When trying to connect to a server it just keeps saying 'Connecting' forever.

**Comment by MidnightSlicer** [comment] 2023-10-19 22:49
Can confirm this is still an issue. Arch, Hyprland-git, waybar-git. I wonder if it has something to do with the Electron version change?

**Comment by raksooo** [comment] 2023-10-20 06:52
I suspect it's caused by the Electron upgrade. We've upgraded Electron again which will be part of the next version. I haven't tested this myself but there is a chance that it's been fixed. We'll hopefully release a beta very soon.

**Comment by mur1chan** [comment] 2023-10-21 12:27
> I suspect it's caused by the Electron upgrade. We've upgraded Electron again which will be part of the next version. I haven't tested this myself but there is a chance that it's been fixed. We'll hopefully release a beta very soon.

do you have any eta for the beta release? :)
it's not so important for me as the mullvad cli is currently my workaround but just to know :+1:

**Comment by tmcybers** [comment] 2023-11-09 12:21
i had same issue, im on arch, hyprland, waybar is crashes when hovering cursor over it. im using aur/mullvad-vpn 2023.5-1 (+125 1.99) (Installed)
    The Mullvad VPN client app for desktop

**Comment by andersmmg** [comment] 2023-11-09 14:50
Same issue, GUI is unusable as it crashes pretty much as soon as it's un-minimized. Using Hyprland on Arch

**Comment by Eclipse222** [comment] 2023-11-15 03:35
Using gamescope with mullvad-vpn works fine as an alternative :)

**Comment by DMNinja** [comment] 2023-11-20 16:51
Can also confirm. Package `mullvad-vpn-bin` Segfaults with error 
```[2023-11-20 18:49:01.894][verbose] Chromium sandbox is enabled
[2023-11-20 18:49:01.895][info] Running version 2023.5
[2023-11-20 18:49:01.972][info] Detected locale: en-US
[2023-11-20 18:49:02.008][info] Connected to the daemon
[2023-11-20 18:49:02.094][info] Skip autoconnect because account token is not set
[2023-11-20 18:49:02.385][error] Failed to check autostart file: ENOENT: no such file or directory, access '/home/dmninja/.config/autostart/mullvad-vpn.desktop'
/usr/bin/mullvad-vpn: line 2: 31404 Segmentation fault      "/opt/Mullvad VPN/mullvad-vp```

Using hyprland-git and nwg-panel 0.9.17-2

**Comment by sinnayuh** [comment] 2023-11-22 17:48
> Using gamescope with mullvad-vpn works fine as an alternative :)

Are you running it in terminal or created a new .desktop file doing this?

**Comment by Eclipse222** [comment] 2023-11-22 19:50
Doing this via terminal. I'll figure out if I can make some .desktop file.

The main issue is the black boxes the gamescope makes, anyone knows a fix?

**Comment by MidnightSlicer** [comment] 2023-11-27 02:21
I just installed the mullvad-vpn-bin (2023.6-beta1) package from the AUR and the application now works as expected on Hyprland. I attribute this to the Electron update (Update Electron from 25.2.0 to 26.3.0). https://github.com/mullvad/mullvadvpn-app/releases/tag/2023.6-beta1

**Comment by raksooo** [comment] 2023-11-29 12:45
@MidnightSlicer Great to hear that it now works! Thanks for notifying us. Yes Electron has been the most likely culprit. I'll close this issue. If anyone still experiences this please write here and we'll reopen the issue.

**Closed by raksooo** 2023-11-29 12:45 UTC
Labels: bug, Linux, Desktop frontend
