### ISSUE TITLE
Interface becomes white

### ISSUE THREAD

**Issue by GokturkTalha** [mullvad/mullvadvpn-app#7117] opened 2024-11-01 21:03 UTC
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

Like in the video, sometimes mullvad vpns interface becomes white and when i take it under it turns normal. It doesnt effects my experience badly but it would be better if this doesnt happen

https://github.com/user-attachments/assets/da65bec7-551b-4025-8995-c012adf20afc

### Expected Behavior

explained above

### Steps to Reproduce

idk it happens randomly

### Operating system version

Linux Mint Cinammon 22

### Mullvad VPN app version

2024.7

**Comment by Serock3** [comment] 2024-11-04 10:48
This is a duplicate of <https://github.com/mullvad/mullvadvpn-app/issues/3068>.

**Closed by Serock3** 2024-11-04 10:48 UTC
Labels: bug
