### ISSUE TITLE
[Feature Request][Android] Support for allowing certain apps to bypass the VPN?

### ISSUE THREAD

**Issue by steamp0rt** [mullvad/mullvadvpn-app#1343] opened 2019-12-13 10:56 UTC
For example, allowing Netflix/Disney+/etc to ignore the VPN. In addition, some apps like KDE Connect won't work through VPNs.

Like, similar to the PIA app.

**Comment by faern** [comment] 2019-12-13 12:34
Duplicate of #781. Closing this issue.

**Closed by faern** 2019-12-13 12:34 UTC

**Comment by steamp0rt** [comment] 2019-12-13 13:12
Oh thanks, I looked to see if this would be a duplicate, but I didn't think of it as "split traffic"!
