### ISSUE TITLE
LAN packets pass firewall if split-tunneling enabled

### ISSUE THREAD

**Issue by TobyGiacometti** [mullvad/mullvadvpn-app#2103] opened 2020-09-10 16:40 UTC
## Issue report

Operating system: Debian GNU/Linux 10 (Buster)

App version: 2020.05

### Issue description

Outgoing packets for the LAN from an excluded process (`mullvad-exclude`) still pass the firewall even if local network sharing is disabled. Following rule is responsible:

```
table inet mullvad {
	chain output {
		type filter hook output priority 0; policy drop;
		mark 0x00000f41 accept
	}
}
```

**Comment by faern** [comment] 2020-09-10 21:13
This is expected and by design. An excluded process (started with `mullvad-exclude`) should behave as close as possible to how it would behave if Mullvad was not running at all. And if Mullvad was not running at all it would not block your LAN.

**Comment by faern** [comment] 2020-09-10 21:15
How do you view excluded processes? What behaviour would feel the most natural to you?

**Comment by TobyGiacometti** [comment] 2020-09-10 21:29
I see where you are coming from, and I do not disagree. I think it comes down to whether `mullvad-exclude` is solely used for the split-tunneling feature or whether it is a more general utility that tells the Mullvad VPN app to "ignore" packets from a specific process. If `mullvad-exclude` is supposed to be used for the split-tunneling feature alone, I do think it makes sense to honor the local sharing setting. Why? Because LAN traffic never goes through the tunnel. One could argue that split-tunneling should only concern itself with traffic that is actually tunneled (WAN traffic only in this case).

**Comment by faern** [comment] 2020-09-11 08:18
`mullvad-exclude` is intended solely for the split tunneling feature indeed. That's the program that the GUI uses to launch split programs. But the way we see split tunneling is that it's excluded from everything the VPN app does. I don't really see a strong use case for having a program where you trust it to talk to the entire internet freely but you don't trust it to talk to your LAN.

If implemented the way you describe. There would not be any way to allow only a few programs to talk to the LAN without allowing all programs to do so. There is a strong use case for wanting to exclude some programs with the intention of accessing local captive portals, intranets, file shares, printers etc without wanting to allow all programs on the computer to reach the LAN.

**Comment by TobyGiacometti** [comment] 2020-09-20 14:04
Indeed, being able to allow specific processes to access the LAN is a useful feature. Still, I see it as a separate feature because if tied to the split-tunneling functionality, there is no way to allow a specific process to access the LAN without giving it access to the WAN outside of the tunnel. I haven't thought much about it, but the opposite scenario might indeed be a rare occurrence. Having said all that, I certainly understand that you don't want to unnecessarily complicate things at this stage. Ultimately, time will tell as the split-tunneling functionality becomes widely used. In the meantime, it might be a good idea to make users aware of the fact that the local networking sharing preference is not considered when split-tunneling is active. Better safe than sorry.

**Comment by faern** [comment] 2020-09-21 19:53
Allowing programs to reach your LAN but not your WAN sounds out of scope for a VPN application. That's probably something you want to fix yourself in your firewall. This VPN application is not a full application firewall.

We will make sure the wording around split tunneling is clear when we release this as a feature in the GUI. Thanks.

**Closed by faern** 2020-09-21 19:53 UTC

**Comment by TobyGiacometti** [comment] 2020-09-22 10:07
> Allowing programs to reach your LAN but not your WAN sounds out of scope for a VPN application.

I agree, but maybe I was not clear enough in my communication. I was referring to following part of your reply:

> If implemented the way you describe. There would not be any way to allow only a few programs to talk to the LAN without allowing all programs to do so. There is a strong use case for wanting to exclude some programs with the intention of accessing local captive portals, intranets, file shares, printers etc without wanting to allow all programs on the computer to reach the LAN.

Currently, if using `mullvad-exclude`, said programs can access the LAN, but at the same time, these programs now operate outside of the VPN. Ultimately, I think 2 lists should exist: One for programs that must talk to the WAN directly, and one for programs that are allowed to talk to the LAN if local network sharing is disabled. Those are 2 different security domains that should also be handled separately.
