### ISSUE TITLE
[Feature request] "Included apps" in addition to "Excluded apps"

### ISSUE THREAD

**Issue by NoleSerrano** [mullvad/mullvadvpn-app#5840] opened 2024-02-21 07:16 UTC
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

It should do the same things as "Excluded apps" but inverted. The VPN should only work on the apps you include in the list, all other app traffic does not go through the VPN.

### Alternative solutions

None

### Type of feature

- [X] Better privacy/anonymity
- [ ] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [X] Android
- [X] iOS
- [X] Windows
- [X] macOS
- [X] Linux

**Comment by MrChocolatine** [comment] 2024-02-21 08:24
Sounds like a duplicate of #2808 .

**Closed** 2024-02-22 12:58 UTC
Labels: feature request

**Comment by raksooo** [comment] 2024-02-22 13:21
Closing since it's a duplicate of #2808.
