### ISSUE TITLE
Bad icon in taskbar on debian 10 Buster LXQT

### ISSUE THREAD

**Issue by mastercoldcoder** [mullvad/mullvadvpn-app#2197] opened 2020-10-20 20:03 UTC
Operating system: Debian 10 Buster. Desktop environment : LXQT
App version: 2020.6

Issue description
When I launch the application, the icon in the taskbar displays a small red padlock but when I connect to the VPN service it displays a toothed wheel instead of the small green padlock.
![Bad tray icon Mullvad](https://user-images.githubusercontent.com/61064876/96638133-faf1da00-131f-11eb-8fba-fc93a4a9ed60.png)

**Comment by faern** [comment] 2020-10-21 08:20
Thanks for reporting. But this is a duplicate of #1744

**Closed by faern** 2020-10-21 08:20 UTC
Labels: Desktop frontend
