### ISSUE TITLE
Newest beta says out of date

### ISSUE THREAD

**Issue by Technetium1** [mullvad/mullvadvpn-app#1703] opened 2020-05-04 07:18 UTC
# Issue report
Operating system: Windows 10
App version: 2020.4-beta3

### Issue description
Just updated to the newest beta and it says it is not the newest 
![image](https://user-images.githubusercontent.com/9877150/80943607-9a90cf80-8db5-11ea-9221-c1bc5fdea550.png)

**Comment by faern** [comment] 2020-05-04 07:47
Duplicate of #1697. Fixed in #1699

**Closed by faern** 2020-05-04 07:47 UTC
