### ISSUE TITLE
mullvad gui doesn't open in Fedora 35 Final

### ISSUE THREAD

**Issue by strykenKN** [mullvad/mullvadvpn-app#3079] opened 2021-11-03 01:18 UTC
the problem is unfortunately not fixed! Under Fedora 35 the GUI does not open and the app does not open in any way. and if it does open, the surface is white, you can't do anything!

Mullvad, that's not your serious now or ? What's going on with you?

Guys what is this ? It sucks and I really have no more nerve on it! 

Act finally!

**Comment by faern** [comment] 2021-11-03 08:58
We have a fix for this and we are testing a beta internally as we speak. It will hopefully be out in a few days.

We have been aware of the issue for a long time. But Ubuntu solved it last second in their release. So we somewhat hoped that Fedora would do the same. Yeah, we could have been faster indeed! But there is a known workaround, as outlined in the other issue that I link to.

I'm going to close this as a duplicate of #2992

**Closed by faern** 2021-11-03 08:58 UTC
Labels: bug, Desktop frontend
