### ISSUE TITLE
[Arch & Hyperland] Crashing due to Segmentation Fault

### ISSUE THREAD

**Issue by sinnayuh** [mullvad/mullvadvpn-app#5466] opened 2023-11-19 12:19 UTC
## Issue report

Operating system: Arch Linux
Desktop Enviroment: Hyperland w/ Sway

App version: mullvad-vpn 2023.5-1

### Issue description

Upon launching the application, as soon as i give the app focus (maximized & windowed) it just crashes due to a Segmentation Fault

### Issue Logs
Below are the logs when trying to run the app, i've listed logs with and without the --disable-gpu flag
```
❯ mullvad-vpn
[2023-11-19 12:14:26.340][verbose] Chromium sandbox is enabled
[2023-11-19 12:14:26.341][info] Running version 2023.5

(mullvad-gui:18990): Gtk-WARNING **: 12:14:26.386: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class
[2023-11-19 12:14:26.422][info] Detected locale: en-US
[2023-11-19 12:14:26.445][info] Connected to the daemon
[2023-11-19 12:14:26.468][info] Skip autoconnect because account token is not set
[19040:1119/121426.496160:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[19040:1119/121426.496246:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[19040:1119/121426.496303:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[19040:1119/121426.496324:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[19040:1119/121426.496341:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[19040:1119/121426.496356:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[19040:1119/121426.496387:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[18990:1119/121426.499959:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
[2023-11-19 12:14:26.500][error] Child process of type GPU exited with exit code 8704 due to abnormal-exit
[19074:1119/121426.572596:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[19074:1119/121426.572646:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[19074:1119/121426.572714:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[19074:1119/121426.572735:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[19074:1119/121426.572754:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[19074:1119/121426.572771:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[19074:1119/121426.572810:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[18990:1119/121426.575776:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
[2023-11-19 12:14:26.575][error] Child process of type GPU exited with exit code 8704 due to abnormal-exit
[19087:1119/121426.645487:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[19087:1119/121426.645538:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=SCANOUT
[19087:1119/121426.645602:ERROR:gbm_wrapper.cc(258)] Failed to export buffer to dma_buf: No such file or directory (2)
[19087:1119/121426.645630:ERROR:gbm_pixmap_wayland.cc(75)] Cannot create bo with format= RGBA_8888 and usage=GPU_READ
[19087:1119/121426.645647:ERROR:shared_image_factory.cc(673)] CreateSharedImage: could not create backing.
[19087:1119/121426.645663:ERROR:shared_image_factory.cc(527)] DestroySharedImage: Could not find shared image mailbox
[19087:1119/121426.645698:ERROR:gpu_service_impl.cc(1010)] Exiting GPU process because some drivers can't recover from errors. GPU process will restart shortly.
[19069:1119/121426.647245:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[18990:1119/121426.648416:ERROR:gpu_process_host.cc(954)] GPU process exited unexpectedly: exit_code=8704
[2023-11-19 12:14:26.648][error] Child process of type GPU exited with exit code 8704 due to abnormal-exit
[19069:1119/121426.683606:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[2023-11-19 12:14:26.785][error] Failed to check autostart file: ENOENT: no such file or directory, access '/home/sina/.config/autostart/mullvad-vpn.desktop'
/usr/bin/mullvad-vpn: line 2: 18990 Segmentation fault      (core dumped) "/opt/Mullvad VPN/mullvad-vpn" "$@"
```

```
❯ mullvad-vpn --disable-gpu
[2023-11-19 12:16:44.919][verbose] Chromium sandbox is enabled
[2023-11-19 12:16:44.919][info] Running version 2023.5

(mullvad-gui:20097): Gtk-WARNING **: 12:16:44.958: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class
[2023-11-19 12:16:44.993][info] Detected locale: en-US
[2023-11-19 12:16:45.010][info] Connected to the daemon
[2023-11-19 12:16:45.032][info] Skip autoconnect because account token is not set
[2023-11-19 12:16:45.186][error] Failed to check autostart file: ENOENT: no such file or directory, access '/home/sina/.config/autostart/mullvad-vpn.desktop'
/usr/bin/mullvad-vpn: line 2: 20097 Segmentation fault      (core dumped) "/opt/Mullvad VPN/mullvad-vpn" "$@"
```

**Comment by pinkisemils** [comment] 2023-11-21 08:58
Duplicate of #5075

**Closed by pinkisemils** 2023-11-21 08:58 UTC
