### ISSUE TITLE
[Bug] The Mac application stops opening when you click the icon in the menu bar

### ISSUE THREAD

**Issue by dizelgerda** [mullvad/mullvadvpn-app#4453] opened 2023-03-16 16:55 UTC
## Issue report

Operating system: macOS 13.2.1

App version: 2023.2

### Issue description

During operation (it seems, after using Zoom), the application stops opening by clicking the icon in the menu bar. Only restarting the computer helps, since Mullvad is not displayed in the panel for forcibly terminating programs.

**Comment by raksooo** [comment] 2023-03-17 09:47
Hi! Thanks for reporting! Are you using an M1/M2 or Intel mac?

**Comment by dizelgerda** [comment] 2023-03-17 10:28
I use M1.

**Comment by raksooo** [comment] 2023-03-20 09:26
Thanks for the info! We'll look into it :)

**Comment by alexanderguryev** [comment] 2023-03-23 22:18
i've also been having this issue for the past several versions on Mac M1

**Comment by dizelgerda** [comment] 2023-03-24 12:48
Today the problem was repeated and it became clear that it has nothing to do with Zoom as I wrote earlier. The worst thing is that you have to restart your computer to make everything work.

**Comment by raksooo** [comment] 2023-04-11 06:53
If you want to you can try this dev-build out to see if it fixes the issue: https://releases.mullvad.net/builds/2023.3-dev-2cc901/

The dev build hasn't gone through our internal release testing and might contain bugs and shouldn't be used other than for testing.

**Comment by raksooo** [comment] 2023-04-19 08:41
We're under the impression that the Electron upgrade fixed this. This will be included in the next beta and stable release. Please write here if the issue remains in future versions of the app.

**Closed by raksooo** 2023-04-19 08:41 UTC
Labels: bug, macOS

**Comment by dizelgerda** [comment] 2023-05-02 15:53
Version 2023.3, this bug just happened again

**Comment by dizelgerda** [comment] 2023-05-03 16:08
@raksooo

**Comment by MrChocolatine** [comment] 2023-05-03 21:00
> This will be included in the next beta and stable release.
> Please write here if the issue remains in future versions of the app.

This was written the 19 April 2023, at that time the version `2023.3` was already released (on 5 April 2023).
@dizelgerda  I think we should assume this is "normal" since there hasn't been any beta or stable release since the version `2023.3`.

**Comment by raksooo** [comment] 2023-05-04 14:35
We've now release `2023.4-beta1`. Please try it out and let us know if the issue is fixed for you: https://mullvad.net/en/download/vpn/macos#beta.

**Comment by cajhin** [comment] 2023-06-06 07:28
fyi, you can use Activity Monitor to stop all "Mullvad VPN *" processes (not the mullvad-daemon), then start Mullvad again, and you can open the GUI again.
(M2 Air, Mullvad 2023.3, MacOS 13.4)
