### ISSUE TITLE
Cannot upgrade to version 2023.3 - file conflict with Local 6.7.0

### ISSUE THREAD

**Issue by lunamode** [mullvad/mullvadvpn-app#4578] opened 2023-04-18 06:21 UTC
## Issue report

**Operating system:** Fedora Linux

**App version:** 2023.1

### Issue description

If version 6.7.0 of [Local](https://localwp.com/releases) is installed, upgrading to version 2023.3 of Mullvad VPN with `dnf install` fails with the following output:

```
Error: Transaction test error:
  file /usr/lib/.build-id/cb/dc9db5fec0e6129bddcb0c282be98be4c6966e from install of mullvad-vpn-2023.3-1.x86_64 conflicts with file from package local-6.7.0-20230315.3.x86_64
```

I assume that using `rpm --install --replacefiles` would allow me to force the install, but I'm not sure if doing this might cause other problems. Would this be safe to do, or is there another way that I might be able to install the upgrade with `dnf`?

**Comment by raksooo** [comment] 2023-04-18 07:36
Thanks for reporting! This seems to be a duplicate of https://github.com/mullvad/mullvadvpn-app/issues/4534. It has been fixed in our main branch and we're aiming to release a beta very soon.

**Closed by raksooo** 2023-04-18 07:36 UTC
