### ISSUE TITLE
Still showing "Amagicom AB" in Allow in Background on MacOS

### ISSUE THREAD

**Issue by whatyoubendoing** [mullvad/mullvadvpn-app#4494] opened 2023-03-27 14:00 UTC
## Issue report

Operating system: MacOS 13.2.1
App version: 2023.2

### Issue description

Hey there, I saw an update in the changelog that you fixed a previous issue I posted `Show "Mullvad VPN" in the Login Items UI instead of "Amagicom AB".` however I still seem to be seeing the latter.

![CleanShot 2023-03-27 at 14 54 09@2x](https://user-images.githubusercontent.com/896954/227960883-20f4e1ba-e84e-484f-9c03-07221ebb39b2.png)

**Comment by faern** [comment] 2023-03-27 14:10
I tried quickly and are not able to reproduce this. Maybe this is because the item was created with the old app? If this bothers you you can try removing the background permission and reinstall the app maybe?

**Comment by bit-blit** [comment] 2023-04-09 08:37
Hmmm.... Whenever there is a new release of Mullvad, I always TOTALLY WIPE all the old Mullvad files in my home directory, and the root Library and System folders. Then I install clean. I'm not saying it will work, but it is worth the 15min that it takes to try it. Mine looks fine - just a suggestion.

**Comment by bit-blit** [comment] 2023-04-12 05:34
@Ben2HellAndBack:

I do a manual removal of all files just using Finder. There may still be some stray files however, due to the fact that I  don't set the finder to show all hidden files as well - next release I'm going to do that and see if there is anything that I have been missing.

**Comment by faern** [comment] 2023-04-12 08:09
If you just remove stuff with finder you will likely miss files. On macOS you are supposed to run `/Applications/Mullvad\ VPN.app/Contents/Resources/uninstall.sh` from a terminal. That will ask you some questions, and wipe everything if you answer yes.

**Comment by bit-blit** [comment] 2023-04-12 20:32
Many Thanks for the help!

Best Regards...

**Comment by johnaaron-git** [comment] 2023-06-22 12:52
I'm also seeing this with a fresh Mac install via Brew.sh

**Comment by hulthe** [comment] 2024-11-26 16:13
Closing since the fix has been out since v2023.4. If anyone is still experiencing this with a newer version, try uninstalling using [`uninstall.sh`](https://mullvad.net/en/help/install-and-use-mullvad-app-macos#uninstall) and reinstalling.

**Closed by hulthe** 2024-11-26 16:13 UTC
Labels: macOS
