### ISSUE TITLE
Mullvad Android App not running after device reboot

### ISSUE THREAD

**Issue by wanam** [mullvad/mullvadvpn-app#2028] opened 2020-08-26 10:58 UTC
## Issue report

Operating system: Android 10 Stock OnePlus (Oxygen) Rom

App version: 2020.6.beta1

### Issue description

I'm expecting Mullvad app to run after rebooting my device, I setup a scheduled power Off/On for my Android device during the night, but I need to start the app manually each time my device reboot.

Battery optimization disabled for the app.
Taking a look at the logcat I notice an app crash:

```
08-26 12:45:50.678  1596  1627 I ActivityManager: Start proc 4756:net.mullvad.mullvadvpn/u0a381 for service {net.mullvad.mullvadvpn/net.mullvad.mullvadvpn.service.MullvadVpnService}
.........................
08-26 12:45:50.698  4756  4756 E lvad.mullvadvp: Not starting debugger since process cannot load the jdwp agent.
.........................
08-26 12:45:50.819  4756  4756 E lvad.mullvadvp: No implementation found for net.mullvad.talpid.tun_provider.TunConfig net.mullvad.talpid.TalpidVpnService.defaultTunConfig() (tried Java_net_mullvad_talpid_TalpidVpnService_defaultTunConfig and Java_net_mullvad_talpid_TalpidVpnService_defaultTunConfig__)
08-26 12:45:50.819  4756  4756 D AndroidRuntime: Shutting down VM
08-26 12:45:50.819  1596  2298 D OnePlusSmartBoostManager: writeHotCount com.soundcloud.android, pid=4805
08-26 12:45:50.819  4756  4756 E AndroidRuntime: FATAL EXCEPTION: main
08-26 12:45:50.819  4756  4756 E AndroidRuntime: Process: net.mullvad.mullvadvpn, PID: 4756
08-26 12:45:50.819  4756  4756 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for net.mullvad.talpid.tun_provider.TunConfig net.mullvad.talpid.TalpidVpnService.defaultTunConfig() (tried Java_net_mullvad_talpid_TalpidVpnService_defaultTunConfig and Java_net_mullvad_talpid_TalpidVpnService_defaultTunConfig__)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at net.mullvad.talpid.TalpidVpnService.defaultTunConfig(Native Method)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at net.mullvad.talpid.TalpidVpnService.<init>(TalpidVpnService.kt:18)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at net.mullvad.mullvadvpn.service.MullvadVpnService.<init>(MullvadVpnService.kt:25)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at android.support.v4.app.CoreComponentFactory.instantiateService(CoreComponentFactory.java:68)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4058)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at android.app.ActivityThread.access$1800(ActivityThread.java:236)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1985)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:219)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7709)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
08-26 12:45:50.819  4756  4756 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

```

Let me know if you need more details.

**Comment by jvff** [comment] 2020-08-26 11:39
Hello and thanks for the report! This is caused by the app trying to call native JNI methods before the JNI library is loaded. We've just fixed this in #2015, and we should be able to release a new version soon fixing the issue.

Thanks again!

**Comment by eXmendiC** [comment] 2020-08-27 17:03
Just a short question, because I wanted to adress this issue as well.
Isn't there still a short period of time between the installing and restarting process if I update it? That would mean the real IP adress is still leaked (even if the interval is short) if there is no app to force a kill switch anymore, or am I wrong?

**Comment by wanam** [comment] 2020-08-27 17:40
I second this question, and does setting "Always-on VPN" to ON prevent from such leak if exists.

**Comment by faern** [comment] 2020-08-28 09:29
In the Android settings, right next to "Always-on VPN" you should have the setting "Block connections without VPN". You can activate this in order for Android to block any non-VPN packets.

**Comment by eXmendiC** [comment] 2020-08-28 16:05
Thanks for the hint. 
Maybe an option to do it (like the "always require VPN" option inside the PC software) or a shortcut (opening the settings option on Android) inside the app still might be useful for other users. I for example, didn't know Android had such an option.

**Comment by faern** [comment] 2020-08-31 08:53
Version `2020.6-beta2` of the app has been released. It should fix the original issue here. So I'm closing this ticket.

**Closed by faern** 2020-08-31 08:53 UTC
