### ISSUE TITLE
[Feature request] Multihop Wireguard Option in Desktop

### ISSUE THREAD

**Issue by 3aswar** [mullvad/mullvadvpn-app#2412] opened 2021-01-22 16:29 UTC
Hello,

Could we consider adding a multihop wireguard option in desktop client ? Right now the only way to achieve it is by using the Wireguard client with a manually generated config, as bridge mode in desktop always falls back to OpenVPN.

Thank you

**Comment by faern** [comment] 2021-01-25 08:50
Thanks for interest in the feature. But going to close this as a duplicate of #1487.

This is still something we want to implement. But we have no estimated time when it will be ready yet.

**Closed by faern** 2021-01-25 08:50 UTC
