### ISSUE TITLE
Internet is blocked after sleep on Linux

### ISSUE THREAD

**Issue by sith-on-mars** [mullvad/mullvadvpn-app#2486] opened 2021-02-17 15:00 UTC
## Issue report

Operating system: OpenSUSE Tumbleweed Gnome

App version: 2021.1, 2021.2

### Issue description

After waking up my system from sleep the internet is blocked after the 2021.1 update, no matter if I turn "always requires VPN" on or off. Even though the internet is blocked, my system still shows the VPN connection is on. I can restore the internet connection by reconnecting the VPN.

**Comment by pinkisemils** [comment] 2021-02-17 18:44
If you have NetworkManager installed (which you should, if you're using gnome), hat's the output of `nmcli --version`?
And, when you've come out of suspension, if you experience this loss of connectivity, can you ping our gateway, which would be `ping 10.64.0.1` for WireGuard and for OpenVPN the gateway can be different depending on which relay you connect to, but it can be deduced by looking at the routing table.
My bet is that NM is resetting your DNS config when coming out of sleep. This is a NetworkManager bug that has been fixed upstream. You can workaround this bug by forcing a specific DNS management mode - a static file would be the best fix until NM is fixed. To help us with deducing what's actually broken, you should send a problem report with all the logs.

**Comment by sith-on-mars** [comment] 2021-02-18 06:24
Thanks for the reply. I believe the issue is caused by the 2021.1 update rather than NetworkManager. My VPN didn't have this issue until I updated to 2021.1. I also didn't update my system before the 2021.1 update. Nevertheless, I will provide you the outputs you asked:

Output of `nmcli --version`: 
`nmcli tool, version 1.28.0`

I use WireGuard and this is the output of 'ping 10.64.0.1' when the connection is lost after waking up :
`PING 10.64.0.1 (10.64.0.1) 56(84) bytes of data.
64 bytes from 10.64.0.1: icmp_seq=1 ttl=64 time=6.82 ms
64 bytes from 10.64.0.1: icmp_seq=2 ttl=64 time=6.17 ms
64 bytes from 10.64.0.1: icmp_seq=3 ttl=64 time=6.74 ms
64 bytes from 10.64.0.1: icmp_seq=4 ttl=64 time=6.40 ms
64 bytes from 10.64.0.1: icmp_seq=5 ttl=64 time=6.55 ms
64 bytes from 10.64.0.1: icmp_seq=6 ttl=64 time=6.20 ms
64 bytes from 10.64.0.1: icmp_seq=7 ttl=64 time=6.36 ms
64 bytes from 10.64.0.1: icmp_seq=8 ttl=64 time=6.28 ms
64 bytes from 10.64.0.1: icmp_seq=9 ttl=64 time=6.40 ms
64 bytes from 10.64.0.1: icmp_seq=10 ttl=64 time=6.58 ms
64 bytes from 10.64.0.1: icmp_seq=11 ttl=64 time=6.87 ms
64 bytes from 10.64.0.1: icmp_seq=12 ttl=64 time=8.04 ms
64 bytes from 10.64.0.1: icmp_seq=13 ttl=64 time=6.48 ms
64 bytes from 10.64.0.1: icmp_seq=14 ttl=64 time=6.17 ms
64 bytes from 10.64.0.1: icmp_seq=15 ttl=64 time=7.02 ms
64 bytes from 10.64.0.1: icmp_seq=16 ttl=64 time=5.43 ms
64 bytes from 10.64.0.1: icmp_seq=17 ttl=64 time=5.78 ms
64 bytes from 10.64.0.1: icmp_seq=18 ttl=64 time=5.62 ms
64 bytes from 10.64.0.1: icmp_seq=19 ttl=64 time=6.99 ms
64 bytes from 10.64.0.1: icmp_seq=20 ttl=64 time=5.77 ms
64 bytes from 10.64.0.1: icmp_seq=21 ttl=64 time=5.67 ms
64 bytes from 10.64.0.1: icmp_seq=22 ttl=64 time=5.29 ms
64 bytes from 10.64.0.1: icmp_seq=23 ttl=64 time=5.61 ms
64 bytes from 10.64.0.1: icmp_seq=24 ttl=64 time=5.50 ms
64 bytes from 10.64.0.1: icmp_seq=25 ttl=64 time=6.38 ms
64 bytes from 10.64.0.1: icmp_seq=26 ttl=64 time=6.52 ms
64 bytes from 10.64.0.1: icmp_seq=27 ttl=64 time=6.70 ms
64 bytes from 10.64.0.1: icmp_seq=28 ttl=64 time=6.10 ms
64 bytes from 10.64.0.1: icmp_seq=29 ttl=64 time=6.57 ms
64 bytes from 10.64.0.1: icmp_seq=30 ttl=64 time=6.46 ms
64 bytes from 10.64.0.1: icmp_seq=31 ttl=64 time=6.43 ms
64 bytes from 10.64.0.1: icmp_seq=32 ttl=64 time=8.14 ms
64 bytes from 10.64.0.1: icmp_seq=33 ttl=64 time=6.42 ms
64 bytes from 10.64.0.1: icmp_seq=34 ttl=64 time=6.26 ms
64 bytes from 10.64.0.1: icmp_seq=35 ttl=64 time=10.5 ms
64 bytes from 10.64.0.1: icmp_seq=36 ttl=64 time=6.46 ms
64 bytes from 10.64.0.1: icmp_seq=37 ttl=64 time=6.29 ms
64 bytes from 10.64.0.1: icmp_seq=38 ttl=64 time=6.17 ms
64 bytes from 10.64.0.1: icmp_seq=39 ttl=64 time=86.2 ms
64 bytes from 10.64.0.1: icmp_seq=40 ttl=64 time=28.1 ms
64 bytes from 10.64.0.1: icmp_seq=41 ttl=64 time=6.90 ms
64 bytes from 10.64.0.1: icmp_seq=42 ttl=64 time=5.83 ms
64 bytes from 10.64.0.1: icmp_seq=43 ttl=64 time=6.16 ms
64 bytes from 10.64.0.1: icmp_seq=44 ttl=64 time=6.44 ms
64 bytes from 10.64.0.1: icmp_seq=45 ttl=64 time=6.57 ms
64 bytes from 10.64.0.1: icmp_seq=46 ttl=64 time=55.0 ms
64 bytes from 10.64.0.1: icmp_seq=47 ttl=64 time=6.73 ms
64 bytes from 10.64.0.1: icmp_seq=48 ttl=64 time=6.24 ms
64 bytes from 10.64.0.1: icmp_seq=49 ttl=64 time=13.7 ms
64 bytes from 10.64.0.1: icmp_seq=50 ttl=64 time=6.31 ms
64 bytes from 10.64.0.1: icmp_seq=51 ttl=64 time=6.55 ms
64 bytes from 10.64.0.1: icmp_seq=52 ttl=64 time=6.21 ms
64 bytes from 10.64.0.1: icmp_seq=53 ttl=64 time=6.79 ms
64 bytes from 10.64.0.1: icmp_seq=54 ttl=64 time=63.2 ms
64 bytes from 10.64.0.1: icmp_seq=55 ttl=64 time=37.9 ms
64 bytes from 10.64.0.1: icmp_seq=56 ttl=64 time=28.5 ms
64 bytes from 10.64.0.1: icmp_seq=57 ttl=64 time=6.79 ms
64 bytes from 10.64.0.1: icmp_seq=58 ttl=64 time=6.23 ms
64 bytes from 10.64.0.1: icmp_seq=59 ttl=64 time=34.0 ms
64 bytes from 10.64.0.1: icmp_seq=60 ttl=64 time=67.7 ms
64 bytes from 10.64.0.1: icmp_seq=61 ttl=64 time=22.7 ms
64 bytes from 10.64.0.1: icmp_seq=62 ttl=64 time=85.0 ms
64 bytes from 10.64.0.1: icmp_seq=63 ttl=64 time=71.9 ms
64 bytes from 10.64.0.1: icmp_seq=64 ttl=64 time=6.08 ms
64 bytes from 10.64.0.1: icmp_seq=65 ttl=64 time=6.29 ms
64 bytes from 10.64.0.1: icmp_seq=66 ttl=64 time=6.34 ms
64 bytes from 10.64.0.1: icmp_seq=67 ttl=64 time=6.21 ms
64 bytes from 10.64.0.1: icmp_seq=68 ttl=64 time=6.53 ms
64 bytes from 10.64.0.1: icmp_seq=69 ttl=64 time=6.98 ms
64 bytes from 10.64.0.1: icmp_seq=70 ttl=64 time=5.56 ms
64 bytes from 10.64.0.1: icmp_seq=71 ttl=64 time=6.51 ms
64 bytes from 10.64.0.1: icmp_seq=72 ttl=64 time=7.43 ms
64 bytes from 10.64.0.1: icmp_seq=73 ttl=64 time=7.28 ms
64 bytes from 10.64.0.1: icmp_seq=74 ttl=64 time=5.21 ms
64 bytes from 10.64.0.1: icmp_seq=75 ttl=64 time=5.55 ms
64 bytes from 10.64.0.1: icmp_seq=76 ttl=64 time=5.49 ms
64 bytes from 10.64.0.1: icmp_seq=77 ttl=64 time=5.60 ms
64 bytes from 10.64.0.1: icmp_seq=78 ttl=64 time=5.41 ms
64 bytes from 10.64.0.1: icmp_seq=79 ttl=64 time=5.50 ms
64 bytes from 10.64.0.1: icmp_seq=80 ttl=64 time=5.42 ms
64 bytes from 10.64.0.1: icmp_seq=81 ttl=64 time=6.05 ms
64 bytes from 10.64.0.1: icmp_seq=82 ttl=64 time=6.23 ms
64 bytes from 10.64.0.1: icmp_seq=83 ttl=64 time=6.53 ms
64 bytes from 10.64.0.1: icmp_seq=84 ttl=64 time=6.39 ms
64 bytes from 10.64.0.1: icmp_seq=85 ttl=64 time=6.46 ms
64 bytes from 10.64.0.1: icmp_seq=86 ttl=64 time=6.55 ms
64 bytes from 10.64.0.1: icmp_seq=87 ttl=64 time=6.13 ms
64 bytes from 10.64.0.1: icmp_seq=88 ttl=64 time=6.53 ms
64 bytes from 10.64.0.1: icmp_seq=89 ttl=64 time=6.33 ms
64 bytes from 10.64.0.1: icmp_seq=90 ttl=64 time=16.6 ms
64 bytes from 10.64.0.1: icmp_seq=91 ttl=64 time=6.55 ms
^C
--- 10.64.0.1 ping statistics ---
91 packets transmitted, 91 received, 0% packet loss, time 90145ms
rtt min/avg/max/mdev = 5.214/12.171/86.208/17.012 ms`

Please let me know if you need more logs.

**Comment by pinkisemils** [comment] 2021-02-18 09:59
Thanks for the output - it seems that only DNS is not working. This is kind of a known issue and we're thinking about what's the best way to fix it (but it's most likely an NM bug). Would you mind sending in a problem report through the app? I'll get the daemon logs that way and I'll be able to see which DNS management method you are using. 

After that, you can apply [this](https://github.com/mullvad/mullvadvpn-app/issues/2339#issuecomment-741846765) workaround  in the mean time, that should fix your issues.

**Comment by pinkisemils** [comment] 2021-02-18 13:14
Given that OpenSUSE seems to be using `netconfig` to manage DNS, it will most definitely not work nicely with our daemon, so you'll probably have to use the workaround until we can support OpenSUSE properly.

**Comment by sith-on-mars** [comment] 2021-02-20 07:18
I've sent the problem report yesterday. Today I updated Mullvad to 2021.2, the bug is still there.

**Comment by jacksongoode** [comment] 2021-02-20 23:36
Second this, Ubuntu 20.10. Will send in report as well.

**Comment by pinkisemils** [comment] 2021-02-20 23:50
Nothing's changed for this bug in 2021.2. 

On Ubuntu 20.10, the issue is that NetworkManager will wipe the systemd-resolved's config for any interface that NM doesn't have a config for. Our daemon configures DNS via systemd-resolved, thus it should be used instead. I'm currently working on a fix for this, it will definitely be included in the next release. You can also try and get Ubuntu developers to apply the upstream patch for this by voicing your issues [here](https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1915153). 
With OpenSUSE, we'll have to look into adding support for `netconfig`, as that is the tool that is overwriting the DNS config we need.

**Comment by jacksongoode** [comment] 2021-02-25 05:28
> Nothing's changed for this bug in 2021.2.
> 
> On Ubuntu 20.10, the issue is that NetworkManager will wipe the systemd-resolved's config for any interface that NM doesn't have a config for. Our daemon configures DNS via systemd-resolved, thus it should be used instead. I'm currently working on a fix for this, it will definitely be included in the next release. You can also try and get Ubuntu developers to apply the upstream patch for this by voicing your issues [here](https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/1915153).
> With OpenSUSE, we'll have to look into adding support for `netconfig`, as that is the tool that is overwriting the DNS config we need.

Is there any workaround for this issue on Ubuntu for now? I tried the workaround you mentioned on Fedora with no success.

**Closed** 2021-03-02 11:46 UTC

**Comment by jacksongoode** [comment] 2021-04-13 18:49
Appears fixed in the latest beta (2021.3-beta1)!
