### ISSUE TITLE
High CPU use by configd process with macOS client connected

### ISSUE THREAD

**Issue by paulrudy** [mullvad/mullvadvpn-app#3400] opened 2022-03-05 20:54 UTC
## Issue report

Operating system: MacOS Monterey 12.2

App version: 2022.1

### Issue description

When the Mullvad client is connected, I see the configd process running at 100-110% CPU in Activity Monitor.
When I disconnect, configd returns to 1-2%
Leaving the client connected but changing settings for blocking ads, trackers, and malware has no effect.

**Comment by paulrudy** [comment] 2022-03-06 18:44
Issue seems to have disappeared after rebooting in Safe Mode (M1 Macbook Air)

**Comment by paulrudy** [comment] 2022-03-06 19:14
I spoke too soon. The issue has reoccurred.

**Comment by pinkisemils** [comment] 2022-03-07 11:27
I can only notice some spikes, Are you by any chance running some other software that is trying to configure your DNS configuration? Did this happen with a previous version too?
The daemon is attempting to listen for changes to your system's DNS configuration and reapply the configuration it needs constantly, and if there's another actor in the system trying to do the same thing, the high CPU load would probably be the end result. We have some plans of changing this behavior in some circumstances (when you'd be using resolves on your local network), but we've not come around to that just yet.

**Comment by paulrudy** [comment] 2022-03-11 18:23
Hi, thanks for checking. I don't have any software that configures DNS. I have iCloud+ Private Relay turned off. I can't recall that it was a problem before the current version, but I also don't think I checked before.

**Comment by paulrudy** [comment] 2022-03-13 00:34
Ok, there may be a connection between this behavior and something about iCloud Private Relay. When configd is using a lot of CPU, if I go to System Preferences > Apple ID > iCloud, the entry for Private Relay shows a spinning progress icon in place of the "Options" button, and no checkbox. It often doesn't stop spinning until I disable the Mullvad VPN. Once I disable the VPN, then Private Relay resolves to an unchecked checkbox and I see the "Options" button. So even though I have Private Relay disabled, perhaps something about MacOS is attempting to check a setting related to Private Relay, and can't complete it with the VPN enabled? Or perhaps there is no relationship.

I tried signing out of iCloud and signing in again. I also tried installing [this configuration profile that disables Private Relay](https://www.macblog.org/posts/how-to-disable-icloud-private-relay/). The problem persisted anyway.

**Comment by pinkisemils** [comment] 2022-03-14 11:45
Thanks, this is very valuable information as far as debugging this goes. It does seem like there's a fight going on between our daemon and some other piece of software, each trying to force a different DNS configuration.

**Comment by dgm34** [comment] 2022-03-14 11:58
For what it's worth I have exactly the same issue, including the iCloud settings entry for Private Relay showing a spinning progress icon in place of the "Options" button and no checkbox. 

I am quite sure I don't have any macOS software specifically interfering with DNS however my router, an AmpliFi system, is configured to use Cloudflare's DNS so I wonder if this is causing an issue with the daemon, perhaps with macOS constantly hearing from the router that the DNS lookups should be to 1.1.1.1 and then the Mullvad daemon listening for changes and undoing it etc. 

I'd be happy to try and help debug?

**Comment by mohamednazmi** [comment] 2022-03-15 13:41
I'm having this issue as well. I am running the NextDNS client concurrently, but even after turning it off and quitting the NextDNS app, the Mullvad app still attempts set something at a rate of 20 per second. I'm running Mullvad v 2022.1 on Big Sur.

`*** Non-configd process (pid=74) attempting to set "Setup:/Network/Service/E97B9F93-EBB3-40B6-8674-4195A9E04A47/DNS" ***`

**Comment by mohamednazmi** [comment] 2022-03-15 14:37
@faern configd was using a lot of CPU, and in fact airportd was as well.

**Comment by pinkisemils** [comment] 2022-03-16 11:01
@mohamednazmi can you try uninstalling NextDNS? It's still a bug, but it's important to deduce if it happens even if our app is the only one managing DNS on a given machine. Could you verify when this happens which PIDs belong to which applications from the logs? You should be able to use `pidof $PID` to see which application is setting the DNS config, and `pidof` can be installed via brew.

I've upgraded my machine to Monterey, and have tested out the private relay, and it seems to work well - the private relay disables itself when our app is installed, and can only be re-enabled if our app is uninstalled. This behavior is not ideal, ideally just not being connected via our app should be sufficient to use the private relay. However, I haven't been able to reproduce this issue. 

Regardless of reproduction of the bug, I will look at debouncing the DNS config changes and detecting if there's a conflict going on if there's more than 10 DNS config changes in a given second and just error out the client. I can't imagine that DNS is actually working whilst our daemon is fighting with some other DNS configurator, so ending up in the error state will at least stop pegging the CPU.

**Comment by dgm34** [comment] 2022-03-16 11:05
Apologies for interjecting but for the avoidance of doubt this issue happens on my machine _even though I have never enabled private relay_. So it's very weird I get the spinning progress icon in the private relay settings.

**Comment by mohamednazmi** [comment] 2022-03-16 11:22
@pinkisemils I'll do that for the next 24 hours and report any anomalies, though I'm not expecting the CPU spikes anymore since they're not fighting over who gets to replace the DNS (for additional reference, between then and a few minutes ago I had restarted the machine and installed the Wireguard app to use concurrently with NextDNS, and the CPU has settled down).

**Comment by pinkisemils** [comment] 2022-03-16 12:15
@dgm34 Apologies if my previous message implied doubts about these reports. I don't doubt mullvad's client has issues here, I'm just trying to figure out the best way to reproduce the issue. 


I do wonder, if this is something that only happens in `2022.1` or has this happened before, with earlier versions of our client?

**Comment by dgm34** [comment] 2022-03-16 12:17
@pinkisemils No worries! And I think I can help with that  - I reverted to the previous client (`2021.6`) a few days ago and it's totally fine. I think it's something introduced in `2022.1` 👍

**Comment by mohamednazmi** [comment] 2022-03-19 01:58
@pinkisemils it's been more than 24 hours with no CPU spikes.

**Comment by mohamednazmi** [comment] 2022-03-21 10:04
That's right, when running without the NextDNS client.

**Comment by paulrudy** [comment] 2022-03-21 15:12
I'm continuing to get high CPU with the configd process. I don't use NextDNS

**Comment by eytanhanig** [comment] 2022-04-15 20:08
Has there been any progress on this? I use Big Sur, which does not offer iCloud Private Relay, and have never used NextDNS.

I've also confirmed that this issue does **not** occur when I instead [use Viscosity with the Mullvad config files](https://mullvad.net/en/help/viscosity-macos/).

@pinkisemils Are there any commands that we can run to help diagnose this or otherwise provide you config information to help with reproducing the issue?

**Comment by pinkisemils** [comment] 2022-04-19 13:00
@eytanhanig I can only suggest you try and see if there's any process that might be changing the DNS configuration, possibly by looking at the Console app, but these efforts have been futile before. 

I have made some changes that should hopefully resolve the issue and in the worst case it will at least fix the CPU usage. I can produce a build with my changes if anyone here would be willing to test it out. Unfortunately I haven't been able to reproduce the issue.

**Comment by pinkisemils** [comment] 2022-04-20 21:37
For the more adventurous of you, there's a test [build](https://releases.mullvad.net/builds/2022.1-dev-6ef700/MullvadVPN-2022.1-dev-6ef700.pkg) (and it's [signature](https://releases.mullvad.net/builds/2022.1-dev-6ef700/MullvadVPN-2022.1-dev-6ef700.pkg.asc)). It will definitely solve the issue with CPU usage, but it might also force the client to enter the error state - if this occurs, please do check the output of `scutil --dns` to get a hint as to what might be attempting to change the DNS config.

**Comment by pinkisemils** [comment] 2022-05-17 13:05
The recently released beta also contains fixes for this bug, please do report back if this isn't fixed.

**Comment by ndw** [comment] 2022-05-24 08:48
I was having the high CPU utilization issues reported in this thread (but not the icloud spinning ball), so I grabbed the build above. "Unable to set system DNS server, please contact support." I'll send the output of `scutil --dns` to support.

**Comment by pinkisemils** [comment] 2022-05-24 11:53
Are you running any other network-related software that might be trying to apply network settings? It doesn't seem like config that is being applied is special in any way.

**Comment by ndw** [comment] 2022-05-24 14:13
Emīls Piņķis ***@***.***> writes:
> Are you running any other network-related software that might be
> trying to apply network settings? It doesn't seem like config that is
> being applied is special in any way.

Not that I’m aware of. I’ll do some experiments. Disabling antivirus
didn’t have any effect. I’ll try rebooting in a cleaner environment and
seeing what I see.

                                        Be seeing you,
                                          norm

--
Norman Tovey-Walsh ***@***.***>
https://nwalsh.com/

> He who seeks happiness for himself by making others unhappy is bound in
> the chains of hate and from those he cannot be free.--The Dhammapada

**Comment by dgm34** [comment] 2022-05-24 18:53
I experience exactly the same behaviour as @ndw. I'm pretty confident I am running no other software that's messing with network settings.

**Comment by dgm34** [comment] 2022-06-04 20:26
I was having the same issue as @ndw and I was convinced I didn't have anything on my Mac interfering with DNS. However I am running an Ubiquiti AmpliFi setup and there is an option to ["_Bypass DNS cache"_](https://help.amplifi.com/hc/en-us/articles/360015273534-Troubleshooting-DNS-Issues) that was previously unchecked (and I think it's disabled by default.)

<img width="566" alt="Screenshot 2022-06-04 at 21 18 41" src="https://user-images.githubusercontent.com/7823438/172024374-276d4d6f-f826-4afc-a45a-33609a3a875a.png">

Now that I have ticked this box and am bypassing the AmpliFi DNS cache I am no longer getting the _"Unable to set system DNS server, please contact support."_ error message. I'm not sure if this is a situation that the Mullvad devs can do anything about (as I'd like untick that checkbox) but until 2022.1 everything worked perfectly, so I hope so ...

**Comment by pinkisemils** [comment] 2022-06-07 11:21
The issue with the way it worked before was that there were a lot of users who had something reconfigure DNS whilst a tunnel was connected - and this can and will break DNS configs, since our app will block DNS traffic to anything that isn't part of the resolvers the client believes should be set. We have some ideas for mitigating this, but unless the resolver config is a local address, this is will not work. 

May I ask, if you use 2021.6 and you enable the _Bypass DNS cache_ option in Amplifi, does DNS work when our client is connected? One way to bypass this would be to use the same resolver as the one that AmpliFi is using as a custom resolver. This can be set in the advanced settings screen of the app.

**Comment by IntrepidToad** [comment] 2022-06-10 08:10
I was experiencing this issue too, and I managed to fix it by disabling Wi-Fi calling.  In the console I noticed commcenter was trying to make cellular connections right before configd started reaching high CPU usage, so I disabled Wi-Fi calling in FaceTime settings as it was the only cellular-related software I could think of on my Mac.  I found you can re-enable calls from iPhone, just don't click upgrade to Wi-Fi calling.  I hope this is of use to someone.

**Comment by pinkisemils** [comment] 2022-06-15 15:21
@dgm34 sorry, just to get this absolutely straight, changing the configuration of your router can induce bad behavior in our client? Or is there any Ubiquiti software running on your macOS machine?

**Comment by dgm34** [comment] 2022-06-17 18:39
> @dgm34 sorry, just to get this absolutely straight, changing the configuration of your router can induce bad behavior in our client? Or is there any Ubiquiti software running on your macOS machine?

There is no Ubiquiti software on my laptop.

However, interestingly, I am now unable to reproduce this on any version of the client (including the recently released 2022.2) which is a bit baffling. I'm now starting to wonder where it was the AmpliFi router that was somehow inducing this undesirable behaviour in the Mullvad macOS client 🤷‍♂️

**Comment by pinkisemils** [comment] 2022-06-20 12:04
Oh well, such is the nature of DNS bugs, it seems. Thank you very much for the responses so far.

**Comment by dmattera** [comment] 2022-07-31 18:42
Just wanted to chime here with some strange behavior I saw here.

I'm running 2022.1 on Catalina (10.15.7) and was experiencing the same behavior as OP but have never had Private relay setup and don't have any other apps that could potentially be messing with DNS settings. 

After reading through this thread I wanted to check and see what custom DNS addresses I had set in System Prefs > Network > Advanced > DNS.  I have my Networks settings set so that you need to enter an admin password in order make any changes under that Advanced menu. As soon as I entered my password I immediately saw configd's CPU usage drop from around 105% down to 0% (I had Activity Monitor open right next the the Sys Prefs window) and have not seen it go up since (going on a few hours now).

Just found this to be very strange and wanted to share in case it helps debug this at all.

**Comment by pinkisemils** [comment] 2022-08-03 07:48
Does unlocking the DNS settings fix this forever, or does it only fix it for one boot? I presume you've not tested this out with the newer versions of the app. 

I have to apologize for the lack of updates on this issue, the only potential solution we currently have is heavy-handed and would require a lot of work to do, and, until that work is done, there's no way to know if it would fix this issue. To add to the frustration, none of the developers have actually reproduced the issue on our machines.

**Comment by dmattera** [comment] 2022-08-04 12:38
It only lasted about a day or so (no reboots, just a few hours of "sleep") before it started happening again even though nothing network related had changed (still on my same home network, Mullvad was on and active the whole time).

After that reoccurence I updated to the latest beta 2022.3-beta3 and, upon first running Mullvad, got the "Unable to set system DNS" error message. I then rebooted and haven't seen that error message since (I think going on 3 days now) so fingers crossed it remains!

**Comment by ndw** [comment] 2022-08-30 08:05
When this problem started, I gave up on using Mullvad VPN on my laptop. A week or two ago, I decided to try again. The problem appears to have gone away under Monterey 12.5.1 with Mullvad 2022.1-dev-6ef700.

**Comment by SkinyMonkey** [comment] 2022-12-28 20:13
Same pb here, Macos Big Sur 11.6.4, Mullvad 2022.5
I'll try to update to Monterey soon and report here

**Comment by jrabinow** [comment] 2023-05-07 00:17
I can confirm this is happening on mac Monterey with latest client release. This seems to be related to battery charge/power management for some reason: I was running on battery without mullvad. I activated mullvad and almost immediately, configd spiked. This never happens if my laptop is plugged into power. It's also worth nothing It's harder to repro if battery %age is above a certain level.

The best reference I can find is https://forums.macrumors.com/threads/macbookpro-mid-2015-mds_stores-or-configd-cpu-high-load.2380126/. Other things I've correlated with this issue: lack of free RAM and chrome/electron usage. I typically run a number of apps based off of electron that start acting up as soon as I try to interact with any of them. I end up having to force quit them and mullvad quite often because of this.

Is there any chance of including the test build fix into the official release? Anything I can do to help here, I will do, I'm quite close to wiping my hard drive and installing linux.

**Comment by jrabinow** [comment] 2023-05-07 00:51
I can confirm this is happening on mac Monterey with latest client release. This seems to be related to battery charge/power management for some reason: I was running on battery without mullvad. I activated mullvad and almost immediately, configd spiked. This never happens if my laptop is plugged into power. It's also worth nothing It's harder to repro if battery %age is above a certain level.

The best reference I can find is https://forums.macrumors.com/threads/macbookpro-mid-2015-mds_stores-or-configd-cpu-high-load.2380126/. Other things I've correlated with this issue: lack of free RAM and chrome/electron usage. I typically run a number of apps based off of electron that start acting up as soon as I try to interact with any of them. I end up having to force quit them and mullvad quite often because of this. Only apps either using electron/chrome, or using significant RAM ever have issues.

Is there any chance of including the test build fix into the official release? Anything I can do to help here, I will do, I'm quite close to wiping my hard drive and installing linux.

The daemon itself doesn't seem to have issues as far as i can tell. Maybe the workaround for the time being is to run mullvad from the command-line and disable the gui?

**Comment by jrabinow** [comment] 2023-05-18 23:08
@faern Sorry for the late response. It's happening whether or not the GUI is running. I'm afraid my laptop gave up the ghost before I could isolate the issue any further.
My best guess would be something related to wifi and power management. This might potentially be triggered by mullvad but I think the best way forward would be to isolate the issue as the more I look at my issue, the more I wonder if there isn't a bug in the Mac OS operating system that is being triggered externally.

This could be done (by someone for whom this is happening on a regular basis) by checking whether the bug occurs when running:
- plugged into a power cord vs not
- with and without chrome or any electron app, including mullvad GUI.
- on ethernet vs on wifi
If configd still runs hot over ethernet, while charging and without chrome or electron (including mullvad GUI), then it's most likely a mullvad daemon software issue. If not, then I'd be curious if this issue could be isolated to any other software.

**Comment by MarkusPettersson98** [comment] 2024-11-27 15:24
Hello everyone, sorry for necrobumping but does anyone still experience this? Otherwise I'll go ahead and close this issue :blush:

**Comment by MarkusPettersson98** [comment] 2024-11-27 15:47
Closing this then. If someone else is still experiencing this, please comment and we'll open it again :blush:

**Closed by MarkusPettersson98** 2024-11-27 15:47 UTC
Labels: bug, macOS
