### ISSUE TITLE
Port options 

### ISSUE THREAD

**Issue by macducknut** [mullvad/mullvadvpn-app#500] opened 2018-10-05 16:35 UTC
Hi are there a Way to add a Open port or is it not inplamented yet?

**Comment by faern** [comment] 2018-10-08 07:33
Do you mean to forward ports from your exit address to your computer in the tunnel? Those are configured on your account page on mullvad.net
https://mullvad.net/en/guides/port-forwarding-and-mullvad/

**Comment by macducknut** [comment] 2018-10-08 11:12
Okej becuse when i start the New app the port att a configured on the website dosnt work when i start the app

**Comment by faern** [comment] 2018-10-08 12:30
Which operating system are you running, and which version of that operating system? And which version of the app?

**Comment by macducknut** [comment] 2018-10-08 12:34
Ubuntu 16.04.05

**Comment by macducknut** [comment] 2018-10-08 12:37
Mullvad 2018.4-beta1 its the only version that have worked for me so far i have had trubble connecting and connecting loop bit now in this beta its fixed but the port wont open

**Comment by faern** [comment] 2018-10-11 08:29
It works for me. Try the following:
1. Add a port to your Mullvad account. Let's denote the port `<port>` from here on.
2. Run the Mullvad app and connect to a relay.
3. Go to https://am.i.mullvad.net on the computer where the app runs, and take note of your public IP, shown under the "Connection" box. Let's call it `<exit ip>` from here.
4. Start a terminal on the computer where the app runs and run `nc -l -p <port>`. This will listen on your port and sit and wait for connections.
5. Preferably on a second computer with Linux, or that has netcat installed, run `nc <exit ip> <port>`, press enter. Type some random input and press enter again. If the random input is shown in the first terminal on the computer where the app runs. Then it works.

The above worked for me. So I don't think the app itself is broken. If you have further questions please get in touch with support@mullvad.net, they are better at helping with app usage problems.

**Comment by macducknut** [comment] 2018-10-11 08:31
Ok thanks im going to try that

**Comment by faern** [comment] 2018-11-09 14:46
Closing since we could not reproduce. Port fowarding seems to work fine.

**Closed by faern** 2018-11-09 14:46 UTC
