### ISSUE TITLE
[Feature request] Add option to bypass VPN for certain apps that block VPNs

### ISSUE THREAD

**Issue by Joe12387** [mullvad/mullvadvpn-app#5849] opened 2024-02-23 02:49 UTC
### I have checked if others have suggested this already

- [X] I have checked this issue tracker to see if others have reported similar issues.

### Feature description

Hi.

I've found myself not using Mullvad or any other VPNs on iOS simply because some apps seem to block IPs from VPN providers. I think it would be a good option to have in app to bypass the VPN for certain apps that block VPNs so they're still usable instead of having to disable the VPN entirely. I originally had this issue with ChatGPT, but they no longer seem to be blocking VPNs in app. The platform formerly known as Twitter, however, still blocks VPNs and the app is effectively useless if connected. There probably are other apps/platforms that do this, but these are just some examples. I'm sure others can contribute to a list of apps that block VPNs. This could also apply to Android apps as well, but I don't have an Android device so I can only confirm that some iOS apps do this.

Thanks!

### Alternative solutions

Disconnect from the VPN.

### Type of feature

- [ ] Better privacy/anonymity
- [X] Better at circumventing censorship
- [X] Easier to use
- [ ] Other

### Operating System

- [ ] Android
- [X] iOS
- [ ] Windows
- [ ] macOS
- [ ] Linux

**Comment by Joe12387** [comment] 2024-02-23 02:56
Just came across #3801 so I'm not sure if this is possible and this may be considered a duplicate.

**Comment by Rawa** [comment] 2024-02-26 16:31
Hello @Joe12387 thanks for reaching out. The feature, called Split Tunneling, exists on Android and on certain desktop platforms. You can see the full support list here:
https://github.com/mullvad/mullvadvpn-app?tab=readme-ov-file#features

Hopefully we can add it to the remaining platforms in the near feature, I'm going to close this issue since it is a duplicate of the other feature request.

**Closed by Rawa** 2024-02-26 16:31 UTC
Labels: feature request
