### ISSUE TITLE
While reconnecting after wake, MacBook Air keyboard and trackpad freeze

### ISSUE THREAD

**Issue by shawnyeager** [mullvad/mullvadvpn-app#2122] opened 2020-09-17 02:35 UTC
## Issue report

Operating system: macOS Mojave 10.15.6 (19G2021)

App version: 2020.5

### Issue description

Upon waking from sleep, while Mullvad is reconnecting (slowly), my MacBook Air (Retina, 13-inch, 2019)'s keyboard and trackpad freeze.

Comparatively, my MacBook Pro 2018 running the same version of macOS and Mullvad do not exhibit this behavior.

**Comment by faern** [comment] 2020-09-29 14:01
That's a really strange bug. I have not heard anyone else report it. We do not have any MacBook Airs to test on, so too bad it only seem to happen on the Air version.

I'm not sure what we could possibly do in the app that causes the OS to not respond on input devices. Sounds to me more like an Apple bug rather than a Mullvad bug, but I don't know. Unless we can reproduce it here I think there is a very slim chance of fixing it sadly.

**Comment by Gecky** [comment] 2020-10-05 21:20
I have the exact same issue, I have a 2018 Macbook Pro. If for whatever reason Mullvad is not able to connect, I have to shut down the mac otherwise I can't do anything.

OS: 10.15.7
App Version: 2020.05

**Comment by beingalink** [comment] 2020-10-21 22:10
Perhaps [this](https://news.ycombinator.com/item?id=24839101) and [this](https://news.ycombinator.com/item?id=24839205) (same thread on hacker news) might have sth to do with it. I'm experiencing the same when the connection with mullvad is getting re-established on wakeup with my Macbook. It doesn't always happen though.

**Comment by shawnyeager** [comment] 2020-10-21 22:24
@beingalink Looks like you found the upstream culprit.

**Comment by faern** [comment] 2020-10-22 07:07
We have been debugging it the last few weeks as well and we have seen the DNS + NTP checks that the OS sometimes does. We have been suspecting that to be the culpit for a while. Thanks for the extra resources that kind of confirms our theories :+1: now we might be able to go after this more efficiently.

**Comment by beingalink** [comment] 2020-10-22 14:01
Another thing that is only loosely connected to this issue but might become a problem with upcoming macOS 11 is [this](https://twitter.com/patrickwardle/status/1318465421796782082), discussed in [this](https://news.ycombinator.com/item?id=24838816) hacker news thread. It's about apple being able to bypass 3rd party firewalls but I'm not sure if this might also affect vpn/wireguard services.

**Comment by hulthe** [comment] 2024-10-01 09:17
As far as I know, this is not an issue with newer MacOS versions. Closing since we don't support 10 anymore

**Closed by hulthe** 2024-10-01 09:17 UTC
Labels: macOS
