### ISSUE TITLE
Breakpoint hit upon shutdown / reboot

### ISSUE THREAD

**Issue by FireBird22** [mullvad/mullvadvpn-app#5190] opened 2023-09-24 06:23 UTC
## Issue report

Operating system: Windows 11(22621.2283)
App version: 2023.4 

### Issue description
Breakpoint hit upon shutdown / reboot. Which prevents the system from shutting down / rebooting until handled.
Haven't been able to replicate as to why this occurs, but it is frequent enough, to be worth reporting.

**Screenshot of the error**
https://i.imgur.com/YQSKjal.png

**Comment by raksooo** [comment] 2024-05-16 11:17
I suspect this is caused by Electron/Chromium and we've updated Electron multiple times since this was reported. I'll close this issue but please let me know if this is still an issue and I'll repoen.

**Closed by raksooo** 2024-05-16 11:17 UTC
Labels: bug, Windows, Desktop frontend
