### ISSUE TITLE
Unable to block all network traffic on macOS 12.0 beta 9

### ISSUE THREAD

**Issue by jererobles** [mullvad/mullvadvpn-app#3032] opened 2021-10-11 09:06 UTC
## Issue report

Operating system: macOS 12.0 Beta 9 (21A5543b)

App version: 2021.4

### Issue description

Mullvad is unable to block internet access after upgrading macOS. I also sent a problem report from the app, this issue is mainly for visibility. Feel free to close.

**Comment by revunix** [comment] 2021-10-13 20:15
New Updates: 12.0 Beta (21A5552a) – 2021.5-beta1

Still broken, so the new Beta 10 didn't fix it by himself.

**Comment by faern** [comment] 2021-10-20 09:36
Yes, the beta we released yesterday should fix this issue. This beta might not go stable before Apple releases macOS 12, but we will try to have it out as stable asap.

I'm closing this since the issue is fixed on the master git branch and in the latest beta.

**Closed by faern** 2021-10-20 09:36 UTC
Labels: bug, macOS
