### ISSUE TITLE
Mullvad 2020.6 keeps disconnecting on Fedora 32 with "Connection wg-mullvad deacticated"

### ISSUE THREAD

**Issue by Evernow** [mullvad/mullvadvpn-app#2199] opened 2020-10-21 03:57 UTC
## Issue report

Operating system: Fedora 32 KDE

App version: 2020.6, does not occur with 2020.5

### Issue description

When using Mullvad 2020.6 (downgrading to Mullvad 2020.5 "fixes" the issue) I keep getting constant disconnects every few seconds. When it disconnects I get two notifications from Network management "Connection wg-mullvad deactivated" and then a millisecond afterwards "Connection wg-mullvad activated"

[mullvadlog.txt](https://github.com/mullvad/mullvadvpn-app/files/5413162/mullvadlog.txt)

**Comment by faern** [comment] 2020-10-21 08:36
Looks like a duplicate of #2186

**Closed by faern** 2020-10-21 08:36 UTC
Labels: Linux
