### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by logan2k** [mullvad/mullvadvpn-app#4093] opened 2022-10-26 17:51 UTC
## Issue report

Operating system: <Debian 11>

App version: <2022.5>

### Issue description

<![bug](https://user-images.githubusercontent.com/79699834/198100067-6f696107-075b-42a0-ac1c-315f44d099f5.png), please see the picture>

**Comment by faern** [comment] 2022-11-24 09:38
I'm closing this as it's a duplicate. The issue is with censorship.

**Closed by faern** 2022-11-24 09:38 UTC
