### ISSUE TITLE
Captive portal connexion blocking exception

### ISSUE THREAD

**Issue by FrancoisChastel** [mullvad/mullvadvpn-app#1284] opened 2019-12-01 14:13 UTC
Hey there,

I am not sure this is the right place to post a product request, but could not find any other place.

It would be great to add an exception to Mullvad blocking all connexion for captive portal when connecting to a public Wi-Fi.

**Comment by faern** [comment] 2019-12-02 12:27
Yeah we are aware of this problem. However, it's quite hard to solve with the security guarantees we want to give. To log in to a captive portal we need to allow the device to communicate outside the tunnel. Something we explicitly promise won't happen while you are connected.

You can always disconnect the VPN, log in to your captive portal and then enable the VPN again.

We would love a solution that does not force users to disable the VPN completely to log in. But we are not there yet. Hopefully we will get there one day.

**Comment by faern** [comment] 2020-06-24 13:45
Closing this as a duplicate of #614

**Closed by faern** 2020-06-24 13:45 UTC
