### ISSUE TITLE
[Feature Request] Report Problem Email Notification Upon Submission

### ISSUE THREAD

**Issue by 8227846265** [mullvad/mullvadvpn-app#3763] opened 2022-07-22 03:49 UTC
## Issue report

Operating system: All

App version: All

### Issue description

Hello, I would like to suggest including email confirmation after user submit the Report Problem form in the app.

Currently, the experience is you'll only get an after submission notification that the form was submitted.

It would be nicer if we can receive an email notification, something similar to the others like the one below
![image](https://user-images.githubusercontent.com/66582769/180358213-eb5d3d3d-8dd9-43db-91b8-c95d58b8fa67.png)

I think it would be helpful for the users to receive acknowledgement and a place where they can add additional comments on the report form they sent.

And on Mullvad, the benefit would be to give the users the chance to visit the knowledge base for self-service troubleshooting by telling it to them via the auto-reply email.

Additionally, you'll have fewer problems getting duplicate tickets (how few they may be) in case the user wants to create a new report just to add a new comment to the first report they made.

For your consideration.

Regards.

**Comment by faern** [comment] 2022-07-22 07:32
This is a duplicate of your own older issue #2779. So I will close this as duplicate. If you have additional information or requests in the same area, please post to that issue. However, I will also reply to some points made.

### Serve as a place to hint the users towards self-service by linking the guides

I'd argue that the "damage" is already done at this point. If they fix their own problems after they sent a problem report our support staff still has to process the email. What I think we could do that might be better is to show the user links to the FAQ/guides in the app, before they get to send a problem report. Trying to make them self-service the issue *first*. This could be a good suggestion.

### Reduce duplicate tickets

As stated in the other issue. We don't have an issue with duplicate tickets.

### An email thread so the user has some place to put additional information

Yeah, this could be helpful. So tho user can report further findings in order to help our support figure out the issue. However, we don't have any ticketing system, it's just emails. So from our point of view it would be exactly the same if you just emailed support@mullvad.net from the same email address you wrote in the problem report form and say "Hey, I have some additional information to add to my previous report". Our support staff is competent and efficient, they will be able to match those emails with each other :+1:

### A more reassuring acknowledgement towards the user that the submission went through.

As stated in the other issue. We get basically no duplicate at all. Meaning most users probably trust the submission success message in the app? If the app shows that the report was successfully sent, you can be sure that it reached our API. There could of course be a bug somewhere that makes it not propagate from there to our support. But if there were such bug it could be approximately equally likely that it happens while the user still get their confirmation email. So it's not really helping much.

But maybe it would be good for transparency if the user gets a copy of the report they sent. So they can (again) look at the logs they submitted to us. And it servers as an historical data point that they contacted support.

Since this will be implemented in our backend service, and not the app, I'll forward this feedback to the service team.

**Closed** 2022-07-22 07:52 UTC

**Comment by 8227846265** [comment] 2022-07-22 09:42
Thanks for the feedback. I forgot I made the previous ticket awhile back. I guess it's still a pain point for me still from then till now.

Personally. The reason why I prefer having the confirmation email for the following purposes
* Confirmation that the report I sent was received
* I can submit additional input
* In case I don't get a response, let say X days later. I can follow up.
* I don't have to create more than 1 email thread for one report.

Looking forward for any form of implementation of this in the Mullvad apps and backend if it gets considered.
