### ISSUE TITLE
issue in latest release while building

### ISSUE THREAD

**Issue by TheTanmay1** [mullvad/mullvadvpn-app#5218] opened 2023-10-02 09:43 UTC
## Issue report

Operating system: Using android studio on LInux Mint

App version:   android/2023.6
### Issue description

The project is using an incompatible version (AGP 8.1.0) of the Android Gradle plugin. Latest supported version is AGP 8.0.2

**Comment by Rawa** [comment] 2023-10-02 12:03
@TheTanmay1 Are you running the latest version of android studio?

**Comment by Rawa** [comment] 2023-10-10 10:31
Closing, can't reproduce. Probably user is running an old version of Android Studio.

**Closed by Rawa** 2023-10-10 10:31 UTC
Labels: Android

**Comment by TheTanmay1** [comment] 2023-10-10 16:42
thanks a lot it solved the issue
