### ISSUE TITLE
Integrate app-tracking blocking option into the android app [Feature request]

### ISSUE THREAD

**Issue by Mr-Bajs** [mullvad/mullvadvpn-app#4372] opened 2023-02-19 13:09 UTC
## Issue report

Operating system: Android 13

App version: 2022.3

### Issue description

An android you can't use tech that somehow uses the VPN to block som apptrackers, at the same time using a VPN. I'm refer to technology such as [Tracker Control](https://github.com/TrackerControl/tracker-control-android) and the [DuckDuckGo blocker app.](https://spreadprivacy.com/app-tracking-protection-open-beta/)

It would be great if the mullvad app somehow would integrate the app-trackning block technology into the mullvad app, so the user could use both tools for improved privacy. Of course this would be optional.

**Comment by faern** [comment] 2023-02-20 10:42
Thanks for the feature request. I'll close this as a duplicate of #2786

**Closed by faern** 2023-02-20 10:42 UTC
Labels: Android, feature request
