### ISSUE TITLE
allows split tunneling with "exclude all" over wireguard, same as with openvpn

### ISSUE THREAD

**Issue by asdffdsazqqq** [mullvad/mullvadvpn-app#5159] opened 2023-09-18 00:33 UTC
hello, thanks,

Operating system:  windows 22H2 64bit
App version: 2023.4
### Issue description
i only need for firefox to access the socks5 proxy server over mullvad vpn

for years, using **openvpn**, and ### https://mullvad.net/en/help/split-tunneling-mullvad-vpn/
that works great, as it would not change the default route, and would not change the routing table.
in effect, split tunnel where all traffic is excluded by default.

now, i need the same over **wireguard**, spent days reading, experimenting. cannot get it to work.
tried `Table = off`  and other attempts, but could never get that working.
i tried using the mullvad app, tried using official wireguard client.

run wireguard vpn so it does not change default routes, does not change routing table.
easy access to proxy servers, so i can use mullvad browser with the mullvad browser extension

also, i need to transfer large amount of data to cloud server, windows updates, etc and do not want that traffic to be forced over mullvad vpn
and at the same time have access to socks5 proxy server
thanks

**Comment by pinkisemils** [comment] 2023-09-18 11:16
Closing as this is a dupe of #2808

**Closed by pinkisemils** 2023-09-18 11:16 UTC
