### ISSUE TITLE
[Feature Request] Whitelist / blacklist SSIDs

### ISSUE THREAD

**Issue by NoMonkeyNoMission** [mullvad/mullvadvpn-app#783] opened 2019-04-01 10:00 UTC
My home router is connected to Mullvad. Thus, when I'm on my home network, I do not need the Mullvad App (on macOS in my case) to connect. It would be great to be able to add an SSID whitelist or blacklist to the Mullvad app so that, for example, it does not connect when on specified SSIDs.

I can do this using [NetworkMate](https://maddox.io/) and the Mullvad CLI, but it would be really convenient to have built-in support similar to that found in the [Encrypt.me](https://encrypt.me/) App (they refer to 'trusted' and 'untrusted' networks), and the Wireguard iOS app.

**Comment by faern** [comment] 2019-04-01 10:41
Thanks for the feedback. The app currently does not in any way differentiate between networks. It has no concept of SSID. Nor wifi vs cable for that matter. But I know we have briefly talked about this in the past. I can add it to our wishlist.

**Comment by geekinaboxx** [comment] 2019-04-10 15:29
Looks like the official Wireguard APp for iOS has added this ability (as has the iOS app):

![ondemand](https://user-images.githubusercontent.com/5023467/55892173-b8d5cd00-5bad-11e9-90dd-2037b7315f05.jpg)

**Comment by faern** [comment] 2021-06-11 09:40
I'm going to close this as a duplicate of #1884. I know this issue is older. But I decided to converge around the other one as I update its title to be more correct and easier to find.

**Closed by faern** 2021-06-11 09:40 UTC
Labels: feature request
