### ISSUE TITLE
Windows app gets wider and wider when switching screens off

### ISSUE THREAD

**Issue by tbloch1** [mullvad/mullvadvpn-app#4166] opened 2022-11-23 13:25 UTC
## Issue report

Operating system: Windows 10 (10.0.19045 Build 19045)

App version: 2022.5

### Issue description

When screen resolution changes, and changes back, mullvad app gets wider and wider.

Can be reset by repinning to the taskbar and unpinning again.

This occurs every time I switch my displayport monitor off (since the PC then only recognises the smaller monitor). Main monitor 21:9/3440x1440, secondary monitor 16:9/1920x1080.

I assume that somewhere some code is dynamically changing the size of the app based on the screen resolution.

**Comment by faern** [comment] 2022-11-24 07:45
I believe this is a duplicate of #3120. Can be re-opened if it's a different bug.

**Closed by faern** 2022-11-24 07:45 UTC

**Comment by tbloch1** [comment] 2022-11-25 09:58
I don't think it's the same, since I have no issues seeing all the buttons, the actual window is getting wider, rather than just the contents.

Here's a screenshot: http://prntscr.com/Te0AIZ0jvJFh

Maybe it's the same underlying issue manifesting differently, but I'm not sure.

**Comment by faern** [comment] 2022-11-25 10:28
It could be different. @raksooo is currently experimenting with a fix that should stop the window from changing size. He might get back to you with a dev build to test it out.

**Comment by raksooo** [comment] 2022-11-25 13:59
@tbloch1 Would you like to test a dev-build that might have fixed this? Dev-builds haven't gone through our internal testing and we can't guarantee the security of them.

https://releases.mullvad.net/builds/2022.5-dev-d219f0+test-fix-incorrect-size/

If the window still gets wider, does it reset if you press the tray icon? Or hide it and reopen?
