### ISSUE TITLE
'Switch' and 'disconnect' buttons have ended up badly miscentered; settings unavailable

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [mullvad/mullvadvpn-app#4928] opened 2023-07-25 15:42 UTC
## Issue report

Operating system: Windows 10 Pro - 22H2 (2009: 19045)

App version: 2023.4

### Issue description

Suddenly the app looks like this:

![2023-07-25_16-36](https://github.com/mullvad/mullvadvpn-app/assets/47056543/3b88653e-3f06-4ac2-be57-e7833b8a651b)

And now . . it's back to normal. I do not know how to reproduce the problem. Here is some further information that may be useful.

My screen resolution: 2560 x 1440.
My display DPI: larger than usual. I'd give the exact value but Windows seems to give me no easy way of seeing that value (!).

**Comment by LinuxOnTheDesktop** [comment] 2024-02-09 02:07
I find that this report is a duplicate of open issue #3120 (and I still have the problem).

**Comment by raksooo** [comment] 2024-02-12 07:57
Thanks for reporting! Yes, this is a duplicate of #3120. I'll close this one and let discussion continue in the other one.

**Closed by raksooo** 2024-02-12 07:57 UTC
