### ISSUE TITLE
Feature Request (Android) "Mock Location"

### ISSUE THREAD

**Issue by Jpersh27** [mullvad/mullvadvpn-app#2417] opened 2021-01-26 03:23 UTC
1.) Is there any plans to utilize or introduce the Mock Location feature under Android Developer Settings?

-If a feature such as GPS Override ("Mock Location") is supported and enabled within the Mullvad application, then any app on your Android device that requests access to your physical coordinates (GPS/Location Access Permission) will be overridden by the coordinates of the selected VPN server your connected too.

-For example, say a user is physically located in the USA and is connected to one of Mullvads servers in Sweden. Whenever any app on the users Android device asks for their GPS location it will now receive the new updated coordinates (Longitude and Latitude) for the location of the VPN server in Sweden as opposed to their actual GPS location in the USA. 

-One current and well known vpn service called ''Surf Shark" offers this feature already, and it already works on there Android version of there VPN application. I tested there service and utilized this feature and it was easy to enable under developer options. They included easy to follow step by step instructions how to enable the feature.

-I used it on two diffrent Android phones and two diffrent versions of Android. Versions being Android 9 pie and Android 10 Q. The feature worked seamlessly and didn't leak my location ever, and matched the same location of the server I was connected too. 

-Overall I think its a useful feature and better then having to use a third party app alongside your VPN to spoof your GPS Location.

-Thank you and I hope I explained everything well enough. I hope to hear back from someone here soon.

**Comment by faern** [comment] 2021-01-26 14:49
Going to close this as duplicate of #2119. I don't have any information newer than the one I posted in that issue. So will copy paste the most important section from that answer:

> But the only way this can be done, to my knowledge, is with either a rooted phone or if the phone is running in developer mode. Neither of which we want to recommend our users to do.

Please use the other thread to follow any updates on this feature.

**Closed by faern** 2021-01-26 14:49 UTC
