### ISSUE TITLE
Feature: Auto IP renew

### ISSUE THREAD

**Issue by xPythh** [mullvad/mullvadvpn-app#3386] opened 2022-02-26 16:58 UTC
Hey ! I just started using MullVad and i think its a really great VPN ! 
But i would like to suggest two things that could be offered as an option for all users:
> Automatic Location Change (With interval such as 10mins, 30mins, 1h, with possibility to pick certains country for switching)
> Slow connection detection with automatic location change 

I hope this feature will be appreciated by more than one !

**Comment by faern** [comment] 2022-03-01 15:46
> Automatic Location Change

The first part is a duplicate of #2623 and #3236. Thanks for the suggestion, but please check if there are other issues/feature requests open first.

>  Slow connection detection with automatic location change

This would be technically very hard to do in a satisfactory way. We can see if the device shuffles a lot of network traffic or not. But when this number is low it could be due to a slow connection or simply because no program on the device is currently using a lot of bandwidth. Hard to know. We could send our own traffic to test if the connection is slow. But that has many other downsides. Such as occupying the user's connection, using up battery, bogging down our own servers with traffic serving no good purpose etc.. I'm sorry. But I don't think we'll implement this for the reasons stated.

**Closed by faern** 2022-03-01 15:46 UTC
