### ISSUE TITLE
mullvad GUI window randomly turns white when not in use

### ISSUE THREAD

**Issue by zzzsl9** [mullvad/mullvadvpn-app#5611] opened 2023-12-20 19:45 UTC
### Is it a bug?

- [X] I know this is an issue with the app, and contacting Mullvad support is not relevant.

### I have checked if others have reported this already

- [X] I have checked the issue tracker to see if others have reported similar issues.

### Current Behavior

![Screenshot_20231220_142444](https://github.com/mullvad/mullvadvpn-app/assets/126982425/f6c0adea-8240-4cb5-9bea-57f7a66852e2)

### Expected Behavior

It should usually show the vpn connection status.

### Steps to Reproduce

1. Open the mullvad GUI. I downloaded from the AUR on arch linux as mullvad-vpn-bin.
2. Leave the window open on desktop (I'm using KDE) connected or not connected.
3. Do stuff on other windows, such as using browser.
4. Go back to your desktop to see the mullvad GUI window and then sometimes it's white.

### Operating system version

Linux

### Mullvad VPN app version

2024.1-beta1

### Additional Information

This has been for as long as I can remember on linux. I found another issue open about the same thing here: https://github.com/mullvad/mullvadvpn-app/issues/3068

Tried to bump and nothing happened.

I haven't seen this happening to any other app on my desktop. I am opening this in hopes this is fixed.

**Comment by faern** [comment] 2023-12-21 09:13
I'm sorry, but opening more issues just because there is no progress in one is not really helping. I can understand it's frustrating. It's a known issue and I'll close this as a duplicate of #3068. We cannot really reproduce this ourselves. We have tried, but the window just never turns white. Thank you for your list of steps to reproduce, maybe those help, we'll see.

@zzzsl9 How often is it white? Like does this happen once a month or every five minutes of using the app?

@raksooo Can you try these steps under KDE?

**Closed by faern** 2023-12-21 09:13 UTC
Labels: bug

**Comment by Kimble303** [comment] 2024-01-03 08:38
Happens with Windows 10 and 11 too.

https://www.reddit.com/r/mullvadvpn/comments/18gt0ia/strange_glitch_with_mullvad_app_gui_on_win_10/
