### ISSUE TITLE
option for show list device and set label to understand which name is for which device

### ISSUE THREAD

**Issue by mohammadRezaeian** [mullvad/mullvadvpn-app#5199] opened 2023-09-27 11:39 UTC
## Issue report

Operating system: Android, Gnu\Linux

App version: 2023.6

### Issue description
Hi,
Is it possible please add option for show list device connect to account from app
and possible putting a name label to understand which name is for which device

**Comment by MrChocolatine** [comment] 2023-09-27 12:29
I remember I asked something very similar in #3717 .

**Comment by faern** [comment] 2023-09-27 13:24
Closing as duplicate of #3717. Thanks for the suggestion, we are discussing it internally. Basically the only blocker is figuring out how to integrate this feature without having too many buttons / cognitive overload on the account page from there being too many things one can do.

**Closed by faern** 2023-09-27 13:24 UTC

**Comment by raksooo** [comment] 2023-09-28 06:52
@mohammadRezaeian We initially discussed having labels/names for devices that the user could set but decided not to. The problem with allowing users to add labels to devices is that it would require us to collect data that we do not want to have. Currently our service doesn't require or allow users to give us any personal data.
