### ISSUE TITLE
Issue -> Mullvad + NextDNS

### ISSUE THREAD

**Issue by scafroglia93** [mullvad/mullvadvpn-app#1623] opened 2020-04-02 06:13 UTC
I would like to be able to use nextdns in mating with mullvad but, on pc I am unable because the selected dns are those of mullvad making it impossible to use

**Comment by Atrate** [comment] 2020-04-02 08:07
Duplicate of #473

**Comment by p1r473** [comment] 2020-04-09 00:35
I cant connect to Mullvad while Pihole enabled.
I got an error about DNS System Preference couldn't be changed.

**Comment by faern** [comment] 2020-04-09 08:53
@p1r473 Please send a problem report to our support via the app. It's under settings -> report a problem.

**Comment by p1r473** [comment] 2020-04-10 15:12
I reported it in the app already
![image](https://user-images.githubusercontent.com/9235633/79001295-35cab800-7b1c-11ea-94d0-f9c1ee679ea5.png)

**Closed** 2020-09-27 06:24 UTC
